install_start:
    path:     /install/start/
    defaults: { _controller: SystemBundle:Install:index }
install_check_mailer_parameters:
    path:     /install/mailer/
    defaults: { _controller: SystemBundle:Install:mailer }
install_misc_check:
    path:     /install/miscellaneous/
    defaults: { _controller: SystemBundle:Install:miscellaneous }
install_build_system:
    path:     /install/build/
    defaults: { _controller: SystemBundle:Install:build }
install_build_complete:
    path:     /install/complete/
    defaults: { _controller: SystemBundle:Install:complete }
update_start:
    path:     /update/start/
    defaults: { _controller: SystemBundle:Update:index }
update_database:
    path:     /update/database/
    defaults: { _controller: SystemBundle:Update:database }
setting_manage:
    path:     /setting/manage/
    defaults: { _controller: SystemBundle:Setting:index }
setting_upload:
    path:     /setting/upload/
    defaults: { _controller: SystemBundle:Setting:upload }
setting_edit:
    path:     /setting/{id}/edit/
    defaults: { _controller: SystemBundle:Setting:edit }
setting_edit_name:
    path:     /setting/{name}/editName/
    defaults: { _controller: SystemBundle:Setting:editName }
plugin_manage:
    path:     /plugin/manage/
    defaults: { _controller: SystemBundle:Plugin:manager }
setting_create:
    path: /setting/create/
    defaults: { _controller: SystemBundle:Setting:create }
bundle_list:
    path: /bundles/list/
    defaults: { _controller: SystemBundle:Bundle:list }