update_start:
    path:     /update/start/
    defaults: { _controller: SystemBundle:Update:index }
update_database:
    path:     /update/database/
    defaults: { _controller: SystemBundle:Update:database }
setting_manage:
    path:     /setting/manage/
    defaults: { _controller: SystemBundle:Setting:index }
setting_upload:
    path:     /setting/upload/
    defaults: { _controller: SystemBundle:Setting:upload }
setting_edit:
    path:     /setting/{id}/edit/
    defaults: { _controller: SystemBundle:Setting:edit }
setting_edit_name:
    path:     /setting/{name}/editName/
    defaults: { _controller: SystemBundle:Setting:editName }
plugin_manage:
    path:     /plugin/manage/
    defaults: { _controller: SystemBundle:Plugin:manager }
setting_create:
    path: /setting/create/
    defaults: { _controller: SystemBundle:Setting:create }
bundle_list:
    path: /bundles/list/
    defaults: { _controller: SystemBundle:Bundle:list }
bundle_update:
    path: /bundle/{name}/update/
    defaults: { _controller: SystemBundle:Bundle:update }
bundle_database_update:
    path: /bundle/update/database/
    defaults: { _controller: SystemBundle:Bundle:database }
