setting_manage:
    path:     /setting/manage/
    defaults: { _controller: SystemBundle:Setting:index }
setting_edit:
    path:     /setting/{id}/edit/
    defaults: { _controller: SystemBundle:Setting:edit }
setting_edit_name:
    path:     /setting/{name}/editName/
    defaults: { _controller: SystemBundle:Setting:editName }
setting_create:
    path: /setting/create/
    defaults: { _controller: SystemBundle:Setting:create }
bundle_list:
    path: /bundles/list/
    defaults: { _controller: SystemBundle:Bundle:list }
bundle_update:
    path: /bundle/{name}/update/
    defaults: { _controller: SystemBundle:Bundle:update }
bundle_database_update:
    path: /bundle/update/database/
    defaults: { _controller: SystemBundle:Bundle:database }
install_build_system:
    path: /install/build/
    defaults: { _controller: SystemBundle:Install:build }
install_build_complete:
    path: /install/complete/
    defaults: { _controller: SystemBundle:Install:complete }
bundle_default_remove:
    path: /bundles/default/remove/
    defaults: { _controller: SystemBundle:Bundle:removeFile }
houses_edit:
    path:  /houses/
    defaults: { _controller: SystemBundle:House:edit }