# System Bundle
parameters:
    version:
        system: '0.0.04'
        database: '0.0.04'
    settingPagination:
        alias: s
        sortBy:
            Name: 
                s.displayName: ASC
                s.description: ASC
            Description: 
                s.description: ASC
                s.displayName: ASC
        limit: '10'
        searchList:
            - s.displayName
            - s.description
        select:
            - s.displayName
            - s.description
            - s.id

services:
    monolog.formatter.session_request:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] [%%extra.token%%] %%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"
#    monolog.processor.session_request:
#        class: Busybee\Core\SystemBundle\Model\SessionRequestProcessor
#        arguments:  ["@session"]
#        tags:
#            - { name: monolog.processor, method: processRecord }
    monolog.logger.busybee:
        class: Busybee\Core\SystemBundle\Model\Logger
        arguments: ['@logger']
        tags:
            - { name: monolog.logger, channel: busybee }
    doctrine.tblprefix_subscriber:
        class: Busybee\Core\SystemBundle\Subscriber\TablePrefixSubscriber
        arguments: 
            - '%database_prefix%'
        tags:
            - { name: doctrine.event_subscriber }    
    system.setting.repository:
        class: Busybee\Core\SystemBundle\Repository\SettingRepository
        factory: 
            - "@doctrine"
            - getRepository 
        arguments: 
            - "SystemBundle:Setting"
    setting.repository:
        class: Busybee\Core\SystemBundle\Repository\SettingRepository
        factory: 
            - "@doctrine"
            - getRepository 
        arguments: 
            - "SystemBundle:Setting"
    system.update.manager:
        class: Busybee\Core\SystemBundle\Update\UpdateManager
        arguments: 
            - "@my_service_container"
    system.password.manager:
        class: Busybee\Core\SystemBundle\Password\PasswordManager
    busybee.writeDoctrine.listener:
        class: Busybee\Core\SystemBundle\EventListener\WriteDoctrineListener
        arguments: 
            - "@my_service_container"
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }
    setting.manager:
        class: Busybee\Core\SystemBundle\Setting\SettingManager
        arguments: 
            - '@my_service_container'
    plugin.manager:
        class: Busybee\Core\SystemBundle\Plugin\PluginManager
        arguments: 
            - "@my_service_container"
    setting.pagination:
        class: Busybee\Core\SystemBundle\Model\SettingPagination
        arguments: 
            - '%settingPagination%'
            - '@setting.repository'
            - '@my_service_container'
    setting.extension:
        class: Busybee\Core\SystemBundle\Model\SettingExtension
        arguments:
            - '@setting.manager'
            - '@menu.manager'
            - '@busybee.parameters'
        tags:
            - { name: twig.extension }
    test.plugin.manage:
        class: Busybee\Core\SystemBundle\Model\Test\TestPluginManage
        arguments:
            - '@my_service_container'
    my_service_container:
        class: Busybee\Core\SystemBundle\Model\myContainer
        arguments:
            - '@service_container'
    test.update.available:
        class: Busybee\Core\SystemBundle\Model\Test\TestUpdateAvailable
        arguments:
            - '@my_service_container'
    system.SettingListType:
        class: Busybee\Core\SystemBundle\Form\SettingListType
        arguments:
            - '@setting.manager'
        tags:
            - { name: form.type }
    system.SettingType:
        class: Busybee\Core\SystemBundle\Form\SettingType
        arguments:
            - '@setting.repository'
        tags: 
            - { name: form.type }    
    validator.org.name.short:
        class: Symfony\Component\Validator\Constraints\Length
        arguments:
            - {max: 8}
    install.manager:
        class: Busybee\Core\SystemBundle\Model\InstallManager
        arguments:
            - '%kernel.project_dir%'
            - '@doctrine.dbal.connection_factory'
            - '@system.password.manager'
    busybee.parameters:
        public: false
        class: stdClass
        factory:
            - '@my_service_container'
            - 'getParameterBag'
