# System Bundle
parameters:
    version:
        system: '0.0.04'
        database: '0.0.04'
    settingPagination:
        alias: s
        sortBy:
            Name: 
                s.displayName: ASC
                s.description: ASC
            Description: 
                s.description: ASC
                s.displayName: ASC
        limit: '10'
        searchList:
            - s.displayName
            - s.description
        select:
            - s.displayName
            - s.description
            - s.id
    SystemBundle:
        settings:
            resources:
                - 'SystemBundle/Resources/config/Settings/Settings_0_0_01.yml'
                - 'SystemBundle/Resources/config/Settings/Settings_0_0_02.yml'
                - 'SystemBundle/Resources/config/Settings/Settings_0_0_03.yml'
                - 'SystemBundle/Resources/config/Settings/Settings_0_0_04.yml'
        version: 0.0.04


services:
    monolog.formatter.line_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] [%%extra.token%%] %%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"
    busybee_core_system.subscriber.table_prefix_subscriber:
        class: Busybee\Core\SystemBundle\Subscriber\TablePrefixSubscriber
        arguments: 
            - '%database_prefix%'
        tags:
            - { name: doctrine.event_subscriber }    
    busybee_core_system.repository.setting_repository:
        class: Busybee\Core\SystemBundle\Repository\SettingRepository
        factory: 
            - "@doctrine"
            - getRepository 
        arguments: 
            - "SystemBundle:Setting"
    busybee_core_system.password.password_manager:
        class: Busybee\Core\SystemBundle\Password\PasswordManager
    busybee_core_system.event_listener.modify_row_listener:
        class: Busybee\Core\SystemBundle\EventListener\ModifyRowListener
        arguments: 
            - "@busybee_core_system.model.my_container"
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }
    busybee_core_system.setting.setting_manager:
        class: Busybee\Core\SystemBundle\Setting\SettingManager
        arguments: 
            - '@busybee_core_system.repository.setting_repository'
            - '@session'
            - '@kernel'
    busybee_core_system.model.setting_pagination:
        class: Busybee\Core\SystemBundle\Model\SettingPagination
        arguments: 
            - '%settingPagination%'
            - '@busybee_core_system.repository.setting_repository'
            - '@busybee_core_system.model.my_container'
    busybee_core_system.model.my_container:
        class: Busybee\Core\SystemBundle\Model\myContainer
        arguments:
            - '@service_container'
    busybee_core_system.model.test.test_update_available:
        class: Busybee\Core\SystemBundle\Model\Test\TestUpdateAvailable
        arguments:
            - '@busybee_core_system.model.my_container'
    busybee_core_system.form.setting_list_type:
        class: Busybee\Core\SystemBundle\Form\SettingListType
        arguments:
            - '@busybee_core_system.setting.setting_manager'
        tags:
            - { name: form.type }
    busybee_core_system.form.setting_type:
        class: Busybee\Core\SystemBundle\Form\SettingType
        arguments:
            - '@busybee_core_system.repository.setting_repository'
        tags: 
            - { name: form.type }    
    busybee_core_system.validator.constraints.length:
        class: Symfony\Component\Validator\Constraints\Length
        arguments:
            - {max: 8}
    busybee_core_system.model.bundle_manager:
        class: Busybee\Core\SystemBundle\Model\BundleManager
        arguments:
            - '@kernel'
    busybee_core_system.model.flash_bag_manager:
        class: Busybee\Core\SystemBundle\Model\FlashBagManager
        arguments:
          - '@session.flash_bag'
          - '@translator'
    busybee_core_system.router.advanced_loader:
        class: Busybee\Core\SystemBundle\Router\AdvancedLoader
        tags:
            - { name: routing.loader }
        arguments:
            - '@kernel'
    busybee_core_system.model.message_manager:
        class: Busybee\Core\SystemBundle\Model\MessageManager
    busybee_core_system.model.house_manager:
        class: Busybee\Core\SystemBundle\Model\HouseManager
        arguments:
            - '@busybee_core_system.setting.setting_manager'
            - "@doctrine.orm.default_entity_manager"
    busybee_core_system.validator.constraints.houses_validator:
        class: Busybee\Core\SystemBundle\Validator\Constraints\HousesValidator
        arguments:
            - "@busybee_core_system.model.house_manager"
        tags:
            - { name: validator.constraint_validator, alias: houses_validator }
    busybee_core_system.form.houses_type:
        class: Busybee\Core\SystemBundle\Form\HousesType
        arguments:
            - '@busybee_core_system.setting.setting_manager'
        tags:
            - { name: form.type }
    busybee_core_system.form.house_type:
        class: Busybee\Core\SystemBundle\Form\HouseType
        arguments:
            - '@busybee_core_system.model.house_manager'
        tags:
            - { name: form.type }
    busybee_core_system.model.days_times_manager:
        class: Busybee\Core\SystemBundle\Model\DaysTimesManager
        arguments:
            - '@busybee_core_system.setting.setting_manager'
            - "@doctrine.orm.default_entity_manager"
    busybee_core_system.form.day_type:
        class: Busybee\Core\SystemBundle\Form\DayType
        arguments:
            - '@busybee_core_system.model.days_times_manager'
        tags:
            - { name: form.type }
    busybee_core_system.form.time_type:
        class: Busybee\Core\SystemBundle\Form\TimeType
        arguments:
            - '@busybee_core_system.model.days_times_manager'
        tags:
            - { name: form.type }
    busybee_core_system.validator.constraints.times_validator:
        class: Busybee\Core\SystemBundle\Validator\Constraints\TimesValidator
        arguments:
            - "@busybee_core_system.model.days_times_manager"
        tags:
            - { name: validator.constraint_validator, alias: times_validator }
