home_page:
    path:     /
    defaults: { _controller: BusybeeHomeBundle:Default:index }
error_page:
    path:     /error/{message}
    defaults: { _controller: BusybeeHomeBundle:Error:index }
home_template:
    path:     /template
    defaults: { _controller: BusybeeHomeBundle:Template:index }