# src\Busybee\RecordBundle\Resources\config\doctrine\ParentType.orm.yml
Busybee\RecordBundle\Entity\ParentType:
    type: entity
    table: record_parent
    repositoryClass: Busybee\RecordBundle\Entity\ParentTypeRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        record:
            type: integer
            column: record_id
        field:
            type: integer
            column: field_id
        table:
            type: integer
            column: table_id 
        value:
            type: text
        user:
            type: integer 
            column: user_id
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    lifecycleCallbacks:
        prePersist: [ updateLastModified ]
        preUpdate: [ updateLastModified ]
