# src\Busybee\RecordBundle\Resources\config\doctrine\PhotoType.orm.yml
Busybee\RecordBundle\Entity\PhotoType:
    type: entity
    table: record_photo
    repositoryClass: Busybee\RecordBundle\Entity\PhotoTypeRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        record:
            type: integer
            column: record_id
        field:
            type: integer
            column: field_id
        table:
            type: integer
            column: table_id 
        value:
            type: blob
        user:
            type: integer
            column: user_id
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    lifecycleCallbacks:
        prePersist: [ updateLastModified ]
        preUpdate: [ updateLastModified ]
