# src\Busybee\RecordBundle\Resources\config\doctrine\Record.orm.yml
Busybee\RecordBundle\Entity\Record:
    type: entity
    table: record_key
    repositoryClass: Busybee\RecordBundle\Entity\RecordRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        record:
            type: integer
            column: record_id
        table:
            type: integer
            column: table_id 
        user:
            type: integer
            column: user_id
        createdOn:
            type: datetime
    lifecycleCallbacks:
        prePersist: [ updateLastModified ]
        preUpdate: [ updateLastModified ]
