# src\Busybee\RecordBundle\Resources\config\doctrine\StringType.orm.yml
Busybee\RecordBundle\Entity\StringType:
    type: entity
    table: record_string
    repositoryClass: Busybee\RecordBundle\Entity\StringTypeRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        record:
            type: integer
            column: record_id
        field:
            type: integer
            column: field_id
        table:
            type: integer
            column: table_id 
        value:
            type: string
        user:
            type: integer
            column: user_id
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    lifecycleCallbacks:
        prePersist: [ updateLastModified ]
        preUpdate: [ updateLastModified ]
