# System
parameters:
    nodes:
        1:
            name: System
            label: menu.admin.node
            role: ROLE_USER
            order: 1
            menu: 1
    items:
        10:
            label: menu.admin.school
            name: School Admin
            role: ROLE_REGISTRAR
            node: 1
            order: 10
            route: calendar_years
        11:
            label: menu.admin.system
            name: System Admin
            role: ROLE_REGISTRAR
            node: 1
            order: 11
            route: setting_manage
        12:
            label: menu.admin.timetable
            name: User Admin
            role: ROLE_REGISTRAR
            node: 1
            order: 13
            route: calendar_years
        13:
            label: menu.admin.user
            name: User Admin
            role: ROLE_REGISTRAR
            node: 1
            order: 13
            route: security_user_list
    sections:
        School Admin:
            groupings:
                setting_edit_houses:
                    label: menu.setting.houses
                    role: ROLE_REGISTRAR
                    route: houses_edit
                    params: {}
            years_days_times:
                calendar_years:
                    label: menu.year.manage
                    role: ROLE_REGISTRAR
                    route: calendar_years
                    params: {}
                school_days_times:
                    route: school_days_times
                    role: ROLE_REGISTRAR
                    label: menu.setting.school.daysandtimes
                    params: {}
                year_calendar:
                    route: year_calendar
                    role: ROLE_REGISTRAR
                    label: menu.year.calendar.display
                    params: {}
        System Admin:
            extend_update:
                manage_bundles:
                    route: bundle_list
                    label: menu.site.bundle.list
                    role: ROLE_REGISTRAR
                    params: {}
                acknowledgement:
                    route: acknowledgement
                    label: menu.site.acknowledgement
                    role: []
                    params: {}
            settings:
                setting_manage:
                    label: menu.setting.manage
                    role: ROLE_REGISTRAR
                    route: setting_manage
                    params: {}
                page_security:
                    label: menu.setting.page.security
                    role: ROLE_REGISTRAR
                    route: page_list
                    params: {}
            hidden:
                - setting_edit
                - setting_edit_name
                - page_edit
        Timetable Admin:
            timetable:
                calendar_years:
                    label: menu.calendar.manage
                    role: ROLE_REGISTRAR
                    route: calendar_years
                    params: {}
            hidden:
                - year_edit
        User Admin:
            user_management:
                security_user_list:
                    label: menu.user.list
                    role: ROLE_REGISTRAR
                    route: security_user_list
                    params: {}
            hidden: []
