# System
parameters:
    nodes:
        1:
            name: System
            label: menu.admin.node
            role: ROLE_USER
            order: 1
            menu: 1
    items:
        10:
            label: menu.admin.school
            name: School Admin
            role: ROLE_REGISTRAR
            node: 1
            order: 10
            route: calendar_years
        12:
            name: Manage System Settings
            label: menu.site.setting.manage
            role: ROLE_REGISTRAR
            node: 1
            route: setting_manage
            order: 12
            menu: 12
        120:
            name: Manage Individual Setting
            label: menu.site.setting.individual
            role: ROLE_REGISTRAR
            node: 12
            route: setting_manage
            order: 120
        124:
            name: Bundle List
            label: menu.site.bundle.list
            role: ROLE_SYSTEM_ADMIN
            node: 12
            route: bundle_list
            order: 124
    sections:
        School Admin:
            groupings:
                setting_edit_houses:
                    label: menu.setting.houses
                    role: ROLE_REGISTRAR
                    route: houses_edit
                    params: {}
            other:
                setting_manage:
                    label: menu.setting.manage
                    role: ROLE_REGISTRAR
                    route: setting_manage
                    params: {}
            years_days_times:
                calendar_years:
                    label: menu.year.manage
                    role: ROLE_REGISTRAR
                    route: calendar_years
                    params: {}
                school_days_times:
                    route: school_days_times
                    role: ROLE_REGISTRAR
                    label: menu.setting.school.daysandtimes
                    params: {}
                year_calendar:
                    route: year_calendar
                    role: ROLE_REGISTRAR
                    label: menu.year.calendar.display
                    params: {}
