Busybee\People\StaffBundle\Entity\Staff:
    properties:
        staffType:
            - \Busybee\Core\TemplateBundle\Validator\SettingChoice:
                name: 'Staff.Categories'
            - NotBlank: ~
        jobTitle:
            - NotBlank: ~
        house:
            - \Busybee\Core\TemplateBundle\Validator\SettingChoice:
                name: 'house.list'
