house.list:
    type: 'array'
    displayName: 'House List'
    description: "House list used in your school."
    role: 'ROLE_REGISTRAR'
student.groups:
    type: array
    displayName: Student Groups
    description: Usually the year groups that attend this school.
    role: ROLE_REGISTRAR
    value:
        Year 7: Y7
        Year 8: Y8
student.enrolment.status:
    type: array
    displayName: Student Enrolment Status
    description: Reflects the status of student enrolment.
    role: ROLE_ADMIN
    value:
        Future: Future
        Current: Current
        Past: Past
        Archived: Archived
department.type.list:
    type: array
    displayName: Department Type List
    role: ROLE_REGISTRAR
    description: Types of departments within the institute.
    value:
        Learning Area: Learning Area
        Administration: Administration