Address.Format:
    type: 'twig'
    displayName: 'Address Format'
    description: 'A template for displaying an address.'
    role: 'ROLE_REGISTRAR'
Address.ListLabel:
    type: 'twig'
    displayName: 'Address Label List'
    description: 'A template to convert the entity values into a string label for autocomplete.'
    role: 'ROLE_ADMIN'
Person.GenderList:
    type: 'array'
    displayName: 'Gender List'
    description: 'A list of genders used in the system.'
    role: 'ROLE_REGISTRAR'
Person.TitleList:
    type: 'array'
    displayName: 'List of Titles'
    description: 'List of personal titles used in the system.'
    role: 'ROLE_REGISTRAR'
Address.TerritoryList:
    type: 'array'
    displayName: 'Territory List'
    description: 'List of Territories, States, Provinces or Counties available to addresses in your organisation.'
    role: 'ROLE_REGISTRAR'
Address.BuildingType:
    type: 'array'
    displayName: 'Dwelling Type'
    description: "List of building types used as dwellings found in your organisation's area."
    role: 'ROLE_REGISTRAR'
Phone.TypeList:
    type: 'array'
    displayName: 'Types of Phones'
    description: "List of phone types. The key : key: value) is displayed on your system, and the value is stored in the database."
    role: 'ROLE_REGISTRAR'
Phone.CountryList:
    type: 'array'
    displayName: 'List of Country Codes'
    description: "List of phone country codes."
    role: 'ROLE_REGISTRAR'
Phone.Validation:
    type: 'regex'
    displayName: 'Phone Validation Rule'
    description: "Phone Validation Regular Expression"
    role: 'ROLE_ADMIN'
Phone.Display:
    type: 'twig'
    displayName: 'Phone Display Format'
    description: "A template to convert phone numbers into display version."
    role: 'ROLE_REGISTRAR'
Org.Name:
    type: 'array'
    displayName: 'Organisation Name'
    description: "The name of your organisation"
    role: 'ROLE_REGISTRAR'
Org.Ext.Id:
    type: 'string'
    displayName: 'Organisation External Identifier'
    description: "The identifier given to your organisation by your parent or external education authority."
    role: 'ROLE_REGISTRAR'
Org.Postal.Address.1:
    type: 'text'
    displayName: 'Organisation Postal Address Line 1'
    description: "First line of this organisation's postal address."
    role: 'ROLE_REGISTRAR'
Org.Postal.Address.2:
    type: 'text'
    displayName: 'Organisation Postal Address Line 2'
    description: "Second line of this organisation's postal address."
    role: 'ROLE_REGISTRAR'
Org.Postal.Locality:
    type: 'text'
    displayName: 'Organisation Postal Locality'
    description: "Locality of this organisation's postal address. : Town, Suburb or Locality)"
    role: 'ROLE_REGISTRAR'
Org.Postal.Postcode: 
    type: 'string'
    displayName: 'Organisation Postal Post Code'
    description: "Post Code of this organisation's postal address."
    role: 'ROLE_REGISTRAR'
Org.Postal.Territory: 
    type: 'string'
    displayName: 'Organisation Postal Territory'
    description: "Territory of this organisation's postal address. : State, Province, County)"
    role: 'ROLE_REGISTRAR'
    choice: 'Address.TerritoryList'
Org.Contact.Name: 
    type: 'text'
    displayName: 'Organisation Contact'
    description: "The name of the person to contact in this organisation."
    role: 'ROLE_REGISTRAR'
Org.Contact.Phone: 
    type: 'string'
    displayName: 'Organisation Contact Phone Number'
    description: "The phone number of the person to contact in this organisation."
    role: 'ROLE_REGISTRAR'
    validator: 'phone.validator'
Org.Contact.Facsimile:
    type: 'string'
    displayName: 'Organisation Contact Facsimile Number'
    description: "The facsimile number of the person to contact in this organisation."
    role: 'ROLE_REGISTRAR'
    validator: 'phone.validator'
Org.Contact.Email:
    type: 'string'
    displayName: 'Organisation Contact Email Address'
    description: "The email address of the person to contact in this organisation."
    role: 'ROLE_REGISTRAR'
    validator: 'email.validator'
Org.Physical.Address.1:
    type: 'text'
    displayName: 'Organisation Physical Address Line 1'
    description: "First line of this organisation's physical address."
    role: 'ROLE_REGISTRAR'
Org.Physical.Address.2:
    type: 'text'
    displayName: 'Organisation Physical Address Line 2'
    description: "Second line of this organisation's physical address."
    role: 'ROLE_REGISTRAR'
Org.Physical.Locality:
    type: 'text'
    displayName: 'Organisation Physical Locality'
    description: "Locality of this organisation's physical address. : Town, Suburb or Locality)"
    role: 'ROLE_REGISTRAR'
Org.Physical.Postcode:
    type: 'string'
    displayName: 'Organisation Physical Post Code'
    description: "Post Code of this organisation's physical address."
    role: 'ROLE_REGISTRAR'
Org.Physical.Territory:
    type: 'string'
    displayName: 'Organisation Physical Territory'
    description: "Territory of this organisation's physical address. : State, Province, County)"
    role: 'ROLE_REGISTRAR'
    choice: 'Address.TerritoryList'
CountryType:
    type: 'text'
    displayName: 'Country Type Form Handler'
    description: "Determines how the country details are obtained and stored in the database."
    role: 'ROLE_SYSTEM_ADMIN'
firstDayofWeek:
    type: 'string'
    displayName: 'First Day of Week'
    description: 'The first day of the week for display purposes.  Monday or Sunday, defaults to Monday.'
    role: 'ROLE_ADMIN'
schoolWeek:
    type: 'array'
    displayName: 'Days in the School Week'
    description: 'Defines the list of days that school would normally be open.'
    role: 'ROLE_ADMIN'
Org.Logo:
    type: 'image'
    displayName: 'Organisation Logo'
    description: 'The organisation Logo'
    role: 'ROLE_ADMIN'
    validator: 'validator.logo'
Org.Logo.Transparent:
    type: 'image'
    displayName: 'Organisation Transparent Logo'
    description: 'The organisation Logo in a transparent form.  Recommended to be 80% opacity. Only PNG or GIF image formats support transparency.'
    role: 'ROLE_ADMIN'
    validator: 'validator.logo'
Background.Image:
    type: 'image'
    displayName: 'Background Image'
    description: 'Change the background displayed for the site.  The image needs to be a minimum of 1200px width.  You can load an image of 1M size, but the smaller the size the better.'
    role: 'ROLE_ADMIN'
    validator: 'validator.background.image'
SchoolDay.Open:
    type: 'time'
    displayName: 'School Day Open Time'
    description: 'At what time are students allowed on campus?'
    role: 'ROLE_ADMIN'
SchoolDay.Begin:
    type: 'time'
    displayName: 'School Day Instruction Start Time'
    description: 'The time that teaching starts. Students would normally be considered late after this time.'
    role: 'ROLE_ADMIN'
    validator: null
SchoolDay.Finish:
    type: 'time'
    displayName: 'School Day Instruction Finish Time'
    description: 'The time students are released for the day.'
    role: 'ROLE_ADMIN'
    validator: null
SchoolDay.Close:
    type: 'time'
    displayName: 'School Day Close Time'
    description: 'The time the doors of the campus normally close, all after school and school activities finished.'
    role: 'ROLE_ADMIN'
    validator: null
Campus.Space.Type:
    type: 'array'
    displayName: 'Type of Space'
    description: 'Spaces are spaces used with the Campus, such as classrooms, purpose built rooms and Storage Rooms.'
    role: 'ROLE_ADMIN'
    validator: null
    value: |
        Classroom: Classroom
    choice: Classroom
Staff.Categories:
    type: 'array'
    displayName: 'Staff Categories'
    description: 'List of the staff Categories.'
    role: 'ROLE_ADMIN'
    validator: null
Country.Code:
    type: 'string'
    displayName: 'Phone Country Code'
    description: 'Default phone country code.'
    role: 'ROLE_REGISTRAR'
    validator: null
Person.Import:
    type: 'array'
    displayName: 'Person Import Defaults'
    description: 'Default values added to imported records.'
    role: 'ROLE_REGISTRAR'
    validator: null
Phone.Format:
    type: 'twig'
    displayName: 'Phone Full Display Format'
    description: "A template to convert phone numbers into full display version."
    role: 'ROLE_REGISTRAR'
Student.Status.List:
    type: 'array'
    displayName: 'Student Status List'
    description: "List of the valid student status: es)"
    role: 'ROLE_ADMIN'
Student.CareGiver.Relationship.List:
    type: 'array'
    displayName: 'List of Student - Care Giver Relationship'
    description: 'List of Student - Care Giver Relationship'
    role: 'ROLE_ADMIN'
Ethnicity.List:
    type: 'array'
    displayName: 'List of Ethnicities'
    description: 'List of Ethnicities.  Uses the Australian Standard to create this list'
    role: 'ROLE_ADMIN'
Religion.List:
    type: 'array'
    displayName: 'List of Religions'
    description: 'List of Religions.  Uses the Australian Standard to create this list'
    role: 'ROLE_ADMIN'
Residency.List:
    type: 'array'
    displayName: 'List of Residency Status'
    description: 'List of Residency Status.  Usually defined by the government.'
    role: 'ROLE_ADMIN'
Settings.Default.Overwrite:
    type: 'file'
    displayName: 'Setting File Overwrite'
    description: 'A file name that allows the update process to change the default settings to match the users pre-set details.'
    role: 'ROLE_SYSTEM_ADMIN'
idleTimeout:
    type: 'integer'
    displayName: 'Idle Timeout (Minutes)'
    description: "Number of minutes that you can leave the screen idle before the system logs out automatically."
    role: 'ROLE_REGISTRAR'
    value: 15
