house.list:
    type: 'array'
    displayName: 'House List'
    description: "House list used in your school."
    role: 'ROLE_REGISTRAR'
student.groups:
    type: array
    displayName: Student Groups
    description: Usually the year groups that attend this school.
    role: ROLE_REGISTRAR
    value:
        Year 7: Y7
        Year 8: Y8
student.enrolment.status:
    type: array
    displayName: Student Enrolment Status
    description: Reflects the status of student enrolment.
    role: ROLE_ADMIN
    value:
        Future: Future
        Current: Current
        Past: Past
        Archived: Archived
department.type.list:
    type: array
    displayName: Department Type List
    role: ROLE_REGISTRAR
    description: Types of departments within the institute.
    value:
        Learning Area: Learning Area
        Administration: Administration
department.staff.type.list:
    type: array
    displayName: Department Staff Type List
    role: ROLE_REGISTRAR
    description: Types of staff within departments within the institute.
    value:
        Learning:
            Coordinator: Coordinator
            Assistant Coordinator: Assistant Coordinator
            Teacher (Curriculum): Teacher (Curriculum)
            Teacher: Teacher
            Other: Other
        Administation:
            Director: Director
            Manager: Manager
            Administrator: Administrator
            Other: Other
date.format.long:
    type: string
    value: 'D, jS M/Y'
    displayName: Date Format (Long)
    description: Display the date in reports in this format. Formats are found at http://php.net/manual/en/function.date.php
    role: ROLE_REGISTRAR
date.format.short:
      type: string
      value: 'j/m/Y'
      displayName: Date Format (Short)
      description: Display the date in reports in this format. Formats are found at http://php.net/manual/en/function.date.php
      role: ROLE_REGISTRAR