Version.System:
    type: 'string'
    value: '0.0.00'
    displayName: 'System Version'
    description: 'The version of Busybee currently configured on your system.'
    role: 'ROLE_SYSTEM_ADMIN'
Version.Database:
    type: 'string'
    value: '0.0.00'
    displayName: 'Database Version'
    description: 'The version of Busybee Database currently configured on your system.'
    role: 'ROLE_SYSTEM_ADMIN'
