Busybee\StudentBundle\Entity\Activity:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name, year]
            errorPath: name
            message: activity.nameyear.unique
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [nameShort, year]
            errorPath: nameShort
            message: activity.nameshortyear.unique
        - Callback: studentNumbersValidate
    properties:
        name:
            - NotBlank: ~
        nameShort:
            - NotBlank: ~
        year:
            - Valid: ~
            - NotBlank: ~
