Busybee\StudentBundle\Entity\Activity:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name, year]
            errorPath: name
            message: activity.unique.name
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [nameShort, year]
            errorPath: nameShort
            message: activity.unique.nameShort
    properties:
        name:
            - NotBlank: ~
        nameShort:
            - NotBlank: ~
        year:
            - Valid: ~
            - NotBlank: ~
