Busybee\StudentBundle\Entity\Enrolment:
    properties:
        year:
            - NotBlank: ~
            - Valid: ~
        status:
            - NotBlank: ~
        grade:
            - NotBlank: ~
            - Busybee\FormBundle\Validator\SettingChoice:
                name: student.groups