Busybee\StudentBundle\Entity\Student:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: person
    properties:
        startAtSchool:
            - Date: ~
        startAtThisSchool:
            - Date: ~
        lastAtThisSchool:
            - Date: ~
        status:
            - Busybee\FormBundle\Validator\SettingChoice:
                name: 'Student.Status.List'
        citizenship1PassportScan:
            - \Busybee\StudentBundle\Validator\PassportImage: ~
        person:
            - NotBlank: ~
        house:
            - Busybee\FormBundle\Validator\SettingChoice:
                name: 'house.list'
        enrolments:
            - Busybee\StudentBundle\Validator\Enrolments: ~