student_manage:
    path:     /manage/
    defaults: { _controller: BusybeeStudentBundle:Student:list }
person_toggle_student:
    path:     /person/{id}/toggle/
    defaults: { _controller: BusybeeStudentBundle:Student:toggle }
student_passport_remove:
    path:     /student/{id}/passport_remove/
    defaults: { _controller: BusybeeStudentBundle:Student:removePassportScan }
student_id_remove:
    path:     /student/{id}/id_remove/
    defaults: { _controller: BusybeeStudentBundle:Student:removeIDScan }
student_add_to_calendar_group:
    path:     /calendar/group/{id}/manage/
    defaults: { _controller: BusybeeStudentBundle:Student:addToCalendarGroup }
remove_student_from_calendar_group:
    path:     /calendar/group/{group}/{student}/remove/
    defaults: { _controller: BusybeeStudentBundle:Student:removeStudentFromCalendarGroup }
add_student_to_calendar_group:
    path:     /calendar/group/{group}/{student}/{status}/add/
    defaults: { _controller: BusybeeStudentBundle:Student:addStudentToCalendarGroup }
