student_manage:
    path:     /manage/
    defaults: { _controller: BusybeeStudentBundle:Student:list }
person_toggle_student:
    path:     /person/{id}/toggle/
    defaults: { _controller: BusybeeStudentBundle:Student:toggle }
