parameters:
    studentPagination:
        alias: s
        sortBy:
            Family Name:
                p.surname: ASC
                p.firstName: ASC
            Given Name:
                p.firstName: ASC
                p.surname: ASC
            Details:
                g.sequence: ASC
                p.surname: ASC
                p.firstName: ASC
        limit: '25'
        join:
            s.person:
                alias: p
                type: leftJoin
            s.grades:
                alias: i
                type: leftJoin
            i.grade:
                alias: g
                type: leftJoin
            p.user:
                alias: u
                type: leftJoin
            p.staff:
                alias: sta
                type: leftJoin
        searchList:
            - p.surname
            - p.firstName
            - p.email
            - g.grade
            - g.name
        select:
            - p.surname
            - p.firstName
            - g.name as details
            - p.id
            - s.id as stu_id
            - sta.id as staff_id
            - u.id as user_id
        choices:
            all:
                route: person_manage
                prompt: pagination.person.all
            student:
                route: student_manage
                prompt: pagination.person.student
            staff:
                route: staff_manage
                prompt: pagination.person.staff
            contact:
                route: contact_manage
                prompt: pagination.person.contact
    Student:
        version: 0.0.01
        settings:
            resources:
                - 'BusybeeStudentBundle/Resources/config/Settings/Settings_0_0_01.yml'
services:
    student.repository:
        class: Busybee\People\StudentBundle\Repository\StudentRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeStudentBundle:Student"
    form.person.student.type:
        class: Busybee\People\StudentBundle\Form\StudentType
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@setting.manager'
        tags:
            - { name: form.type }
    passport.image.validator:
        class: Busybee\People\StudentBundle\Validator\Constraints\PassportImageValidator
        tags:
            - { name: validator.constraint_validator, alias: passport_image_validator }
    student.extension:
        class: Busybee\People\StudentBundle\Model\StudentExtension
        arguments:
            - '@student.repository'
            - '@translator'
        tags:
            - { name: twig.extension }
    form.person.student.grade.type:
        class: Busybee\People\StudentBundle\Form\StudentGradeType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
    student.grades.validator:
        class: Busybee\People\StudentBundle\Validator\Constraints\GradesValidator
        tags:
            - { name: validator.constraint_validator, alias: student_grades_validator }
    student.pagination:
        class: Busybee\People\StudentBundle\Model\StudentPagination
        arguments:
            - '%studentPagination%'
            - '@student.repository'
            - '@my_service_container'
    student.student.voter:
        class: Busybee\People\StudentBundle\Security\StudentVoter
        arguments:
            - '@security.access.decision_manager'
            - '@person.manager'
        tags:
            - { name: security.voter, priority: 250 }
        public: false
    student.parent.voter:
        class: Busybee\People\StudentBundle\Security\ParentVoter
        arguments:
            - '@security.access.decision_manager'
            - '@person.manager'
        tags:
            - { name: security.voter, priority: 250 }
        public: false
    student.manager:
        class: Busybee\People\StudentBundle\Model\StudentManager
        arguments:
            - '@setting.manager'
            - '@doctrine.orm.entity_manager'
            - '@validator'
            - '@current.year.currentYear'
