parameters:
    studentPagination:
        alias: s
        sortBy:
            Family Name:
                p.surname: ASC
                p.firstName: ASC
            Given Name:
                p.firstName: ASC
                p.surname: ASC
            Details:
                g.sequence: ASC
                p.surname: ASC
                p.firstName: ASC
        limit: '25'
        join:
            s.person:
                alias: p
                type: leftJoin
            s.grades:
                alias: i
                type: leftJoin
            i.grade:
                alias: g
                type: leftJoin
            p.user:
                alias: u
                type: leftJoin
            p.staff:
                alias: sta
                type: leftJoin
        searchList:
            - p.surname
            - p.firstName
            - p.email
            - g.grade
            - g.name
        select:
            - p.surname
            - p.firstName
            - g.name as details
            - p.id
            - s.id as stu_id
            - sta.id as staff_id
            - u.id as user_id
        choices:
            all:
                route: person_manage
                prompt: pagination.person.all
            student:
                route: student_manage
                prompt: pagination.person.student
            staff:
                route: staff_manage
                prompt: pagination.person.staff
            contact:
                route: contact_manage
                prompt: pagination.person.contact
    StudentBundle:
        version: 0.0.01
        settings:
            resources:
                - 'BusybeeStudentBundle/Resources/config/Settings/Settings_0_0_01.yml'
services:
    busybee_people_student.repository.student_repository:
        class: Busybee\People\StudentBundle\Repository\StudentRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeStudentBundle:Student"
    busybee_people_student.validator.constraints.passport_image_validator:
        class: Busybee\People\StudentBundle\Validator\Constraints\PassportImageValidator
        tags:
            - { name: validator.constraint_validator, alias: passport_image_validator }
    student.extension:
        class: Busybee\People\StudentBundle\Model\StudentExtension
        arguments:
            - '@busybee_people_student.repository.student_repository'
            - '@translator'
        tags:
            - { name: twig.extension }
    busybee_people_student.form.student_grade_type:
        class: Busybee\People\StudentBundle\Form\StudentGradeType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
    busybee_people_student.validator.constraints.grades_validator:
        class: Busybee\People\StudentBundle\Validator\Constraints\GradesValidator
        tags:
            - { name: validator.constraint_validator, alias: student_grades_validator }
    busybee_people_student.model.student_pagination:
        class: Busybee\People\StudentBundle\Model\StudentPagination
        arguments:
            - '%studentPagination%'
            - '@busybee_people_student.repository.student_repository'
            - '@busybee_core_system.model.my_container'
    busybee_people_student.security.student_voter:
        class: Busybee\People\StudentBundle\Security\StudentVoter
        arguments:
            - '@security.access.decision_manager'
            - '@busybee_people_person.model.person_manager'
        tags:
            - { name: security.voter, priority: 250 }
        public: false
    busybee_people_student.security.parent_voter:
        class: Busybee\People\StudentBundle\Security\ParentVoter
        arguments:
            - '@security.access.decision_manager'
            - '@busybee_people_person.model.person_manager'
        tags:
            - { name: security.voter, priority: 250 }
        public: false
    busybee_people_student.model.student_manager:
        class: Busybee\People\StudentBundle\Model\StudentManager
        arguments:
            - '@busybee_core_system.setting.setting_manager'
            - '@doctrine.orm.entity_manager'
            - '@validator'
            - '@busybee_core_calendar.model.get_current_year'
