parameters:
    studentPagination:
        alias: s
        sortBy:
            Family Name:
                s.surname: ASC
                s.firstName: ASC
            Given Name:
                s.firstName: ASC
                s.surname: ASC
        limit: '25'
        join:
            s.user:
                alias: u
                type: leftJoin
            s.phone:
                type: leftJoin
                alias: p
        searchList:
            - s.surname
            - s.firstName
            - s.email
        select:
            - s.surname
            - s.firstName
            - s.id
            - u.id as user_id
        choices:
            all:
                route: person_manage
                prompt: pagination.person.all
            student:
                route: student_manage
                prompt: pagination.person.student
            staff:
                route: staff_manage
                prompt: pagination.person.staff
            contact:
                route: contact_manage
                prompt: pagination.person.contact
    StudentBundle:
        version: 0.0.01
        settings:
            resources:
                - 'BusybeeStudentBundle/Resources/config/Settings/Settings_0_0_01.yml'
services:
    busybee_people_student.repository.student_repository:
        class: Busybee\People\StudentBundle\Repository\StudentRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeStudentBundle:Student"
    busybee_people_student.validator.constraints.passport_image_validator:
        class: Busybee\People\StudentBundle\Validator\Constraints\PassportImageValidator
        tags:
            - { name: validator.constraint_validator, alias: passport_image_validator }
    busybee_people_student.model.student_extension:
        class: Busybee\People\StudentBundle\Model\StudentExtension
        arguments:
            - '@busybee_people_student.repository.student_repository'
            - '@translator'
        tags:
            - { name: twig.extension }
    busybee_people_student.model.student_pagination:
        class: Busybee\People\StudentBundle\Model\StudentPagination
        arguments:
            - '%studentPagination%'
            - '@busybee_people_student.repository.student_repository'
            - '@busybee_core_system.model.my_container'
            - '@busybee_people_person.model.person_manager'
    busybee_people_student.security.student_voter:
        class: Busybee\People\StudentBundle\Security\StudentVoter
        arguments:
            - '@security.access.decision_manager'
            - '@busybee_people_person.model.person_manager'
        tags:
            - { name: security.voter, priority: 250 }
        public: false
    busybee_people_student.security.parent_voter:
        class: Busybee\People\StudentBundle\Security\ParentVoter
        arguments:
            - '@security.access.decision_manager'
            - '@busybee_people_person.model.person_manager'
        tags:
            - { name: security.voter, priority: 250 }
        public: false
    busybee_people_student.model.student_manager:
        class: Busybee\People\StudentBundle\Model\StudentManager
        arguments:
            - '@busybee_core_system.setting.setting_manager'
            - '@doctrine.orm.entity_manager'
            - '@validator'
            - '@busybee_core_calendar.model.get_current_year'
