# src\General\ValidationBundle\Resources\config\doctrine\Validator.orm.yml
General\ValidationBundle\Entity\Messages:
    type: entity
    table: validator_messages
    repositoryClass: General\ValidationBundle\Entity\MessagesRepository
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [name, group, type]
            errorPath: ConstraintType
            message: 'validator_message.name.unique'
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 30
            column: constraint_name
        group:
            type: string
            length: 30
            column: constraint_group
        type:
            type: string
            length: 30
            column: constraint_type
        message:
            type: text
            nullable: false 
    manyToOne:
        validator:
            targetEntity: General\ValidationBundle\Entity\Validator
            inversedBy: messages