# src\General\ValidationBundle\Resources\config\doctrine\Validator.orm.yml
General\ValidationBundle\Entity\Validator:
    type: entity
    table: validator
    repositoryClass: General\ValidationBundle\Entity\ValidatorRepository
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [ConstraintName, ConstraintGroup]
            errorPath: ConstraintName
            message: 'validator.name.unique'
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        constraintName:
            type: string
            length: 30
            column: constraint_name
        constraintGroup:
            type: string
            length: 30
            column: constraint_group
        notblank:
            type: boolean
            column: not_blank 
        unique:
            type: boolean
            column: _unique
        match:
            type: text
            column: _match
            nullable: true 
        replace:
            type: text
            column: _replace
            nullable: true 
        format:
            type: text
            column: _format
            nullable: true 
        minlength:
            type: integer
            column: _minimum
            nullable: true 
        length: 
            type: integer
            column: _length
            nullable: true 
        enumeration:
            type: json_array
            nullable: true 
    oneToMany:     
        messages:
            targetEntity: General\ValidationBundle\Entity\Messages    
            mappedBy: validator 

