# Calendar
parameters:
    calendar:
        year:
            label: calendar.tab.year
            include: 'BusybeeCalendarBundle:Calendar:year.html.twig'
            message: yearMessage
        terms:
            label: calendar.tab.terms
            include: 'BusybeeCalendarBundle:Term:terms.html.twig'
            message: termMessage
        specialDays:
            label: calendar.tab.specialDays
            include: 'BusybeeCalendarBundle:SpecialDays:specialDays.html.twig'
            message: specialDayMessage
        grades:
            label: calendar.tab.grades
            include: 'BusybeeCalendarBundle:Grade:edit.html.twig'
            message: gradeMessage