Busybee\CurriculumBundle\Entity\Course:
    type: entity
    table: course
    repositoryClass: Busybee\CurriculumBundle\Repository\CourseRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
            unique: true
        version:
            type: string
            length: '10'
            nullable: true
        lastModified:
            type: datetime
        createdOn:
            type: datetime
        targetYear:
            type: string
            length: '255'
    manyToOne:
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                createdBy:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modifiedBy:
                    referencedColumnName: id
