Busybee\CurriculumBundle\Entity\Course:
    type: entity
    table: course
    repositoryClass: Busybee\CurriculumBundle\Repository\CourseRepository
    uniqueConstraints:
        name_version:
            columns: [ name, version ]
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
        version:
            type: string
            length: '10'
            nullable: true
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    manyToOne:
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                createdBy:
                    referencedColumnName: id
                    
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modifiedBy:
                    referencedColumnName: id
