Busybee\TimeTableBundle\Entity\ActivityGroups:
    type: entity
    table: activity_groups
    repositoryClass: Busybee\TimeTableBundle\Repository\ActivityGroupsRepository
    uniqueConstraints:
        name_year:
            columns:
                - name
                - year
        short_year:
            columns:
                - nameShort
                - year
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
        nameShort:
            type: string
            length: '5'
        participants:
            type: integer
            length: 4
        includeAll:
            type: boolean
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    manyToMany:
        activities:
            targetEntity: Busybee\StudentBundle\Entity\Activity
            joinTable:
                name: activity_group_activity
                joinColumns:
                    group_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    activity_id:
                        referencedColumnName: id
    manyToOne:
        year:
            targetEntity: Busybee\InstituteBundle\Entity\Year
            nullable: false
            joinColumns:
                year:
                    referencedColumnName: id
        course:
            targetEntity: Busybee\CurriculumBundle\Entity\Course
            nullable: true
            orderBy: { 'name': 'ASC' }
            joinColumns:
                course:
                    referencedColumnName: id
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                createdBy:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modifiedBy:
                    referencedColumnName: id
