Busybee\TimeTableBundle\Entity\Column:
    type: entity
    table: tt_column
    repositoryClass: Busybee\TimeTableBundle\Repository\ColumnRepository
    uniqueConstraints:
        name_tt:
            columns:
                - name
                - tt_id
        nameshort_tt:
            columns:
                - nameShort
                - tt_id
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
        nameShort:
            type: string
            length: '8'
        mappingInfo:
            length: '8'
        start:
            type: time
        end:
            type: time
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    oneToMany:
        periods:
            targetEntity: Busybee\TimeTableBundle\Entity\Period
            mappedBy: column
            cascade: [ 'all' ]
    manyToOne:
        timetable:
            targetEntity: Busybee\TimeTableBundle\Entity\TimeTable
            inversedBy: columns
            joinColumn:
                name: tt_id
                referencedColumnName: id
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                createdBy:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modifiedBy:
                    referencedColumnName: id
