Busybee\TimeTableBundle\Entity\LearningGroups:
    type: entity
    table: learning_groups
    repositoryClass: Busybee\TimeTableBundle\Repository\LearningGroupsRepository
    uniqueConstraints:
        name_year:
            columns:
                - name
                - year
        short_year:
            columns:
                - nameShort
                - year
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
        nameShort:
            type: string
            length: '5'
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    manyToMany:
        activities:
            targetEntity: Busybee\StudentBundle\Entity\Activity
            joinTable:
                name: learning_group_activity
                joinColumns:
                    lg_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    activity_id:
                        referencedColumnName: id
    manyToOne:
        year:
            targetEntity: Busybee\InstituteBundle\Entity\Year
            joinColumns:
                year:
                    referencedColumnName: id
        course:
            targetEntity: Busybee\CurriculumBundle\Entity\Course
            joinColumns:
                course:
                    referencedColumnName: id
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                createdBy:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modifiedBy:
                    referencedColumnName: id
