Busybee\TimeTableBundle\Entity\LearningGroups:
    type: entity
    table: learning_groups
    repositoryClass: Busybee\TimeTableBundle\Repository\LearningGroupsRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
        nameShort:
            type: string
            length: '5'
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    manyToMany:
        activities:
            targetEntity: Busybee\StudentBundle\Entity\Activity
            joinTable:
                name: learning_group_activity
                joinColumns:
                    lg_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    activity_id:
                        referencedColumnName: id
    manyToOne:
        line:
            targetEntity: Busybee\TimeTableBundle\Entity\Line
            inversedBy: learningGroups
            joinColumn:
                name: line
                referencedColumnName: id
        course:
            targetEntity: Busybee\CurriculumBundle\Entity\Course
            joinColumns:
                course:
                    referencedColumnName: id
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                createdBy:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modifiedBy:
                    referencedColumnName: id
