Busybee\TimeTableBundle\Entity\Line:
    type: entity
    table: timetable_line
    repositoryClass: Busybee\TimeTableBundle\Repository\LineRepository
    uniqueConstraints:
        seq_tt:
            columns:
                - sequence
                - tt_id
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        sequence:
            type: integer
            length: '3'
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    manyToMany:
        learningGroups:
            targetEntity: Busybee\TimeTableBundle\Entity\LearningGroups
            joinTable:
                name: learninggroups_lines
                joinColumns:
                    learninggroup_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    line_id:
                        referencedColumnName: id
    manyToOne:
        timetable:
            targetEntity: Busybee\TimeTableBundle\Entity\TimeTable
            inversedBy: lines
            joinColumn:
                name: tt_id
                referencedColumnName: id
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                createdBy:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modifiedBy:
                    referencedColumnName: id
