Busybee\TimeTableBundle\Entity\Period:
    type: entity
    table: tt_period
    repositoryClass: Busybee\TimeTableBundle\Repository\PeriodRepository
    uniqueConstraints:
        name_column:
            columns:
                - name
                - column_id
        nameshort_column:
            columns:
                - nameShort
                - column_id
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            length: '24'
        nameShort:
            length: '3'
        start:
            type: time
        end:
            type: time
        break:
            type: boolean
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    oneToMany:
        activities:
            targetEntity: Busybee\TimeTableBundle\Entity\PeriodActivity
            mappedBy: period
            cascade: [ 'all' ]
    manyToOne:
        column:
            targetEntity: Busybee\TimeTableBundle\Entity\Column
            inversedBy: periods
            joinColumn:
                name: column_id
                referencedColumnName: id
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                createdBy:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modifiedBy:
                    referencedColumnName: id
