Busybee\TimeTableBundle\Entity\PeriodActivity:
    type: entity
    table: tt_period_activity
    repositoryClass: Busybee\TimeTableBundle\Repository\PeriodActivityRepository
    uniqueConstraints:
        period_activity:
            columns:
                - period_id
                - activity_id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    manyToOne:
        space:
            targetEntity: Busybee\InstituteBundle\Entity\Space
            joinColumns:
                space_id:
                    referencedColumnName: id
        tutor1:
            targetEntity: Busybee\People\StaffBundle\Entity\Staff
            joinColumns:
                tutor_1:
                    referencedColumnName: id
        tutor2:
            targetEntity: Busybee\People\StaffBundle\Entity\Staff
            joinColumns:
                tutor_2:
                    referencedColumnName: id
        tutor3:
            targetEntity: Busybee\People\StaffBundle\Entity\Staff
            joinColumns:
                tutor_3:
                    referencedColumnName: id
        activity:
            targetEntity: Busybee\ActivityBundle\Entity\Activity
            inversedBy: periods
            joinColumns:
                activity_id:
                    referencedColumnName: id
        period:
            targetEntity: Busybee\TimeTableBundle\Entity\Period
            inversedBy: activities
            joinColumns:
                period_id:
                    referencedColumnName: id
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
