Busybee\PersonBundle\Entity\Address:
    type: entity
    table: address
    repositoryClass: Busybee\PersonBundle\Repository\AddressRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        line1:
            type: string
            length: '50'
        line2:
            type: string
            length: '50'
            nullable: true
        locality:
            type: string
            length: '50'
        territory:
            type: string
            length: '50'
            nullable: true
        postCode:
            type: string
            length: '12'
            nullable: true
        country:
            type: string
            length: '50'
        lastModified:
            type: datetime
            nullable: true
        createdOn:
            type: datetime
            nullable: true
    manyToOne:
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
                    nullable: true
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
                    nullable: true
