Busybee\PersonBundle\Entity\Address:
    type: entity
    table: address
    repositoryClass: Busybee\PersonBundle\Repository\AddressRepository
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields:
                - buildingType
                - buildingNumber
                - streetNumber
                - line1
                - line2
                - locality
            errorPath: line1
            message: address.error.unique 
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        buildingType:
            type: string 
            length: '10'
            nullable: true
        buildingNumber:
            type: string
            length: '10'
            nullable: true
        streetNumber:
            type: string
            length: '10'
            nullable: true
        line1:
            type: string
            length: '50'
        line2:
            type: string
            length: '50'
            nullable: true
        locality: 
            type: integer
        lastModified:
            type: datetime
            nullable: true
        createdOn:
            type: datetime
            nullable: true
    manyToOne:
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
                    nullable: true
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
                    nullable: true
