Busybee\PersonBundle\Entity\CareGiver:
    type: entity
    table: person_care_giver
    repositoryClass: Busybee\PersonBundle\Repository\CareGiverRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    manyToOne:
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
        person:
            targetEntity: Busybee\PersonBundle\Entity\Person
            joinColumns:
                person_id:
                    referencedColumn: id
