Busybee\PersonBundle\Entity\Image:
    type: entity
    table: image_store
    repositoryClass: Busybee\PersonBundle\Repository\ImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: '25'
        image:
            type: blob    
        size:
            type: string
            length: '25'
        name:
            type: string
            length: '100'
        lastModified:
            type: datetime
            nullable: true 
        createdOn:
            type: datetime
            nullable: true 
    manyToOne:
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
                    nullable: true
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
                    nullable: true
