Busybee\PersonBundle\Entity\Locality:
    type: entity
    table: locality
    repositoryClass: Busybee\PersonBundle\Repository\LocalityRepository
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: 
                - locality
                - territory
                - postCode
                - country
            errorPath: locality
            message: 'error.unique.locality'
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        locality:
            type: string
            length: '50'
        territory:
            type: string
            length: '50'
            nullable: true
        postCode:
            type: string
            length: '12'
            nullable: true
        country:
            type: string
            length: '6'
        lastModified:
            type: datetime
            nullable: true
        createdOn:
            type: datetime
            nullable: true
    manyToOne:
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
                    nullable: true
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
                    nullable: true
