Busybee\PersonBundle\Entity\Person:
    type: entity
    table: person
    repositoryClass: Busybee\PersonBundle\Repository\PersonRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '5'
            nullable: true
        surname:
            type: string
            length: '50'
        firstName:
            type: string
            length: '50'
        preferredName:
            type: string
            length: '50'
        officialName:
            type: string
            length: '150'
        gender:
            type: string
            length: '1'
        dob:
            type: date
            nullable: true
        email:
            type: string
            length: '65'
            nullable: true
        email2:
            type: string
            length: '65'
            nullable: true
        website:
            type: string
            length: '150'
            nullable: true
        address1:
            type: integer
            nullable: true
        address2:
            type: integer
            nullable: true
        photo:
            type: string
            length: '150'
            nullable: true
        lastModified:
            type: datetime
            nullable: true 
        createdOn:
            type: datetime
            nullable: true 
    properties:
        email:
            - Email: ~
        email2:
            - Email: ~
        surname:
            - NotBlank: ~
        website:
            - Url: ~
        gender:
            - Choice: 
                choices: { callback: getGenders }
        photo:
            - Image:
                maxSize: 200k
                minWidth: '350'
                maxWidth: '450'
                minHeight: '400'
                maxHeight: '500'
                allowPortrait: false
                minRatio: '0.8'
                maxRatio: '0.9'
    manyToOne:
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
                    nullable: true
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
                    nullable: true
