Busybee\PersonBundle\Entity\Person:
    type: entity
    table: person
    repositoryClass: Busybee\PersonBundle\Repository\PersonRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '5'
            nullable: true
        surname:
            type: string
            length: '50'
        firstName:
            type: string
            length: '50'
        preferredName:
            type: string
            length: '50'
        officialName:
            type: string
            length: '150'
        gender:
            type: string
            length: '1'
        dob:
            type: date
            nullable: true
        email:
            type: string
            length: '65'
            nullable: true
        email2:
            type: string
            length: '65'
            nullable: true
        website:
            type: string
            length: '200'
            nullable: true
        photo:
            type: string
            length: '150'
            nullable: true
        lastModified:
            type: datetime
            nullable: true 
        createdOn:
            type: datetime
            nullable: true 
    manyToOne:
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
        address1:
            targetEntity: Busybee\PersonBundle\Entity\Address
            nullable: true
            joinColumns:
                address1:
                    referencedColumnName: id
        address2:
            targetEntity: Busybee\PersonBundle\Entity\Address
            nullable: true
            joinColumns:
                address2:
                    referencedColumnName: id
    manyToMany:
        phone:
            targetEntity: Busybee\PersonBundle\Entity\Phone
            cascade: [ 'persist' ]
            joinTable:
                name: person_phone
                joinColumns:
                    person_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    phone_id:
                        referencedColumnName: id
    oneToOne:
        staff:
            targetEntity: Busybee\PersonBundle\Entity\Staff
            cascade: [persist, remove]
            mappedBy: person
            nullable: true
        caregiver:
            targetEntity: Busybee\PersonBundle\Entity\CareGiver
            cascade: [persist, remove]
            mappedBy: person
            nullable: true
        student:
            targetEntity: Busybee\PersonBundle\Entity\Student
            cascade: [persist, remove]
            mappedBy: person
            nullable: true
        user:
            targetEntity: Busybee\SecurityBundle\Entity\User
            cascade: [persist]
            mappedBy: person
            nullable: true
