Busybee\PersonBundle\Entity\PersonPreference:
    type: entity
    table: person_preference
    repositoryClass: Busybee\PersonBundle\Repository\PersonPreferenceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        lastModified:
            type: datetime
            nullable: true 
        createdOn:
            type: datetime
            nullable: true
    oneToOne:
        person:
            targetEntity: Busybee\PersonBundle\Entity\Person
            inversedBy: preference
            joinColumn:
                name: person
                referencedColumnName: id
    manyToOne:
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
