Busybee\PersonBundle\Entity\Staff:
    type: entity
    table: person_staff
    repositoryClass: Busybee\PersonBundle\Repository\StaffRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: '20'
        jobTitle:
            type: string    
            length: '100'
        lastModified:
            type: datetime
            nullable: true 
        createdOn:
            type: datetime
            nullable: true 
    manyToOne:
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
                    nullable: true
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
                    nullable: true
    oneToOne:
        person:
            targetEntity: Busybee\PersonBundle\Entity\Person
            joinColumn:
                name: person_id
                referencedColumn: id
                
            
