Busybee\PersonBundle\Entity\Student:
    type: entity
    table: person_student
    repositoryClass: Busybee\PersonBundle\Repository\StudentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        startAtSchool:
            type: date
        startAtThisSchool:
            type: date
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    oneToOne:
        person:
            targetEntity: Busybee\PersonBundle\Entity\Person
            inversedBy: student
    manyToOne:
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
