person_manage:
    path:     /manage/
    defaults: { _controller: BusybeePersonBundle:Person:index }
person_edit:
    path:     /{id}/edit/
    defaults: { _controller: BusybeePersonBundle:Person:edit, id: 'Add' }
people_import:
    path:     /import/
    defaults: { _controller: BusybeePersonBundle:People:import }
person_toggle_user:
    path:     /user/{id}/toggle/
    defaults: { _controller: BusybeePersonBundle:User:toggle }
person_photo_remove:
    path:     /photo/{id}/remove
    defaults: { _controller: BusybeePersonBundle:Person:removePhoto }
