#PersonBundle
parameters:
    personPagination:
        alias: p
        sortBy:
            Family Name:
                p.surname: ASC
                p.firstName: ASC
            Given Name:
                p.firstName: ASC
                p.surname: ASC
            Details:
                p.email: ASC
                h.phoneNumber: ASC
                p.surname: ASC
                p.firstName: ASC
        limit: '25'
        searchList:
            - p.surname
            - p.firstName
            - p.email
        select:
            - p.id
            - p.title as details
            - p.surname
            - p.firstName
            - u.id as user_id
        join:
            p.phone:
                type: leftJoin
                alias: h
            p.user:
                type: leftJoin
                alias: u
        choices:
            all:
                route: person_manage
                prompt: pagination.person.all
            student:
                route: student_manage
                prompt: pagination.person.student
            staff:
                route: staff_manage
                prompt: pagination.person.staff
            contact:
                route: contact_manage
                prompt: pagination.person.contact
    PersonBundle:
        version: 0.0.01
        settings:
            resources:
                - 'BusybeePersonBundle/Resources/config/Settings/Settings_0_0_01.yml'
    PersonTabs:
        person:
            label: person.tab.person
            include: 'BusybeePersonBundle:Person:person.html.twig'
            message: personMessage
#        contact:
#            label: person.tab.contact
#            include: 'BusybeePersonBundle:Person:contact.html.twig'
#        staff:
#            label: person.tab.staff
#            include: BusybeeStaffBundle:Person:staff.html.twig
#            message: staffMessage
#            translation: BusybeeStaffBundle
#        immigration:
#            label: person.tab.immigration
#            include: BusybeeStudentBundle:Person:immigration.html.twig
#            message: immigrationMessage
#            translation: BusybeeStudentBundle
#        student:
#            label: person.tab.student
#            include: BusybeeStudentBundle:Person:student.html.twig
#            message: studentMessage
#            translation: BusybeeStudentBundle
#        grades:
#            label: person.tab.grades
#            include: BusybeeStudentBundle:Person:gradeStart.html.twig
#            message: gradeMessage
#            translation: BusybeeStudentBundle
#        user:
#            label: person.tab.user
#            include: BusybeePersonBundle:Person:user.html.twig
#            message: userMessage
services:
    busybee_people_person.model.person_manager:
        class: Busybee\People\PersonBundle\Model\PersonManager
    busybee_people_person.repository.person_repository:
        class: Busybee\People\PersonBundle\Repository\PersonRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeePersonBundle:Person"
    busybee_people_person.pagination.person_pagination:
        class: Busybee\People\PersonBundle\Pagination\PersonPagination
        arguments:
            - '%personPagination%'
            - '@busybee_people_person.repository.person_repository'
            - '@busybee_core_system.model.my_container'
    busybee_people_person.extension.person_extension:
        class: Busybee\People\PersonBundle\Extension\PersonExtension
        arguments:
            - '@busybee_core_system.setting.setting_manager'
            - '@busybee_people_person.model.person_manager'
            - '@busybee_people_address.model.address_manager'
            - '@busybee_people_phone.model.phone_manager'
        tags:
            - { name: twig.extension }
