# Family
parameters:
    items:
        20:
            label: menu.people.family.manage
            name: Manage Families
            route: family_manage
            parameters: []
            node: 2
            order: 20
            role: ROLE_ADMIN