parameters:
    staffPagination:
        alias: s
        sortBy:
            Family Name:
                p.surname: ASC
                p.firstName: ASC
            Given Name:
                p.firstName: ASC
                p.surname: ASC
            Email:
                p.email: ASC
                p.surname: ASC
                p.firstName: ASC
        limit: '25'
        searchList:
            - p.surname
            - p.firstName
            - p.email
        join:
            s.person:
                type: leftJoin
                alias: p
        select:
            - p.id
            - p.surname
            - p.firstName
            - p.title as details
        choices:
            all:
                route: person_manage
                prompt: pagination.person.all
            student:
                route: student_manage
                prompt: pagination.person.student
            staff:
                route: staff_manage
                prompt: pagination.person.staff
            contact:
                route: contact_manage
                prompt: pagination.person.contact
services:
    staff.repository:
        class: Busybee\StaffBundle\Repository\StaffRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeStaffBundle:Staff"
    form.person.staff.type:
        class: Busybee\StaffBundle\Form\StaffType
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@setting.manager'
        tags:
            - { name: form.type }
    staff.pagination:
        class: Busybee\StaffBundle\Model\StaffPagination
        arguments:
            - '%staffPagination%'
            - '@staff.repository'
            - '@my_service_container'
    staff.grade.voter:
        class: Busybee\StaffBundle\Security\GradeVoter
        arguments:
            - '@security.access.decision_manager'
            - '@person.manager'
        tags:
            - { name: security.voter, priority: 250 }
        public: false
    staff.student.voter:
        class: Busybee\StaffBundle\Security\StudentVoter
        arguments:
            - '@security.access.decision_manager'
            - '@person.manager'
        tags:
            - { name: security.voter, priority: 250 }
        public: false
    staff.staff.voter:
        class: Busybee\StaffBundle\Security\StaffVoter
        arguments:
            - '@security.access.decision_manager'
            - '@person.manager'
        tags:
            - { name: security.voter, priority: 250 }
        public: false
