parameters:
    GradeBundle:
        version: 0.0.01
        settings:
            resources:
                - 'BusybeeGradeBundle/Resources/config/Settings/Settings_0_0_01.yml'
services:
    busybee_management_grade.form.student_grade_type:
        class: Busybee\Program\GradeBundle\Form\StudentGradeType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
    busybee_management_grade.events.student_subscriber:
        class: Busybee\Program\GradeBundle\Events\StudentSubscriber
        tags:
            - { name: doctrine.event_subscriber }
    busybee_management_grade.validator.constraints.grades_validator:
        class: Busybee\Program\GradeBundle\Validator\Constraints\GradesValidator
        tags:
            - { name: validator.constraint_validator, alias: student_grades_validator }
    busybee_management_grade.model.grade_manager:
        class: Busybee\Program\GradeBundle\Model\GradeManager
        arguments:
            - '@doctrine.orm.default_entity_manager'