Busybee\PersonBundle\Entity\Locality:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - name
                - territory
                - postCode
                - country
            errorPath: name
            message: 'locality.unique'
    properties:
        territory:
            - \Busybee\Core\FormBundle\Validator\SettingChoice:
                name: 'Address.TerritoryList'
