Busybee\PersonBundle\Entity\Person:
    properties:
        email:
            - Email:
                  checkMX: true
        email2:
            - Email:
                  checkMX: true
        surname:
            - NotBlank: ~
        firstName:
            - NotBlank: ~
        officialName:
            - NotBlank: ~
        preferredName:
            - NotBlank: ~
        website:
            - Url: ~
        dob:
            - Date: ~
        gender:
            - \Busybee\FormBundle\Validator\SettingChoice:
                name: 'Person.GenderList'
            - NotBlank: ~
        title:
            - \Busybee\FormBundle\Validator\SettingChoice:
                name: 'Person.TitleList'
        photo:
            - \Busybee\PersonBundle\Validator\PersonImage: ~
        phone:
            - Valid: ~
        address1:
            - Valid: ~
        address2:
            - Valid: ~
        staff:
            - Valid: ~
        student:
            - Valid: ~
        user:
            - Valid: ~