Busybee\PersonBundle\Entity\Person:
    properties:
        email:
            - Email:
              checkMX: true
        email2:
            - Email:
              checkMX: true
        surname:
            - NotBlank: ~
        firstName:
            - NotBlank: ~
        officialName:
            - NotBlank: ~
        website:
            - Url: ~
        dob:
            - Date: ~
        gender:
            - Choice:
                choices: { callback: getGenders }
        photo:
            - Image:
                maxSize: 200k
                minWidth: '350'
                maxWidth: '450'
                minHeight: '400'
                maxHeight: '500'
                allowPortrait: false
                minRatio: '0.8'
                maxRatio: '0.9'
        phone:
            - Valid: ~
