Busybee\PersonBundle\Entity\Phone:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [phoneNumber, countryCode]
            errorPath: phoneNumber
    properties:
        phoneNumber:
            - Busybee\PersonBundle\Validator\Phone: ~
        phoneType:
            - \Busybee\FormBundle\Validator\SettingChoice:
                name: 'Phone.TypeList'
        countryCode:
            - \Busybee\FormBundle\Validator\SettingChoice:
                name: 'Phone.CountryList'
