Busybee\PersonBundle\Entity\Staff:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: person
    properties:
        type:
            - NotBlank: ~
        jobTitle:
            - NotBlank: ~