Busybee\PersonBundle\Entity\Student:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: person
    properties:
        startAtSchool:
            - Date: ~
        startAtThisSchool:
            - Date: ~
