# Home
parameters:
    nodes:
        9:
            name: Miscellaneous
            label: menu.Misc
            order: 9
            menu: 9
    items:
        90:
            label: menu.templateDesign
            name: Template Design
            route: home_template
            parameters: []
            node: 9
            order: 90
