# Home
parameters:
    nodes:
        3:
            name: Miscellaneous
            label: menu.Misc
            order: 3
            menu: 3
        5:
            name: curriculum
            label: menu.curriculum
            order: 5
            menu: 5
    items:
        30:
            label: menu.templateDesign
            name: Template Design
            route: home_template
            parameters: []
            node: 3
            order: 30
