Busybee\Core\CalendarBundle\Entity\CalendarGroup:
    type: entity
    table: calendar_group
    repositoryClass: Busybee\Core\CalendarBundle\Repository\CalendarGroupRepository
    uniqueConstraints:
        calendar_short:
            columns:
                - name_short
                - year_id
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        nameShort:
            type: string
            length: '8'
            column: name_short
        name:
            type: string
            length: 24
        sequence:
            type: integer
            length: 2
        website:
            type: string
            length: 200
            nullable: true
        lastModified:
            type: datetime
            column: last_modified
        createdOn:
            type: datetime
            column: created_on
    manyToOne:
        year:
            targetEntity: Busybee\Core\CalendarBundle\Entity\Year
            inversedBy: calendarGroups
            cascade: ['persist']
        createdBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
