Busybee\Core\CalendarBundle\Entity\Grade:
    type: entity
    table: grade
    repositoryClass: Busybee\Core\CalendarBundle\Repository\GradeRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        grade:
            type: string
            length: '8'
        name:
            type: string
            length: '24'
            nullable: true
        sequence:
            type: integer
            length: 2
        lastModified:
            type: datetime
            column: last_modified
        createdOn:
            type: datetime
            column: created_on
    manyToOne:
        year:
            targetEntity: Busybee\Core\CalendarBundle\Entity\Year
            inversedBy: grades
            joinColumn:
                name: year_id
                referencedColumnName: id
        createdBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
