Busybee\Core\CalendarBundle\Entity\Year:
    type: entity
    table: calendar
    repositoryClass: Busybee\Core\CalendarBundle\Repository\YearRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
            unique: true
        firstDay:
            type: date
        lastDay:
            type: date
        status:
            type: string
            length: '20'
        downloadCache:
            column: download_cache
            nullable: true
            length: 150
            type: string
        importIdentifier:
            column: import_identifier
            nullable: true
            type: integer
            length: 3
        lastModified:
            type: datetime
            column: last_modified
        createdOn:
            type: datetime
            column: created_on
    oneToMany:
        terms:
            targetEntity: Busybee\Core\CalendarBundle\Entity\Term
            mappedBy: year
            cascade: [persist, remove]
        specialDays:
            targetEntity: Busybee\Core\CalendarBundle\Entity\SpecialDay
            mappedBy: year
            cascade: [persist, remove]
        calendarGroups:
            targetEntity: Busybee\Core\CalendarBundle\Entity\CalendarGroup
            mappedBy: year
            cascade: [persist, remove]
            orderBy: { sequence: ASC }
    manyToOne:
        createdBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
