Busybee\Core\CalendarBundle\Entity\Year:
    type: entity
    table: calendar
    repositoryClass: Busybee\Core\CalendarBundle\Repository\YearRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
            unique: true
        firstDay:
            type: date
        lastDay:
            type: date
        status:
            type: string
            length: '20'
        lastModified:
            type: datetime
            nullable: true 
        createdOn:
            type: datetime
            nullable: true 
    oneToMany:
        terms:
            targetEntity: Busybee\Core\CalendarBundle\Entity\Term
            mappedBy: year
            cascade: [persist, remove]
        specialDays:
            targetEntity: Busybee\Core\CalendarBundle\Entity\SpecialDay
            mappedBy: year
            cascade: [persist, remove]
        grades:
            targetEntity: Busybee\Core\CalendarBundle\Entity\Grade
            mappedBy: year
            cascade: [persist, remove]
            orderBy: { sequence: ASC }
    manyToOne:
        createdBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                createdBy:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                modifiedBy:
                    referencedColumnName: id
