Busybee\People\StudentBundle\Entity\StudentCalendarGroup:
    type: entity
    table: student_calendar_group
    repositoryClass: Busybee\People\StudentBundle\Repository\StudentCalendarGroupRepository
    uniqueConstraints:
         student_grade:
             columns:
                 - student_id
                 - calendar_group_id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        status:
            type: string
            length: '32'
        lastModified:
            type: datetime
            column: last_modified
        createdOn:
            type: datetime
            column: created_on
    manyToOne:
        calendarGroup:
            targetEntity: Busybee\Core\CalendarBundle\Entity\CalendarGroup
            inversedBy: students
            joinColumns:
                calendar_group_id:
                    referencedColumnName: id
        student:
            targetEntity: Busybee\People\StudentBundle\Entity\Student
            inversedBy: calendarGroups
            joinColumns:
                student_id:
                    referencedColumnName: id
        createdBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
