# This file contains the details of all Busybee Bundles.
# Format is:
#   name:
#       active:  true or false (Defaults to false)
#       type: (core or plugin) (Defaults to plugin)
#       namespace: namespace of the Bundle file
#       route: is an array of  (not compulsory if bundle has no routes.)
#           resource: location of routing file
#           type: Type of file (Default yaml) yaml, xml, php (if using annotations do not supply a route
#           prefix: added as a prefix to the path of the URL
parameters:
    bundles:
        Home:
            active: true
            type: core
            namespace: Busybee\Core\HomeBundle\BusybeeHomeBundle
            route:
                resource: BusybeeHomeBundle/Resources/config/routing.yml
                prefix: /
        Security:
            active: true
            type: core
            namespace: Busybee\Core\SecurityBundle\BusybeeSecurityBundle
            route:
                resource: BusybeeSecurityBundle/Resources/config/routing.yml
                prefix: /security/
        System:
            active: true
            type: core
            namespace: Busybee\Core\SystemBundle\SystemBundle
            route:
                resource: SystemBundle/Resources/config/routing.yml
                prefix: /system/
        Form:
            active: true
            type: core
            namespace: Busybee\Core\FormBundle\BusybeeFormBundle
        Pagination:
            active: true
            type: core
            namespace: Busybee\Core\PaginationBundle\PaginationBundle
        Calendar:
            active: true
            type: plugin
            namespace: Busybee\Core\CalendarBundle\BusybeeCalendarBundle
            route:
                resource: BusybeeCalendarBundle/Resources/config/routing.yml
                prefix: /calendar/
        Family:
            active: true
            type: plugin
            namespace: Busybee\People\FamilyBundle\BusybeeFamilyBundle
            route:
                resource: BusybeeFamilyBundle/Resources/config/routing.yml
                prefix: /family/
        Person:
            active: true
            type: plugin
            namespace: Busybee\People\PersonBundle\BusybeePersonBundle
            route:
                resource: BusybeePersonBundle/Resources/config/routing.yml
                prefix: /person/
        Staff:
            active: true
            type: plugin
            namespace: Busybee\People\StaffBundle\BusybeeStaffBundle
            route:
                resource: BusybeeStaffBundle/Resources/config/routing.yml
                prefix: staff
        Student:
            active: true
            type: plugin
            namespace: Busybee\People\StudentBundle\BusybeeStudentBundle
            route:
                resource: BusybeeStudentBundle/Resources/config/routing.yml
                prefix: student
        Curriculum:
            active: true
            type: plugin
            namespace: Busybee\CurriculumBundle\BusybeeCurriculumBundle
            route:
                resource: "BusybeeCurriculumBundle/Resources/config/routing.yml"
                prefix:   curriculum
                type: yaml
        Institute:
            active: true
            type: plugin
            namespace: Busybee\InstituteBundle\BusybeeInstituteBundle
            route:
                prefix:   institute
                resource: "BusybeeInstituteBundle/Resources/config/routing.yml"
        TimeTable:
            active: true
            type: plugin
            namespace: Busybee\TimeTableBundle\BusybeeTimeTableBundle
            route:
                resource: "BusybeeTimeTableBundle/Resources/config/routing.yml"
                prefix:   timetable
        Activity:
            active: true
            type: plugin
            namespace: Busybee\ActivityBundle\BusybeeActivityBundle
            route:
                resource: "BusybeeActivityBundle/Resources/config/routing.yml"
                prefix:   activity
        Attendance:
            active: true
            type: plugin
            namespace: Busybee\AttendanceBundle\BusybeeAttendanceBundle
            route:
                resource: "BusybeeAttendanceBundle/Resources/config/routing.yml"
                prefix:   attendance
        Period:
            active: true
            type: plugin
            namespace: Busybee\PeriodBundle\BusybeePeriodBundle
            route:
                resource: "BusybeePeriodBundle/Resources/config/routing.yml"
                prefix:   period
        AVETMISS:
            active: false
            type: plugin
            namespace: Busybee\AVETMISS\AVETMISSBundle\BusybeeAVETMISSBundle
            route:
                resource: BusybeeAVETMISSBundle/Resources/config/routing.yml
                prefix: avetmiss
            description: bundle.description.avetmiss