busybee_home:
    resource: "@BusybeeHomeBundle/Resources/config/routing.yml"
    prefix:   /

busybee_security:
    resource: "@BusybeeSecurityBundle/Resources/config/routing.yml"
    prefix:   /security/

busybee_person:
    resource: "@BusybeePersonBundle/Resources/config/routing.yml"
    prefix:   /person/

busybee_system:
    resource: "@SystemBundle/Resources/config/routing.yml"
    prefix:   /system/

busybee_curriculum:
    resource: "@BusybeeCurriculumBundle/Resources/config/routing.yml"
    prefix:   /curriculum/

busybee_institute:
    resource: "@BusybeeInstituteBundle/Resources/config/routing.yml"
    prefix:   /institute/

busybee_staff:
    resource: "@BusybeeStaffBundle/Resources/config/routing.yml"
    prefix:   /staff/

busybee_student:
    resource: "@BusybeeStudentBundle/Resources/config/routing.yml"
    prefix:   /student/

busybee_family:
    resource: "@BusybeeFamilyBundle/Resources/config/routing.yml"
    prefix:   /family/

busybee_enrolment:
    resource: "@BusybeeEnrolmentBundle/Resources/config/routing.yml"
    prefix:   /enrol/


busybee_plugin:
    resource: .
    type: advanced_extra


