busybee_form:
    resource: "@BusybeeFormBundle/Resources/config/routing.yml"
    prefix:   /form

busybee_system:
    resource: "@SystemBundle/Resources/config/routing.yml"
    prefix:   /system/

busybee_home:
    resource: "@BusybeeHomeBundle/Resources/config/routing.yml"
    prefix:   /

busybee_security:
    resource: "@BusybeeSecurityBundle/Resources/config/routing.yml"
    prefix:   /security/
