busybee_home:
    resource: "@BusybeeHomeBundle/Resources/config/routing.yml"
    prefix:   /

busybee_security:
    resource: "@BusybeeSecurityBundle/Resources/config/routing.yml"
    prefix:   /security/

busybee_person:
    resource: "@BusybeePersonBundle/Resources/config/routing.yml"
    prefix:   /person/

busybee_system:
    resource: "@SystemBundle/Resources/config/routing.yml"
    prefix:   /system/

busybee_campus:
    resource: "@BusybeeCampusBundle/Resources/config/routing.yml"
    prefix:   /campus/

busybee_curriculum:
    resource: "@BusybeeCurriculumBundle/Resources/config/routing.yml"
    prefix:   /curriculum/

busybee_plugin:
    resource: .
    type: advanced_extra


