# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    kernel.listener.your_pdo_listener:
        class: Busybee\SystemBundle\EventListener\PDOConnectionListener
        tags:
           - { name: kernel.event_listener, event: kernel.exception, method: onPdoException }