Busybee\InstituteBundle\Entity\Department:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - name
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - nameShort
    properties:
        name:
            - NotBlank: ~
        nameShort:
            - NotBlank: ~
            - Length:
                max: 4
        staff:
            - Valid: ~
            - Busybee\InstituteBundle\Validator\DepartmentStaff:
                errorPath: staff
        type:
            - NotBlank: ~
