# src\Busybee\InstituteBundle\Resources\config\validation\Institute.yml
Busybee\InstituteBundle\Entity\Institute:
    properties:
        phone:
            - General\ValidationBundle\Validator\Constraints\Phone: ~
        facsimile:
            - General\ValidationBundle\Validator\Constraints\Phone: ~
        name:
            - NotBlank: 
                message: validator.institute.name.blank            
        address_line_one:
            - NotBlank: 
                message: validator.institute.address_line_one.blank            
        email:
            - Email:
                checkMX: true
                message: validator.institute.email 
        state:
            - General\ValidationBundle\Validator\Constraints\State: ~
 
                