Busybee\InstituteBundle\Entity\Space:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name, campus]
            errorPath: name
            message: campus.space.unique.name
    properties:
        phoneExt:
            - Busybee\PersonBundle\Validator\Phone: ~