Busybee\InstituteBundle\Entity\StudentYear:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name, schoolYear]
            message: groups.year.unique.name
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [nameShort, schoolYear]
            message: groups.year.unique.nameShort
    properties:
        year:
            - Valid: ~