Busybee\SystemBundle\Entity\Setting:
    type: entity
    table: setting
    repositoryClass: Busybee\SystemBundle\Repository\SettingRepository
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [name]
            errorPath: name
            message: 'unique.setting.name'
    indexes:
        type:
            columns: [ type, name ] 
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: '25'
        name:
            type: string
            length: '64'
            unique: true
        displayName:
            type: string
            length: '64'
            unique: true
            column: display_name
        description:
            type: text
        value:
            type: text
        choice:
            type: string
            length: '50'
            nullable: true
        validator:
            type: string
            length: '255'
            nullable: true
        lastModified:
            type: datetime
            nullable: true 
        createdOn:
            type: datetime
            nullable: true 
    manyToOne:
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            nullable: true
            joinColumns:
                createdBy:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            nullable: true
            joinColumns:
                modifiedBy:
                    referencedColumnName: id
        role:
            targetEntity: Busybee\SecurityBundle\Entity\Role
            cascade: [persist]
            joinColumns:
                role_id:
                    referencedColumnName: id
