# src\Busybee\SystemBundle\Resources\config\doctrine\Setting.orm.yml
Busybee\SystemBundle\Entity\Setting:
    type: entity
    table: system_setting
    repositoryClass: Busybee\SystemBundle\Entity\SettingRepository
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [name]
            errorPath: name
            message: 'The Setting Name must be unique.'
    indexes:
        type:
            columns: [ type, name ] 
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 25
        name:
            type: string
            length: 25
            unique: true
        value:
            type: text
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    manyToOne:
        user:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                user_id:
                    referencedColumnName: id
        role:
            targetEntity: Busybee\SecurityBundle\Entity\Role
            joinColumns:
                role_id:
                    referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ updateLastModified ]
        preUpdate: [ updateLastModified ]
