parameters:
    PaginationBundle:
        version: 0.0.01
        settings:
            resources:
                - 'PaginationBundle/Resources/config/Settings/Settings_0_0_01.yml'
services:
    busybee_core_pagination.form.pagination_type:
        class: Busybee\Core\PaginationBundle\Form\PaginationType
        arguments:
            - '@router'
        tags:
            - { name: form.type }

