parameters:
    Pagination:
        version: 0.0.01
        settings:
            resources:
                - 'BusybeePaginationBundle/Resources/config/Settings/Settings_0_0_01.yml'
services:
    pagination.Type:
        class: Busybee\Core\PaginationBundle\Form\PaginationType
        arguments:
            - '@router'
        tags:
            - { name: form.type }

