# Person
parameters:
    calendar:
        year:
            label: calendar.tab.year
            include: 'BusybeeInstituteBundle:Calendar:year.html.twig'    
            message: yearMessage
        terms:
            label: calendar.tab.terms
            include: 'BusybeeInstituteBundle:Calendar:terms.html.twig'    
            message: termMessage
