address_manage:
    path:     /manage/{id}/
    defaults: { _controller: BusybeeAddressBundle:Address:index }
address_fetch:
    path:     /fetch/
    defaults: { _controller: BusybeeAddressBundle:Address:fetch }
address_delete:
    path:     /delete/{id}/
    defaults: { _controller: BusybeePersonBundle:Address:delete}

