address_manage:
    path:     /{id}/edit/
    defaults: { _controller: BusybeeAddressBundle:Address:index }
address_fetch:
    path:     /address/fetch/
    defaults: { _controller: BusybeeAddressBundle:Address:fetch }

