services:
    busybee_people_address.model.address_manager:
        class: Busybee\People\AddressBundle\Model\AddressManager
        arguments:
            - '@busybee_core_system.setting.setting_manager'
            - '@doctrine.orm.default_entity_manager'
    busybee_people_address.repository.address_repository:
        class: Busybee\People\AddressBundle\Repository\AddressRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeAddressBundle:Address"
    busybee_people_address.form.address_type:
        class: Busybee\People\AddressBundle\Form\AddressType
        arguments:
            - '@busybee_core_system.setting.setting_manager'
            - '@doctrine.orm.default_entity_manager'
        tags:
            - { name: form.type }
