busybee_security_login:
    path:     /login
    defaults: { _controller: BusybeeSecurityBundle:Authentication:login }
busybee_security_check:
    path:     /check
    defaults: { _controller: BusybeeSecurityBundle:Authentication:check }
    methods:  [POST]
busybee_security_resetting_request:
    path:     /request
    defaults: { _controller: BusybeeSecurityBundle:User:request }
busybee_security_logout:
    path:     /logout
    defaults: { _controller: BusybeeSecurityBundle:Authentication:logout }
busybee_security_group_new:
    path:     /group/new
    defaults: { _controller: BusybeeSecurityBundle:Group:new }
    methods:  [GET, POST]
busybee_security_group_edit:
    path:     /group/edit/{GroupID}
    defaults: { _controller: BusybeeSecurityBundle:Group:edit }
    methods:  [GET, POST]
busybee_security_group_list: 
    path:     /group/list
    defaults: { _controller: BusybeeSecurityBundle:Group:list }
busybee_security_group_delete: 
    path:     /group/delete/{GroupID}
    defaults: { _controller: BusybeeSecurityBundle:Group:delete }
busybee_security_user_register:
    path:     /user/register
    defaults: { _controller: BusybeeSecurityBundle:User:register }
busybee_security_user_edit:
    path:     /user/edit
    defaults: { _controller: BusybeeSecurityBundle:User:edit }
    methods:  [GET, POST]
busybee_security_user_list: 
    path:     /user/list
    defaults: { _controller: BusybeeSecurityBundle:User:list }
busybee_switch_user_impersonate:
    path:     /user/impersonate
    defaults: { _controller: BusybeeSecurityBundle:User:impersonate }
busybee_security_user_reset_request:
    path:     /user/request
    defaults: { _controller: BusybeeSecurityBundle:User:request }
busybee_security_user_reset_reset:
    path:     /user/reset/{token}
    defaults: { _controller: BusybeeSecurityBundle:User:reset }
busybee_security_user_reset_send_email:
    path:     /user/sendrequest
    defaults: { _controller: BusybeeSecurityBundle:User:sendEmail }
busybee_security_user_registration_confirmed:
    path:     /user/confirmed 
    defaults: { _controller: BusybeeSecurityBundle:User:confirmed }
busybee_security_role_add: 
    path:     /role/add
    defaults: { _controller: BusybeeSecurityBundle:Role:add }
busybee_security_role_edit: 
    path:     /role/{roleName}/edit
    defaults: { _controller: BusybeeSecurityBundle:Role:edit }
busybee_security_role_list:
    path:     /role/list
    defaults: { _controller: BusybeeSecurityBundle:Role:list }
busybee_security_role_delete:
    path:     /role/delete/{roleName}
    defaults: { _controller: BusybeeSecurityBundle:Role:delete }
busybee_security_createuser:
    path:     /{personID}/createuser
    defaults: { _controller: BusybeeSecurityBundle:User:create }
busybee_security_user_reset_check_email:
    path:     /checkemail
    defaults: { _controller: BusybeeSecurityBundle:User:checkEmail }
