# Security
parameters:
    busybee_security.firewall_name: default 
    busybee_security.user.entity: Busybee\SecurityBundle\Entity\User
    busybee_security.failure.entity: Busybee\SecurityBundle\Entity\Failure
    busybee_security.resetting.token_ttl: 86400 
    busybee_security.resetting.email.template: 'BusybeeSecurityBundle:User:resetting.txt.twig'
    busybee_security.registration.confirmation.template: 'BusybeeSecurityBundle:User:confirmation.txt.twig'
    busybee_security.registration.confirmation.from_email: 
        '%mailer_sender_address%': '%mailer_sender_name%' 
    busybee_security.resetting.email.from_email: 
        '%mailer_sender_address%': '%mailer_sender_name%'
    userPagination: 
        sortBy:
            User Name: 
                a.username: ASC
                a.email: ASC
            Email: 
                a.email: ASC
                a.username: ASC
        limit: 15
        searchList:
            - a.username
            - a.email
    pagePagination:
        alias: p
        sortBy:
            Route:
                p.route: ASC
                p.path: ASC
            Path:
                p.path: ASC
                p.route: ASC
        limit: '25'
        searchList:
            - p.route
            - p.path
    groups:
        Parent: [ROLE_PARENT]
        Student: [ROLE_STUDENT]
        Teaching Staff: [ROLE_STAFF, ROLE_TEACHER, ROLE_ALLOWED_TO_SWITCH]
        Support Staff: [ROLE_STAFF]
        Administration Staff: [ROLE_STAFF, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        Contact: [ROLE_USER]
    roles:
        ROLE_USER: ~
        ROLE_ALLOWED_TO_SWITCH: ~
        ROLE_PARENT: ~
        ROLE_STUDENT: ~
        ROLE_STAFF: ~
        ROLE_TEACHER:
            - ROLE_ALLOWED_TO_SWITCH
            - ROLE_STUDENT
            - ROLE_STAFF
        ROLE_HEAD_TEACHER:
            - ROLE_TEACHER
        ROLE_PRINCIPAL:
            - ROLE_HEAD_TEACHER
        ROLE_ADMIN:
            - ROLE_ALLOWED_TO_SWITCH
        ROLE_REGISTRAR:
            - ROLE_PRINCIPAL
            - ROLE_ADMIN
        ROLE_SYSTEM_ADMIN:
            - ROLE_REGISTRAR


services:
    busybee_security.authentication.login_handler: 
        class: Busybee\SecurityBundle\Model\loginHandler
        arguments:
            - '@router'
            - '@doctrine.orm.entity_manager'
            - '@service_container' 
    busybee_security.authentication.failure_handler:
        class:  Busybee\SecurityBundle\Model\failureHandler
        arguments:  
            - "@http_kernel"
            - "@security.http_utils"
            - {}
            - '@service_container'
        tags:
            - { name: 'monolog.logger.busybee', channel: 'security' }
    busybee_security.user.classmetadata:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments: 
            - '%busybee_security.user.entity%'
    user.repository:
        class: Busybee\SecurityBundle\Repository\UserRepository
        factory: 
            - "@doctrine"
            - getRepository 
        arguments: 
            - "BusybeeSecurityBundle:User"
    busybee_security.user.canonicaliser: 
        class: Busybee\SecurityBundle\Util\Canonicaliser
    security.user_checker:
        class: Symfony\Component\Security\Core\User\UserChecker
        public: false 
    busybee_security.user_manager:
        class: Busybee\SecurityBundle\Doctrine\UserManager
        arguments: 
            - '@security.encoder_factory'
            - '@busybee_security.user.canonicaliser'
            - '@session'
            - '@doctrine.orm.entity_manager'
            - '%busybee_security.user.entity%'
        public: false
    user.manager:
        class: Busybee\SecurityBundle\Doctrine\UserManager
        arguments:
            - '@security.encoder_factory'
            - '@busybee_security.user.canonicaliser'
            - '@session'
            - '@doctrine.orm.entity_manager'
            - '%busybee_security.user.entity%'
        public: false
    busybee_security.user_provider.username:
        class: Busybee\SecurityBundle\Security\UserProvider
        public: false 
        arguments: 
            - '@busybee_security.user_manager'
    busybee_security.interactive_login_listener:
        class: Busybee\SecurityBundle\EventListener\LastLoginListener
        tags:
            - { name: kernel.event_subscriber }
        arguments: 
            - '@busybee_security.user_manager'
            - '@session'
    busybee_security.login_manager:
        class: Busybee\SecurityBundle\Security\LoginManager
        arguments: 
            - '@security.token_storage'
            - '@security.user_checker'
            - '@security.authentication.session_strategy'
            - '@service_container'
    busybee_security.listener.authentication:
        class: Busybee\SecurityBundle\EventListener\AuthenticationListener
        tags:
            - { name: kernel.event_subscriber }
        arguments: 
            - '@busybee_security.login_manager'
            - '%busybee_security.firewall_name%'
    security.role_hierarchy:
        class: Busybee\SecurityBundle\Security\Role\RoleHierarchy
        public: false
        arguments:
            - '%security.role_hierarchy.roles%'
            - '@doctrine.orm.default_entity_manager'
            - '%roles%'
    busybee_security.util.tokengenerator:
        class: Busybee\SecurityBundle\Util\TokenGenerator
        arguments: 
            - '@?logger'
    busybee_security.mailer:
        class: Busybee\SecurityBundle\Mailer\Mailer
        arguments: 
            - '@mailer'
            - '@router'
            - '@templating'
            - { confirmation.template: '%busybee_security.registration.confirmation.template%', resetting.template: '%busybee_security.resetting.email.template%', from_email: { confirmation: '%busybee_security.registration.confirmation.from_email%', resetting: '%busybee_security.resetting.email.from_email%' } }
    busybee_security.authorisation.checker:
        class: Busybee\SecurityBundle\Model\Authorisation 
        arguments:
            - '@security.token_storage'
            - '@security.authentication.manager'
            - '@security.access.decision_manager'
            - '@service_container'
            - '%security.access.always_authenticate_before_granting%'
    busybee_security.session_idle:
        class: Busybee\SecurityBundle\Event\SessionIdleHandler
        arguments: 
            - '@service_container'
            - '@security.token_storage'
            - '%session_max_idle_time%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    security.locale_listener:
        class: Busybee\SecurityBundle\EventListener\LocaleListener
        arguments: 
            - '%kernel.default_locale%'
        tags:
            - { name: kernel.event_subscriber }
    security.role.hierarchy.voter:
        class: Symfony\Component\Security\Core\Authorization\Voter\RoleHierarchyVoter 
        tags:
            - { name: security.voter }
        # small performance boost
        public: false
        arguments: 
            - "@security.role_hierarchy"
    failure_metadata:
        class: Doctrine\ORM\Mapping\ClassMetaData
        arguments: 
            - '%busybee_security.failure.entity%'
    security.failure.repository:
        class: Busybee\SecurityBundle\Repository\FailureRepository
        arguments: 
            - "@doctrine.orm.entity_manager" 
            - "@failure_metadata"
            - '%signin_count_minimum%'
            - '%signin_timeout_period%'
            - '%signin_ip_exceptions%' 
    password.validator:
        class: Busybee\SecurityBundle\Validator\Constraints\PasswordValidator
        tags:
            - { name: validator.constraint_validator, alias: password.validator  }
        arguments:
            - '@service_container'
    user.pagination:
        class: Busybee\SecurityBundle\Model\UserPagination
        arguments: 
            - '%userPagination%'
            - '@user.repository'
            - '@service_container'
    security.page.pagination:
        class: Busybee\SecurityBundle\Model\PagePagination
        arguments:
            - '%pagePagination%'
            - '@security.page.repository'
            - '@my_service_container'
    security.page.repository:
        class: Busybee\SecurityBundle\Repository\PageRepository
        factory:
            - "@doctrine"
            - getRepository
        arguments:
            - "BusybeeSecurityBundle:Page"
    form.group.type:
        class: Busybee\SecurityBundle\Form\GroupType
        arguments:
            - '%groups%'
        tags:
            - { name: form.type }
    form.directrole.type:
        class: Busybee\SecurityBundle\Form\DirectRoleType
        arguments:
            - '%roles%'
        tags:
            - { name: form.type }
    user.manager.extension:
        class: Busybee\SecurityBundle\Model\UserManagerExtension
        arguments:
            - '@busybee_security.user_manager'
        tags:
            - { name: twig.extension }
    voter.details:
        class: Busybee\SecurityBundle\Security\VoterDetails
        arguments:
            - '@doctrine.orm.entity_manager'
    grab.user:
        class: Busybee\SecurityBundle\Model\GrabUser
        arguments:
            - '@my_service_container'
    grab.user.current:
        class: Busybee\SecurityBundle\Model\GrabUser
        factory:
            - '@grab.user'
            - 'getCurrentUser'
    page.manager:
        class: Busybee\SecurityBundle\Model\PageManager
        arguments:
            - '@session'
            - '@doctrine.orm.entity_manager'
            - '@router.default'