person_manage:
    path:     /
    defaults: { _controller: BusybeePersonBundle:Person:index }
person_edit:
    path:     /edit/{id}
    defaults: { _controller: BusybeePersonBundle:Person:edit }
person_save:
    path:     /save/{id}
    defaults: { _controller: BusybeePersonBundle:Person:save }
address_check:
    path:     /address/
    defaults: { _controller: BusybeePersonBundle:Address:check }
locality_manage:
    path:     /locality/{id}/manage/
    defaults: { _controller: BusybeePersonBundle:Locality:index }
locality_fetch:
    path:     /locality/fetch/
    defaults: { _controller: BusybeePersonBundle:Locality:fetch }
address_fetch_list:
    path:     /locality/fetch/list/
    defaults: { _controller: BusybeePersonBundle:Address:fetchList }
locality_delete:
    path:     /locality/{id}/delete/
    defaults: { _controller: BusybeePersonBundle:Locality:delete }
address_manage:
    path:     /address/{id}/edit/
    defaults: { _controller: BusybeePersonBundle:Address:index }
address_delete:
    path:     /address/{id}/delete/
    defaults: { _controller: BusybeePersonBundle:Address:delete}
address_edit:
    path:     /address/edit/
    defaults: { _controller: BusybeePersonBundle:Address:edit }
address_fetch:
    path:     /address/fetch/
    defaults: { _controller: BusybeePersonBundle:Address:fetch }
address_fetch_search:
    path:     /address/search/{id}
    defaults: { _controller: BusybeePersonBundle:Address:search }
phone_fetch:
    path:     /phone/fetch/
    defaults: { _controller: BusybeePersonBundle:Phone:fetch }
