parameters:
    staffPagination:
        alias: s
        sortBy:
            Family Name: 
                p.surname: ASC
                p.firstName: ASC
            Given Name: 
                p.firstName: ASC
                p.surname: ASC
            Email: 
                p.email: ASC
                p.surname: ASC
                p.firstName: ASC
        limit: '10'
        searchList:
            - p.surname
            - p.firstName
            - p.email
        join:
            s.person:
                alias: p
                type: leftJoin
        select:
            - p.surname
            - p.firstName
            - s.id
            - p.email
    personPagination:
        alias: p
        sortBy:
            Family Name: 
                p.surname: ASC
                p.firstName: ASC
            Given Name: 
                p.firstName: ASC
                p.surname: ASC
            Email: 
                p.email: ASC
                p.surname: ASC
                p.firstName: ASC
        limit: '10'
        searchList:
            - p.surnameaddress.formType
            - p.firstName
            - p.email

services:
    person.repository:
        class: Busybee\PersonBundle\Entity\Repository\PersonRepository
        factory: 
            - "@doctrine"
            - 'getRepository' 
        arguments: 
            - "BusybeePersonBundle:Person"
    person.pagination:
        class: Busybee\PersonBundle\Model\PersonPagination
        arguments: 
            - '%personPagination%'
            - '@person.repository'
            - '@service_container'
    staff.repository:
        class: Busybee\PersonBundle\Entity\Repository\StaffRepository
        factory: 
            - "@doctrine"
            - 'getRepository' 
        arguments: 
            - "BusybeePersonBundle:Staff"
    staff.pagination:
        class: Busybee\PersonBundle\Model\StaffPagination
        arguments: 
            - '%staffPagination%'
            - '@staff.repository'
            - '@service_container'
    address.manager:
        class: Busybee\PersonBundle\Model\AddressManager
        arguments:
            - '@translator'
    locality.repository:
        class: Busybee\PersonBundle\Entity\Repository\LocalityRepository
        factory: 
            - "@doctrine"
            - 'getRepository' 
        arguments: 
            - "BusybeePersonBundle:Locality"
    address.repository:
        class: Busybee\PersonBundle\Entity\Repository\AddressRepository
        factory: 
            - "@doctrine"
            - 'getRepository' 
        arguments: 
            - "BusybeePersonBundle:Address"
   