#PersonBundle
parameters:
    staffPagination:
        alias: s
        sortBy:
            Family Name: 
                p.surname: ASC
                p.firstName: ASC
            Given Name: 
                p.firstName: ASC
                p.surname: ASC
            Email: 
                p.email: ASC
                p.surname: ASC
                p.firstName: ASC
        limit: '10'
        searchList:
            - p.surname
            - p.firstName
            - p.email
        join:
            s.person:
                alias: p
                type: leftJoin
        select:
            - p.surname
            - p.firstName
            - s.id
            - p.email
    personPagination:
        alias: p
        sortBy:
            Family Name: 
                p.surname: ASC
                p.firstName: ASC
            Given Name: 
                p.firstName: ASC
                p.surname: ASC
            Email: 
                p.email: ASC
                p.surname: ASC
                p.firstName: ASC
        limit: '10'
        searchList:
            - p.surname
            - p.firstName
            - p.email
services:
    person.repository:
        class: Busybee\PersonBundle\Entity\Repository\PersonRepository
        factory: 
            - "@doctrine"
            - 'getRepository' 
        arguments: 
            - "BusybeePersonBundle:Person"
    person.pagination:
        class: Busybee\PersonBundle\Model\PersonPagination
        arguments: 
            - '%personPagination%'
            - '@person.repository'
            - '@my_service_container'
    staff.repository:
        class: Busybee\PersonBundle\Entity\Repository\StaffRepository
        factory: 
            - "@doctrine"
            - 'getRepository' 
        arguments: 
            - "BusybeePersonBundle:Staff"
    staff.pagination:
        class: Busybee\PersonBundle\Model\StaffPagination
        arguments: 
            - '%staffPagination%'
            - '@staff.repository'
            - '@my_service_container'
    address.manager:
        class: Busybee\PersonBundle\Model\AddressManager
        arguments:
            - '@translator'
            - '@setting.manager'
            - '@address.repository'
    locality.repository:
        class: Busybee\PersonBundle\Entity\Repository\LocalityRepository
        factory: 
            - "@doctrine"
            - 'getRepository' 
        arguments: 
            - "BusybeePersonBundle:Locality"
    address.repository:
        class: Busybee\PersonBundle\Entity\Repository\AddressRepository
        factory: 
            - "@doctrine"
            - 'getRepository' 
        arguments: 
            - "BusybeePersonBundle:Address"
    phone.repository:
        class: Busybee\PersonBundle\Entity\Repository\PhoneRepository
        factory: 
            - "@doctrine"
            - 'getRepository' 
        arguments: 
            - "BusybeePersonBundle:Phone"
    person.uploader.photo:
        class: Busybee\PersonBundle\Model\PhotoUploader
        arguments:
            - "%upload_path%"
    person.listener:
        class: Busybee\PersonBundle\EventListener\PersonListener
        arguments: ['@person.uploader.photo']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postLoad }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postRemove }
    person.form.phoneType:
        class: Busybee\PersonBundle\Form\PhoneType
        arguments:
            - '@setting.manager'
        tags: 
            - { name: form.type }    
    person.form.personType:
        class: Busybee\PersonBundle\Form\PersonType
        arguments:
            - '@setting.manager'
            - '@doctrine.orm.entity_manager'
        tags: 
            - { name: form.type }
    person.form.addressType:
        class: Busybee\PersonBundle\Form\AddressType
        arguments:
            - '@setting.manager'
        tags: 
            - { name: form.type }
    person.form.localityType:
        class: Busybee\PersonBundle\Form\LocalityType
        arguments:
            - '@setting.manager'
            - '@locality.repository'
        tags: 
            - { name: form.type }
    person.phone.validator:
        class: Busybee\PersonBundle\Validator\Constraints\PhoneValidator
        arguments:
            - '@setting.manager'
        tags:
            - { name: validator.constraint_validator, alias: phone_validator }
