# Campus
parameters:
    nodes: []
    items:
        122:
            label: menu.campus.manage
            name: Campus Management
            node: 12
            order: 122
            route: campus_manage
            