Busybee\Facility\InstituteBundle\Entity\Department:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - name
            message: 'department.name.unique'
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - nameShort
            message: 'department.nameShort.unique'
    properties:
        name:
            - NotBlank: ~
        nameShort:
            - NotBlank: ~
            - Length:
                max: 4
        members:
            - Valid: ~
        type:
            - NotBlank: ~
        importIdentifier:
            - Busybee\Core\TemplateBundle\Validator\UniqueOrBlank:
                message: department.importIdentifer.unique
                data_class: 'Busybee\Facility\InstituteBundle\Entity\Department'
        logo:
            - Busybee\Core\TemplateBundle\Validator\Logo: ~
