busybee_security_login:
    path:     /login
    defaults: { _controller: BusybeeSecurityBundle:Authentication:login }
busybee_security_check:
    path:     /check
    defaults: { _controller: BusybeeSecurityBundle:Authentication:check }
    methods:  [POST]
busybee_security_resetting_request:
    path:     /request
    defaults: { _controller: BusybeeSecurityBundle:User:request, id: null }
busybee_security_logout:
    path:     /logout
    defaults: { _controller: BusybeeSecurityBundle:Authentication:logout }
security_timeout:
    path:     /timeout
    defaults: { _controller: BusybeeSecurityBundle:Authentication:timeout }
security_user_reset_request:
    path:     /user/request/{id}
    defaults: { _controller: BusybeeSecurityBundle:User:request }
security_user_reset_reset:
    path:     /user/reset/{token}
    defaults: { _controller: BusybeeSecurityBundle:User:reset }
busybee_security_user_reset_send_email:
    path:     /user/sendrequest
    defaults: { _controller: BusybeeSecurityBundle:User:sendEmail }
busybee_security_user_registration_confirmed:
    path:     /user/confirmed 
    defaults: { _controller: BusybeeSecurityBundle:User:confirmed }
busybee_security_createuser:
    path:     /{personID}/createuser
    defaults: { _controller: BusybeeSecurityBundle:User:create }
busybee_security_user_reset_check_email:
    path:     /checkemail
    defaults: { _controller: BusybeeSecurityBundle:User:checkEmail }
user_toggle_enabled:
    path:     /user/{id}/toggleEnabled/
    defaults: { _controller: BusybeeSecurityBundle:User:toggleEnabled }
google_oauth:
    path:     /oauth2callback/
    defaults: { _controller: BusybeeSecurityBundle:Authentication:google}
page_list:
    path:     /page/list/
    defaults: { _controller: BusybeeSecurityBundle:Page:index}
page_edit:
    path:     /page/{id}/edit/
    defaults: { _controller: BusybeeSecurityBundle:Page:edit}
security_user_edit:
    path:     /user/{id}/edit/
    defaults: { _controller: BusybeeSecurityBundle:User:edit, id: 'Add'}
security_user_list:
    path:     /user/list/
    defaults: { _controller: BusybeeSecurityBundle:User:list }
security_user_delete:
    path:     /user/{id}/delete/
    defaults: { _controller: BusybeeSecurityBundle:User:delete }