# Security
parameters:
    busybee_security.firewall_name: default 
    busybee_security.user.entity: Busybee\Core\SecurityBundle\Entity\User
    busybee_security.failure.entity: Busybee\Core\SecurityBundle\Entity\Failure
    busybee_security.resetting.token_ttl: 86400 
    busybee_security.resetting.email.template: 'BusybeeSecurityBundle:User:resetting.txt.twig'
    busybee_security.registration.confirmation.template: 'BusybeeSecurityBundle:User:confirmation.txt.twig'
    busybee_security.registration.confirmation.from_email: 
        '%mailer_sender_address%': '%mailer_sender_name%' 
    busybee_security.resetting.email.from_email: 
        '%mailer_sender_address%': '%mailer_sender_name%'
    securityPagination:
        alias: u
        sortBy:
            User Name: 
                u.username: ASC
                u.email: ASC
            Email: 
                u.email: ASC
                u.username: ASC
        limit: 25
        searchList:
            - u.username
            - u.email
    pagePagination:
        alias: p
        sortBy:
            Route:
                p.route: ASC
                p.path: ASC
            Path:
                p.path: ASC
                p.route: ASC
        limit: '25'
        searchList:
            - p.route
            - p.path
    groups:
        Parent: [ROLE_PARENT]
        Student: [ROLE_STUDENT]
        Teaching Staff: [ROLE_STAFF, ROLE_TEACHER, ROLE_ALLOWED_TO_SWITCH]
        Support Staff: [ROLE_STAFF]
        Administration Staff: [ROLE_STAFF, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        Contact: [ROLE_USER]
    roles:
        ROLE_USER: ~
        ROLE_ALLOWED_TO_SWITCH: ~
        ROLE_PARENT: ~
        ROLE_STUDENT: ~
        ROLE_STAFF: ~
        ROLE_TEACHER:
            - ROLE_ALLOWED_TO_SWITCH
            - ROLE_STUDENT
            - ROLE_STAFF
        ROLE_HEAD_TEACHER:
            - ROLE_TEACHER
        ROLE_PRINCIPAL:
            - ROLE_HEAD_TEACHER
        ROLE_ADMIN:
            - ROLE_ALLOWED_TO_SWITCH
        ROLE_REGISTRAR:
            - ROLE_PRINCIPAL
            - ROLE_ADMIN
        ROLE_SYSTEM_ADMIN:
            - ROLE_REGISTRAR
            - ROLE_PARENT
    SecurityBundle:
        settings:
            resources:
                - 'BusybeeSecurityBundle/Resources/config/Settings/settings_0_0_01.yml'
        version: 0.0.01

services:
    busybee_core_security.model.login_handler:
        class: Busybee\Core\SecurityBundle\Model\loginHandler
        arguments:
            - '@router'
            - '@doctrine.orm.entity_manager'
            - '@busybee_core_system.model.my_container'
    busybee_core_security.model.failure_handler:
        class:  Busybee\Core\SecurityBundle\Model\failureHandler
        arguments:  
            - "@http_kernel"
            - "@security.http_utils"
            - {}
            - '@busybee_core_system.model.my_container'
        tags:
            - { name: 'busybee_core_template.model.logger', channel: 'security' }
    busybee_core_security.user.entity_name:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments: 
            - '%busybee_security.user.entity%'
    busybee_core_security.repository.user_repository:
        class: Busybee\Core\SecurityBundle\Repository\UserRepository
        factory: 
            - "@doctrine"
            - getRepository 
        arguments: 
            - "BusybeeSecurityBundle:User"
    busybee_core_security.util.canonicaliser:
        class: Busybee\Core\SecurityBundle\Util\Canonicaliser
    busybee_core_security.user.user_checker:
        class: Symfony\Component\Security\Core\User\UserChecker
        public: false 
    busybee_core_security.doctrine.user_manager:
        class: Busybee\Core\SecurityBundle\Doctrine\UserManager
        arguments: 
            - '@security.encoder_factory'
            - '@busybee_core_security.util.canonicaliser'
            - '@session'
            - '@doctrine.orm.entity_manager'
            - '%busybee_security.user.entity%'
        public: false
    busybee_core_security.security.user_provider:
        class: Busybee\Core\SecurityBundle\Security\UserProvider
        public: false 
        arguments: 
            - '@busybee_core_security.doctrine.user_manager'
    busybee_core_security.event_listener.last_login_listener:
        class: Busybee\Core\SecurityBundle\EventListener\LastLoginListener
        tags:
            - { name: kernel.event_subscriber }
        arguments: 
            - '@busybee_core_security.doctrine.user_manager'
            - '@session'
    busybee_core_security.security.login_manager:
        class: Busybee\Core\SecurityBundle\Security\LoginManager
        arguments: 
            - '@security.token_storage'
            - '@busybee_core_security.user.user_checker'
            - '@security.authentication.session_strategy'
            - '@service_container'
    busybee_core_security.event_listener.authentication_listener:
        class: Busybee\Core\SecurityBundle\EventListener\AuthenticationListener
        tags:
            - { name: kernel.event_subscriber }
        arguments: 
            - '@busybee_core_security.security.login_manager'
            - '%busybee_security.firewall_name%'
    busybee_core_security.security.role.role_hierarchy:
        class: Busybee\Core\SecurityBundle\Security\Role\RoleHierarchy
        public: false
        arguments:
            - '%roles%'
            - '@doctrine.orm.default_entity_manager'
            - '%roles%'
    busybee_core_security.util.token_generator:
        class: Busybee\Core\SecurityBundle\Util\TokenGenerator
        arguments: 
            - '@?logger'
    busybee_core_security.mailer.mailer:
        class: Busybee\Core\SecurityBundle\Mailer\Mailer
        arguments: 
            - '@mailer'
            - '@router'
            - '@templating'
            - { confirmation.template: '%busybee_security.registration.confirmation.template%', resetting.template: '%busybee_security.resetting.email.template%', from_email: { confirmation: '%busybee_security.registration.confirmation.from_email%', resetting: '%busybee_security.resetting.email.from_email%' } }
    busybee_core_security.model.authorisation:
        class: Busybee\Core\SecurityBundle\Model\Authorisation
        arguments:
            - '@security.token_storage'
            - '@security.authentication.manager'
            - '@security.access.decision_manager'
            - '@service_container'
            - '%security.access.always_authenticate_before_granting%'
    busybee_core_security.event.session_idle_handler:
        class: Busybee\Core\SecurityBundle\Event\SessionIdleHandler
        arguments: 
            - '@service_container'
            - '@security.token_storage'
            - '%session_max_idle_time%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    busybee_core_security.event_listener.locale_listener:
        class: Busybee\Core\SecurityBundle\EventListener\LocaleListener
        arguments: 
            - '%kernel.default_locale%'
        tags:
            - { name: kernel.event_subscriber }
    busybee_core_security.role.hierarchy.voter:
        class: Symfony\Component\Security\Core\Authorization\Voter\RoleHierarchyVoter 
        tags:
            - { name: security.voter }
        # small performance boost
        public: false
        arguments: 
            - "@busybee_core_security.security.role.role_hierarchy"
    busybee_core_security.failure.metadata:
        class: Doctrine\ORM\Mapping\ClassMetaData
        arguments: 
            - '%busybee_security.failure.entity%'
    busybee_core_security.repository.failure_repository:
        class: Busybee\Core\SecurityBundle\Repository\FailureRepository
        arguments: 
            - "@doctrine.orm.entity_manager" 
            - "@busybee_core_security.failure.metadata"
            - '%signin_count_minimum%'
            - '%session_max_idle_time%'
            - '%signin_ip_exceptions%' 
    busybee_core_security.model.user_pagination:
        class: Busybee\Core\SecurityBundle\Model\UserPagination
        arguments: 
            - '%securityPagination%'
            - '@busybee_core_security.repository.user_repository'
            - '@busybee_core_system.model.my_container'
    busybee_core_security.model.page_pagination:
        class: Busybee\Core\SecurityBundle\Model\PagePagination
        arguments:
            - '%pagePagination%'
            - '@busybee_core_security.repository.page_repository'
            - '@busybee_core_system.model.my_container'
    busybee_core_security.repository.page_repository:
        class: Busybee\Core\SecurityBundle\Repository\PageRepository
        factory:
            - "@doctrine"
            - getRepository
        arguments:
            - "BusybeeSecurityBundle:Page"
    busybee_core_security.form.group_type:
        class: Busybee\Core\SecurityBundle\Form\GroupType
        arguments:
            - '%groups%'
        tags:
            - { name: form.type }
    busybee_core_security.form.direct_role_type:
        class: Busybee\Core\SecurityBundle\Form\DirectRoleType
        arguments:
            - '%roles%'
        tags:
            - { name: form.type }
    busybee_core_security.extension.user_manager_extension:
        class: Busybee\Core\SecurityBundle\Extension\UserManagerExtension
        arguments:
            - '@busybee_core_security.doctrine.user_manager'
        tags:
            - { name: twig.extension }
    busybee_core_security.security.voter_details:
        class: Busybee\Core\SecurityBundle\Security\VoterDetails
        arguments:
            - '@doctrine.orm.entity_manager'
    busybee_core_security.model.grab_user:
        class: Busybee\Core\SecurityBundle\Model\GrabUser
        arguments:
            - '@busybee_core_system.model.my_container'
    busybee_core_security.model.get_current_user:
        class: Busybee\Core\SecurityBundle\Model\GrabUser
        factory:
            - '@busybee_core_security.model.grab_user'
            - 'getCurrentUser'
    busybee_core_security.model.page_manager:
        class: Busybee\Core\SecurityBundle\Model\PageManager
        arguments:
            - '@session'
            - '@doctrine.orm.entity_manager'
            - '@router.default'
