gibbon_import:
    path:     /{offset}/import/
    defaults: { _controller: GibbonBundle:Default:index }
gibbon_start:
    path:     /
    defaults: { _controller: GibbonBundle:Default:index, offset: '0' }
