gibbon_import:
    path:     /{offset}/{function}/import/
    defaults: { _controller: GibbonBundle:Default:index }
gibbon_start:
    path:     /
    defaults: { _controller: GibbonBundle:Default:index }
