services:
    gibbon.model.import_manager:
        class: GibbonBundle\Model\ImportManager
        arguments:
            - '@doctrine.orm.gibbon_entity_manager'
            - '@doctrine.orm.default_entity_manager'
            - '@busybee_people_person.model.person_manager'
