parameters:
    AttendanceBundle:
        version: 0.0.01
        settings:
            resources:
                - 'BusybeeAttendanceBundle/Resources/config/Settings/Settings_0_0_01.yml'
services:
    attendance.repository:
        class: Busybee\AttendanceBundle\Repository\AttendancePeriodRepository
        factory:
            - '@doctrine'
            - 'getRepository'
        arguments:
            - "BusybeeAttendanceBundle:AttendancePeriod"
    attendance.manager:
        class: Busybee\AttendanceBundle\Model\AttendanceManager
        arguments:
            - '@timetable.manager.getTTYear'