System.version:
    type: system
    value: 0.0.01
    displayName: 'Version: System Bundle'
    description: System Setting ONLY
    role: ROLE_SYSTEM_ADMIN
Version.System:
    type: system
    value: '0.0.01'
    displayName: 'System Version'
    description: 'The version of Busybee currently configured on your system.'
    role: 'ROLE_SYSTEM_ADMIN'
Version.Database:
    type: system
    value: '0.0.01'
    displayName: 'Database Version'
    description: 'The version of Busybee Database currently configured on your system.'
    role: 'ROLE_SYSTEM_ADMIN'
