parameters:
    GradeBundle:
        version: 0.0.01
        settings:
            resources:
                - 'BusybeeGradeBundle/Resources/config/Settings/Settings_0_0_01.yml'
services:
    busybee_management_grade.form.student_grade_type:
        class: Busybee\Management\GradeBundle\Form\StudentGradeType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
    busybee_management_grade.events.student_subscriber:
        class: Busybee\Management\GradeBundle\Events\StudentSubscriber
        tags:
            - { name: doctrine.event_subscriber }
