Busybee\Core\SystemBundle\Entity\Setting:
    type: entity
    table: setting
    repositoryClass: Busybee\Core\SystemBundle\Repository\SettingRepository
    indexes:
        type:
            columns: [ type, name ] 
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: '25'
        name:
            type: string
            length: '64'
            unique: true
        displayName:
            type: string
            length: '64'
            unique: true
            column: display_name
        description:
            type: text
        value:
            type: text
            nullable: true
        choice:
            type: string
            length: '50'
            nullable: true
        validator:
            type: string
            length: '255'
            nullable: true
        role:
            type: string
            length: 64
        lastModified:
            type: datetime
            nullable: true 
        createdOn:
            type: datetime
            nullable: true 
    manyToOne:
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            nullable: true
            joinColumns:
                createdBy:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            nullable: true
            joinColumns:
                modifiedBy:
                    referencedColumnName: id
