Busybee\EnrolmentBundle\Entity\Enrolment:
    type: entity
    table: enrolment
    repositoryClass: Busybee\EnrolmentBundle\Repository\EnrolmentRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    manyToOne:
        student:
            targetEntity: Busybee\StudentBundle\Entity\Student
            joinColumns:
                schoolYear:
                    referencedColumnName: id
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                createdBy:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modifiedBy:
                    referencedColumnName: id
