Busybee\EnrolmentBundle\Entity\HomeRoom:
    type: entity
    table: home_room
    repositoryClass: Busybee\EnrolmentBundle\Repository\HomeRoomRepository
    uniqueConstraints:
        year_resource:
            columns: [ schoolYear, campusResource ]
        tutor_year:
            columns: [ tutor1, schoolYear ]
        name_year:
            columns: [ name, schoolYear ]
        nameShort_year:
            columns: [ nameShort, schoolYear ]

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '15'
        nameShort:
            type: string
            length: '5'
        website:
            type: string
            length: '255'
            nullable: true
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    manyToOne:
        schoolYear:
            targetEntity: Busybee\InstituteBundle\Entity\StudentYear
            orderBy: [year: ASC, sequence: ASC]
            joinColumns:
                schoolYear:
                    referencedColumnName: id
        tutor1:
            targetEntity: Busybee\StaffBundle\Entity\Staff
            joinColumns:
                tutor1:
                    referencedColumnName: id
        tutor2:
            targetEntity: Busybee\StaffBundle\Entity\Staff
            joinColumns:
                tutor2:
                    referencedColumnName: id
        tutor3:
            targetEntity: Busybee\StaffBundle\Entity\Staff
            joinColumns:
                tutor3:
                    referencedColumnName: id
        campusResource:
            targetEntity: Busybee\InstituteBundle\Entity\CampusResource
            joinColumns:
                campusResource:
                    referencedColumnName: id
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                createdBy:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modifiedBy:
                    referencedColumnName: id
