services:
    form.errors.parser:
        class: Busybee\FormBundle\Model\FormErrorsParser
    form.all_form_errors_extension:
        class: Busybee\FormBundle\Model\FormErrorsExtension
        arguments:
            - '@form.errors.parser'
            - '@translator'
        tags:
            - { name: twig.extension }
    form.type.image:
        class: Busybee\FormBundle\Type\ImageType
        arguments:
            - '@image.uploader'
        tags: 
            - { name: form.type }    
    image.uploader:
        class: Busybee\FormBundle\Model\ImageUploader
        arguments:
            - "%upload_path%"
    validator.logo:
        class: Busybee\FormBundle\Validator\Logo
    validator.logo.constraint:
        class: Busybee\FormBundle\Validator\Constraints\LogoValidator
        tags:
            - { name: validator.constraint_validator, alias: logo_validator }
    validator.background.image:
        class: Busybee\FormBundle\Validator\BackgroundImage
    validator.background.image.constraint:
        class: Busybee\FormBundle\Validator\Constraints\BackgroundImageValidator
        tags:
            - { name: validator.constraint_validator, alias: background_image_validator }
    form.time.type:
        class: Busybee\FormBundle\Type\TimeType
        arguments:
            - '%timezone%'
        tags: 
            - { name: form.type }
    validator.setting.choice.constraint:
        class: Busybee\FormBundle\Validator\Constraints\SettingChoiceValidator
        arguments:
            - '@setting.manager'
        tags:
            - { name: validator.constraint_validator, alias: setting_validator }
    validator.blank.or.valid.constraint:
        class: Busybee\FormBundle\Validator\Constraints\BlankOrValidValidator
        tags:
            - { name: validator.constraint_validator, alias: blank_or_valid_validator }
    file.uploader:
        class: Busybee\FormBundle\Model\FileUpLoad
        arguments:
            - "%upload_path%"
    form.type.csv:
        class: Busybee\FormBundle\Type\CSVType
        arguments:
            - '@file.uploader'
        tags:
            - { name: form.type }
    form.type.setting:
        class: Busybee\FormBundle\Type\SettingChoiceType
        arguments:
            - '@setting.manager'
        tags:
            - { name: form.type }
