# Person
parameters:
    person:
        person:
            label: person.tab.person
            include: 'BusybeePersonBundle:Person:person.html.twig'    
            message: personMessage
        contact:
            label: person.tab.contact
            include: 'BusybeePersonBundle:Person:contact.html.twig'
        staff:
            label: person.tab.staff
            include: BusybeePersonBundle:Person:staff.html.twig
            message: staffMessage
        careGiver:
            label: person.tab.careGiver
            include: BusybeePersonBundle:Person:careGiver.html.twig
            message: careGiverMessage
        student:
            label: person.tab.student
            include: BusybeePersonBundle:Person:student.html.twig
            message: studentMessage
        user:
            label: person.tab.user
            include: BusybeePersonBundle:Person:user.html.twig
            message: userMessage
