# Person
parameters:
    person:
        person:
            label: person.tab.person
            include: 'BusybeePersonBundle:Person:person.html.twig'    
            message: personMessage
        contact:
            label: person.tab.contact
            include: 'BusybeePersonBundle:Person:contact.html.twig'
        staff:
            label: person.tab.staff
            include: BusybeePersonBundle:Person:staff.html.twig
            message: staffMessage
        careGiver:
            label: person.tab.careGiver
            include: BusybeePersonBundle:Person:careGiver.html.twig
            message: careGiverMessage
