# Person
parameters:
    person:
        person:
            label: person.tab.person
            include: 'BusybeePersonBundle:Person:person.html.twig'    
            message: personMessage
        contact:
            label: person.tab.contact
            include: 'BusybeePersonBundle:Person:contact.html.twig'
        staff:
            label: person.tab.staff
            include: BusybeeStaffBundle:Person:staff.html.twig
            message: staffMessage
            translation: BusybeeStaffBundle
        immigration:
            label: person.tab.immigration
            include: BusybeeStudentBundle:Person:immigration.html.twig
            message: immigrationMessage
            translation: BusybeeStudentBundle
        student:
            label: person.tab.student
            include: BusybeeStudentBundle:Person:student.html.twig
            message: studentMessage
            translation: BusybeeStudentBundle
        grades:
            label: person.tab.grades
            include: BusybeeStudentBundle:Person:gradeStart.html.twig
            message: gradeMessage
            translation: BusybeeStudentBundle
        user:
            label: person.tab.user
            include: BusybeePersonBundle:Person:user.html.twig
            message: userMessage
        extra:
            label: person.tab.extra
            include: BusybeePersonBundle:Person:extra.html.twig
            message: extraMessage
