# Person
parameters:
    person:
        person:
            label: person.tab.person
            include: 'BusybeePersonBundle:Person:person.html.twig'    
            message: personMessage
        contact:
            label: person.tab.contact
            include: 'BusybeePersonBundle:Person:contact.html.twig'
        staff:
            label: person.tab.staff
            include: BusybeeStaffBundle:Person:staff.html.twig
            message: staffMessage
            translation: BusybeeStaffBundle
        student:
            label: person.tab.student
            include: BusybeeStudentBundle:Person:student.html.twig
            message: studentMessage
            translation: BusybeeStudentBundle
        immigration:
            label: person.tab.immigration
            include: BusybeeStudentBundle:Person:immigration.html.twig
            message: immigrationMessage
            translation: BusybeeStudentBundle
        enrolment:
            label: person.tab.enrolment
            include: BusybeeStudentBundle:Person:enrolmentStart.html.twig
            message: enrolmentMessage
            translation: BusybeeStudentBundle
        user:
            label: person.tab.user
            include: BusybeePersonBundle:Person:user.html.twig
            message: userMessage
