parameters:
    activityPagination:
        alias: a
        sortBy:
            Activity Name:
                a.name: ASC
                a.nameShort: ASC
                y.firstDay: DESC
            Grade:
                g.sequence: ASC
                a.name: ASC
                a.nameShort: ASC
                y.name: ASC
        limit: '25'
        searchList:
            - a.name
            - a.nameShort
            - g.grade
            - y.name
        join:
            a.year:
                alias: y
                type: leftJoin
            a.grades:
                alias: g
                type: leftJoin
        select:
            - a.name
            - a.nameShort
            - a.id
            - y.name as year
    studentPagination:
        alias: p
        sortBy:
            Family Name:
                p.surname: ASC
                p.firstName: ASC
            Given Name:
                p.firstName: ASC
                p.surname: ASC
            Email:
                p.email: ASC
                p.surname: ASC
                p.firstName: ASC
        limit: '25'
        searchList:
            - p.surname
            - p.firstName
            - p.email
        choices:
            all:
                route: person_manage
                prompt: pagination.person.all
            student:
                route: student_manage
                prompt: pagination.person.student
            staff:
                route: staff_manage
                prompt: pagination.person.staff
            contact:
                route: contact_manage
                prompt: pagination.person.contact
services:
    student.repository:
        class: Busybee\StudentBundle\Repository\StudentRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeStudentBundle:Student"
    form.person.student.type:
        class: Busybee\StudentBundle\Form\StudentType
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@setting.manager'
        tags:
            - { name: form.type }
    passport.image.validator:
        class: Busybee\StudentBundle\Validator\Constraints\PassportImageValidator
        tags:
            - { name: validator.constraint_validator, alias: passport_image_validator }
    activity.pagination:
        class: Busybee\StudentBundle\Model\ActivityPagination
        arguments:
            - '%activityPagination%'
            - '@activity.repository'
            - '@my_service_container'
            - '@current.year.currentYear'
    activity.repository:
        class: Busybee\StudentBundle\Repository\ActivityRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeStudentBundle:Activity"
    form.activity.type:
        class: Busybee\StudentBundle\Form\ActivityType
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@request_stack'
        tags:
            - { name: form.type }
    student.extension:
        class: Busybee\StudentBundle\Model\StudentExtension
        arguments:
            - '@student.repository'
            - '@translator'
        tags:
            - { name: twig.extension }
    form.person.student.grade.type:
        class: Busybee\StudentBundle\Form\StudentGradeType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
    student.grades.validator:
        class: Busybee\StudentBundle\Validator\Constraints\GradesValidator
        tags:
            - { name: validator.constraint_validator, alias: student_grades_validator }
    student.pagination:
        class: Busybee\StudentBundle\Model\StudentPagination
        arguments:
            - '%studentPagination%'
            - '@person.repository'
            - '@my_service_container'
    activity.manager:
        class: Busybee\StudentBundle\Model\ActivityManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@session.flash_bag'
            - '@translator'
    student.student.voter:
        class: Busybee\StudentBundle\Security\StudentVoter
        arguments:
            - '@security.access.decision_manager'
            - '@person.manager'
        tags:
            - { name: security.voter, priority: 250 }
        public: false
