# FamilyBundle
parameters:
   familyPagination:
        alias: f
        sortBy:
            Family Name:
                f.name: ASC
        limit: '10'
        searchList:
            - f.name
        select:
            - f.name
            - f.id
   FamilyBundle:
        version: 0.0.01
        settings:
            resources:
                - 'BusybeeFamilyBundle/Resources/config/Settings/Settings_0_0_01.yml'
services:
    busybee_people_family.repository.family_repository:
        class: Busybee\People\FamilyBundle\Repository\FamilyRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeFamilyBundle:Family"
    busybee_people_family.model.family_pagination:
        class: Busybee\People\FamilyBundle\Model\FamilyPagination
        arguments:
            - '%familyPagination%'
            - '@busybee_people_family.repository.family_repository'
            - '@busybee_core_system.model.my_container'
    busybee_people_family.form.family_type:
        class: Busybee\People\FamilyBundle\Form\FamilyType
        arguments:
            - '@busybee_people_family.model.family_manager'
        tags:
            - { name: form.type }
    busybee_people_family.model.family_manager:
        class: Busybee\People\FamilyBundle\Model\FamilyManager
        arguments:
            - '@busybee_core_system.setting.setting_manager'
            - '@doctrine.orm.entity_manager'
            - '@busybee_people_person.model.person_manager'
    busybee_people_family.extension.caregiver_extension:
        class: Busybee\People\FamilyBundle\Extension\CareGiverExtension
        tags:
            - { name: twig.extension }
    busybee_people_family.events.caregiver_subscriber:
        class: Busybee\People\FamilyBundle\Events\CareGiverSubscriber
        tags:
            - { name: doctrine.event_subscriber }
