parameters:
    CoursePagination:
        alias: c
        sortBy:
            Name:
                c.name: ASC
                y.sequence: ASC
            Student Year:
                y.sequence: ASC
                c.name: ASC
        limit: '25'
        searchList:
            - c.name
            - y.name
        join:
             c.studentYear:
                 alias: y
                 type: leftJoin
        select:
            - c.name
            - c.id
            - c.version
            - y.name as year
services:
    course.repository:
        class: Busybee\CurriculumBundle\Repository\CourseRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeCurriculumBundle:Course"
    course.pagination:
        class: Busybee\CurriculumBundle\Model\CoursePagination
        arguments:
            - '%CoursePagination%'
            - '@course.repository'
            - '@my_service_container'
    course.form.type:
        class: Busybee\CurriculumBundle\Form\CourseType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
