parameters:
    CoursePagination:
        alias: c
        sortBy:
            Name:
                c.name: ASC
                c.targetYear: ASC
            Target Year:
                c.targetYear: ASC
                c.name: ASC
        limit: '25'
        searchList:
            - c.name
            - c.targetYear
        select:
            - c.name
            - c.id
            - c.version
            - c.targetYear
services:
    course.repository:
        class: Busybee\CurriculumBundle\Repository\CourseRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeCurriculumBundle:Course"
    course.pagination:
        class: Busybee\CurriculumBundle\Model\CoursePagination
        arguments:
            - '%CoursePagination%'
            - '@course.repository'
            - '@my_service_container'
    course.form.type:
        class: Busybee\CurriculumBundle\Form\CourseType
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@setting.manager'
        tags:
            - { name: form.type }
