Busybee\People\StudentBundle\Entity\Student:
    properties:
        startAtSchool:
            - Date: ~
        startAtThisSchool:
            - Date: ~
        lastAtThisSchool:
            - Date: ~
        citizenship1PassportScan:
            - \Busybee\People\StudentBundle\Validator\PassportImage: ~
        nationalIDCardScan:
            - \Busybee\People\StudentBundle\Validator\PassportImage: ~
        house:
            - Busybee\Core\TemplateBundle\Validator\SettingChoice:
                name: 'house.list'
                valueIn: 'name'
