# src\Busybee\SecurityBundle\Resources\config\validation\Group.yml
Busybee\SecurityBundle\Entity\Group: 
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [groupname] 
            message: The Group Name must be unique.
            errorPath: groupname 
    properties:
        groupname:
            - NotBlank: 
                message: The Group Name cannot be blank.
            - Length:
                min: 5 
                max: 64
                minMessage: The Group Name needs to be at least 5 characters long.
                maxMessage: The Group Name needs to be less than 65 characters long.
