# Person
parameters:
    nodes:
        2:
            name: People
            label: menu.Person
            role: ROLE_USER
            order: 2
            menu: 2
    items:
        21:
            label: menu.people.person.manage
            name: Manage People
            route: person_manage
            role: ROLE_ADMIN
            parameters: []
            node: 2
            order: 21
