# Campus
services:
    campus.repository:
        class: Busybee\CampusBundle\Entity\CampusRepository
        factory: 
            - "@doctrine"
            - getRepository 
        arguments: 
            - "BusybeeCampusBundle:Campus"
    campus.form.campusType:
        class: Busybee\CampusBundle\Form\CampusType
        arguments:
            - '@setting.manager'
        tags: 
            - { name: form.type }    
    institute.name.validator:
        class: Busybee\CampusBundle\Validator\Constraints\InstituteNameValidator
        tags:
            - { name: validator.constraint_validator, alias: institute_name_validator }
