Busybee\People\PersonBundle\Entity\Person:
    type: entity
    table: person
    repositoryClass: Busybee\People\PersonBundle\Repository\PersonRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        identifier:
            type: string
            length: '10'
            unique: true
        importIdentifier:
            type: string
            length: '32'
            nullable: true
        title:
            type: string
            length: '5'
            nullable: true
        surname:
            type: string
            length: '50'
        firstName:
            type: string
            length: '50'
        preferredName:
            type: string
            length: '50'
        officialName:
            type: string
            length: '150'
        gender:
            type: string
            length: '1'
        dob:
            type: date
            nullable: true
        email:
            type: string
            length: '65'
            nullable: true
        email2:
            type: string
            length: '65'
            nullable: true
        website:
            type: string
            length: '200'
            nullable: true
        photo:
            type: string
            length: '150'
            nullable: true
        staffQuestion:
            type: boolean
            name: staff_question
        studentQuestion:
            type: boolean
            name: student_question
        lastModified:
            type: datetime
            nullable: true 
        createdOn:
            type: datetime
            nullable: true 
    manyToOne:
        createdBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
        address1:
            targetEntity: Busybee\People\PersonBundle\Entity\Address
            nullable: true
            cascade: [ 'persist' ]
            joinColumns:
                address1:
                    referencedColumnName: id
        address2:
            targetEntity: Busybee\People\PersonBundle\Entity\Address
            nullable: true
            joinColumns:
                address2:
                    referencedColumnName: id
    manyToMany:
        phone:
            targetEntity: Busybee\People\PersonBundle\Entity\Phone
            cascade: [ 'persist' ]
            joinTable:
                name: person_phone
                joinColumns:
                    person_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    phone_id:
                        referencedColumnName: id
    oneToOne:
        user:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            cascade: [persist]
            mappedBy: person
            nullable: true
        staff:
            targetEntity: Busybee\People\StaffBundle\Entity\Staff
            cascade: [all]
            mappedBy: person
            nullable: true
        student:
            targetEntity: Busybee\People\StudentBundle\Entity\Student
            cascade: [all]
            mappedBy: person
            nullable: true
        extra:
            targetEntity: Busybee\People\PersonBundle\Entity\PersonExtra
            cascade: [all]
            mappedBy: person
        preference:
            targetEntity: Busybee\People\PersonBundle\Entity\PersonPreference
            cascade: [all]
            mappedBy: person
    oneToMany:
        careGiver:
            targetEntity: Busybee\People\FamilyBundle\Entity\CareGiver
            mappedBy: person