Busybee\People\PersonBundle\Entity\PersonExtra:
    type: entity
    table: person_extra
    repositoryClass: Busybee\People\PersonBundle\Repository\PersonExtraRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        vehicleRegistration:
            type: string
            length: '25'
            nullable: true
        lastModified:
            type: datetime
            nullable: true 
        createdOn:
            type: datetime
            nullable: true
    oneToOne:
        person:
            targetEntity: Busybee\People\PersonBundle\Entity\Person
            inversedBy: extra
            joinColumn:
                name: person
                referencedColumnName: id
    manyToOne:
        createdBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
