Busybee\People\PhoneBundle\Entity\Phone:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [phoneNumber, countryCode, phoneType]
            errorPath: phoneNumber
    properties:
        phoneNumber:
            - NotBlank: ~
            - \Busybee\People\PhoneBundle\Validator\Phone: ~
        phoneType:
            - NotBlank: ~
            - \Busybee\Core\TemplateBundle\Validator\SettingChoice:
                name: 'phone.typelist'
        countryCode:
            - NotBlank: ~
            - \Busybee\Core\TemplateBundle\Validator\SettingChoice:
                name: 'phone.countrylist'
