Busybee\FamilyBundle\Entity\CareGiver:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [family, person]
            errorPath: family
            message: 'caregiver.unique.fail'