Busybee\FamilyBundle\Entity\Family:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
        careGiver1:
            - NotBlank: ~
            - Valid: ~
        careGiver2:
            - Valid: ~
        phone:
            - Valid: ~
        emergencyContact:
            - Valid: ~