timetable_manage:
    path:     /manage/{currentSearch}
    defaults: { _controller: BusybeeTimeTableBundle:TimeTable:list, currentSearch: null }
timetable_edit:
    path:     /{id}/edit/{currentSearch}
    defaults: { _controller: BusybeeTimeTableBundle:TimeTable:edit, currentSearch: null }
activity_group_list:
    path:     /lgs/list/{currentSearch}
    defaults: { _controller: BusybeeTimeTableBundle:ActivityGroup:list, currentSearch: null }
activity_group_manage:
    path:     /lgs/{id}/manage/{currentSearch}
    defaults: { _controller: BusybeeTimeTableBundle:ActivityGroup:manage, id: 'Add', currentSearch: null }
activity_group_test:
    path:     /lgs/{id}/test/
    defaults: { _controller: BusybeeTimeTableBundle:ActivityGroup:test, id: 'Add' }
timetable_day_assignment:
    path:     /day/assign/
    defaults: { _controller: BusybeeTimeTableBundle:Day:dayAssign }
timetable_day_rotate_toggle:
    path:     /day/{date}/{termName}/rotate/
    defaults: { _controller: BusybeeTimeTableBundle:Day:rotateToggle }
