timetable_manage:
    path:     /manage/
    defaults: { _controller: BusybeeTimeTableBundle:TimeTable:list }
timetable_edit:
    path:     /{id}/edit/
    defaults: { _controller: BusybeeTimeTableBundle:TimeTable:edit}
line_list:
    path:     /line/list/
    defaults: { _controller: BusybeeTimeTableBundle:Line:list }
line_manage:
    path:     /line/{id}/manage/{closeWindow}
    defaults: { _controller: BusybeeTimeTableBundle:Line:manage, id: 'Add', closeWindow: '' }
line_test:
    path:     /line/{id}/test/
    defaults: { _controller: BusybeeTimeTableBundle:Line:test, id: 'Add' }
timetable_day_assignment:
    path:     /day/assign/
    defaults: { _controller: BusybeeTimeTableBundle:Day:dayAssign }
timetable_day_rotate_toggle:
    path:     /day/{date}/{termName}/rotate/
    defaults: { _controller: BusybeeTimeTableBundle:Day:rotateToggle }
timetable_days_edit:
    path:     /{id}/editdays/
    defaults: { _controller: BusybeeTimeTableBundle:TimeTable:editTimeTableDays }
period_remove:
    path:     /period/{id}/{page}/
    defaults: { _controller: BusybeeTimeTableBundle:Period:remove }
column_remove:
    path:     /column/{id}/remove/
    defaults: { _controller: BusybeeTimeTableBundle:Column:remove }
column_resettimes:
    path:     /column/{id}/reset/times/
    defaults: { _controller: BusybeeTimeTableBundle:Column:resetTimes }
period_plan:
    path:     /plan/{id}/activity/
    defaults: { _controller: BusybeeTimeTableBundle:Period:periodPlan }
period_plan_report:
    path:     /plan/{id}/activity/report/
    defaults: { _controller: BusybeeTimeTableBundle:Period:report }
period_add_line:
    path:     /plan/{id}/{line}/activities/
    defaults: { _controller: BusybeeTimeTableBundle:Period:addLineToPlan }
period_remove_activity:
    path:     /plan/{id}/remove/{activity}/activities/
    defaults: { _controller: BusybeeTimeTableBundle:Period:removePeriodActivity }
period_activity_edit:
    path:     /plan/{activity}/edit/activity/
    defaults: { _controller: BusybeeTimeTableBundle:Period:editPeriodActivity }
period_full_report:
    path:     /period/{id}/full/report/
    defaults: { _controller: BusybeeTimeTableBundle:Period:fullReport }
period_duplicate:
    path:     /period/{source}/{target}/duplicate
    defaults: { _controller: BusybeeTimeTableBundle:Period:duplicate }
timetable_builder:
    path:     /{id}/builder/{all}/
    defaults: { _controller: BusybeeTimeTableBundle:TimeTable:builder, all: 'All' }
period_builder_line:
    path:     /plan/{id}/{line}/builder/activities/
    defaults: { _controller: BusybeeTimeTableBundle:TimeTable:addLineToPeriod }
period_builder_activity:
    path:     /plan/{id}/{activity}/builder/activity/
    defaults: { _controller: BusybeeTimeTableBundle:TimeTable:addActivityToPeriod }
line_delete:
    path:     /line/{id}/delete/
    defaults: { _controller: BusybeeTimeTableBundle:Line:delete }
grade_control:
    path:     /grade/{grade}/control/
    defaults: { _controller: BusybeeTimeTableBundle:TimeTable:gradeControl }
timetable_display:
    path:     /display/
    defaults: { _controller: BusybeeTimeTableBundle:TimeTable:display }
timetable_refresh_display:
    path:     /display/{displayDate}/refresh/
    defaults: { _controller: BusybeeTimeTableBundle:TimeTable:refreshDisplay }
timetable_grade_set:
    path:     /grade/{grade}/set/
    defaults: { _controller: BusybeeTimeTableBundle:TimeTable:setTimeTableGrade }
timetable_space_set:
    path:     /space/{space}/set/
    defaults: { _controller: BusybeeTimeTableBundle:TimeTable:setTimeTableSpace }
timetable_staff_set:
    path:     /staff/{staff}/set/
    defaults: { _controller: BusybeeTimeTableBundle:TimeTable:setTimeTableStaff }
