timetable_manage:
    path:     /manage/
    defaults: { _controller: BusybeeTimeTableBundle:TimeTable:list }
timetable_edit:
    path:     /{id}/edit/
    defaults: { _controller: BusybeeTimeTableBundle:TimeTable:edit}
activity_group_list:
    path:     /lgs/list/
    defaults: { _controller: BusybeeTimeTableBundle:ActivityGroup:list }
activity_group_manage:
    path:     /lgs/{id}/manage/
    defaults: { _controller: BusybeeTimeTableBundle:ActivityGroup:manage, id: 'Add' }
activity_group_test:
    path:     /lgs/{id}/test/
    defaults: { _controller: BusybeeTimeTableBundle:ActivityGroup:test, id: 'Add' }
timetable_day_assignment:
    path:     /day/assign/
    defaults: { _controller: BusybeeTimeTableBundle:Day:dayAssign }
timetable_day_rotate_toggle:
    path:     /day/{date}/{termName}/rotate/
    defaults: { _controller: BusybeeTimeTableBundle:Day:rotateToggle }
timetable_days_edit:
    path:     /{id}/editdays/
    defaults: { _controller: BusybeeTimeTableBundle:TimeTable:editTimeTableDays }
period_remove:
    path:     /period/{id}/{page}/
    defaults: { _controller: BusybeeTimeTableBundle:Period:remove }
column_remove:
    path:     /column/{id}/remove/
    defaults: { _controller: BusybeeTimeTableBundle:Column:remove }
column_resettimes:
    path:     /column/{id}/reset/times/
    defaults: { _controller: BusybeeTimeTableBundle:Column:resetTimes }
period_plan:
    path:     /plan/{id}/activity/
    defaults: { _controller: BusybeeTimeTableBundle:Period:periodPlan }
period_plan_report:
    path:     /plan/{id}/activity/report/
    defaults: { _controller: BusybeeTimeTableBundle:Period:report }
period_add_activities_to_plan:
    path:     /plan/{id}/{line}/activities/
    defaults: { _controller: BusybeeTimeTableBundle:Period:addActivitiesToPlan }
period_remove_activity:
    path:     /plan/{id}/remove/{activity}/activities/
    defaults: { _controller: BusybeeTimeTableBundle:Period:removePeriodActivity }
period_activity_edit:
    path:     /plan/{activity}/edit/activity/
    defaults: { _controller: BusybeeTimeTableBundle:Period:editPeriodActivity }
