parameters:
    TimeTablePagination:
        alias: t
        sortBy:
            Year:
                y.firstDay: DESC
                t.name: ASC
            Name:
                t.name: ASC
                y.firstDay: DESC
            Short Name:
                t.nameShort: ASC
                y.firstDay: DESC
        limit: '25'
        join:
            t.year:
                alias: y
                type: leftJoin
        searchList:
            - t.name
            - t.nameShort
            - y.name
        select:
            - t.name
            - t.nameShort
            - t.id
            - y.name as year
    ActivityGroupsPagination:
        alias: a
        sortBy:
            Name:
                a.name: ASC
                a.nameShort: ASC
            Short Name:
                a.nameShort: ASC
                a.name: ASC
            Course:
                c.name: ASC
                a.name: ASC
        limit: '25'
        join:
            a.course:
                alias: c
                type: leftJoin
        searchList:
            - a.name
            - a.nameShort
            - c.name
        select:
            - a.name
            - a.nameShort
            - c.name as course
            - a.id
services:
    timetable.repository:
        class: Busybee\TimeTableBundle\Repository\TimeTableRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeTimeTableBundle:TimeTable"
    timetable.pagination:
        class: Busybee\TimeTableBundle\Model\TimeTablePagination
        arguments:
            - '%TimeTablePagination%'
            - '@timetable.repository'
            - '@my_service_container'
    form.timetable.type:
        class: Busybee\TimeTableBundle\Form\TimeTableType
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@setting.manager'
        tags:
            - { name: form.type }
    activity.groups.repository:
        class: Busybee\TimeTableBundle\Repository\ActivityGroupsRepository
        factory:
            - '@doctrine'
            - 'getRepository'
        arguments:
            - "BusybeeTimeTableBundle:ActivityGroups"
    activity.groups.pagination:
        class: Busybee\TimeTableBundle\Model\ActivityGroupsPagination
        arguments:
            - '%ActivityGroupsPagination%'
            - '@activity.groups.repository'
            - '@my_service_container'
    activity.groups.manager:
        class: Busybee\TimeTableBundle\Model\ActivityGroupsManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@translator'
    form.timetable.column.type:
        class: Busybee\TimeTableBundle\Form\ColumnEntityType
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@setting.manager'
        tags:
            - { name: form.type }
    form.timetable.day.type:
        class: Busybee\TimeTableBundle\Form\DayEntityType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
    timetable.manager:
        class: Busybee\TimeTableBundle\Model\TimeTableManager
        arguments:
            - '@security.token_storage'
            - '@busybee_security.user_manager'
            - '@doctrine.orm.entity_manager'
            - '@setting.manager'
    form.timetable.days.type:
        class: Busybee\TimeTableBundle\Form\TimeTableDaysType
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@setting.manager'
        tags:
            - { name: form.type }
    form.timetable.hidden.day.type:
        class: Busybee\TimeTableBundle\Form\DayHiddenType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
    form.timetable.columns.type:
        class: Busybee\TimeTableBundle\Form\ColumnType
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@setting.manager'
        tags:
            - { name: form.type }
    form.timetable.period.type:
        class: Busybee\TimeTableBundle\Form\PeriodType
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@setting.manager'
        tags:
            - { name: form.type }
    column.repository:
        class: Busybee\TimeTableBundle\Repository\ColumnRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeTimeTableBundle:Column"
    form.timetable.column.period.type:
        class: Busybee\TimeTableBundle\Form\ColumnPeriodType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
    period.repository:
        class: Busybee\TimeTableBundle\Repository\PeriodRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeTimeTableBundle:Period"
    period.manager:
        class: Busybee\TimeTableBundle\Model\PeriodManager
        arguments:
            - '@doctrine.orm.entity_manager'
    periods.validator:
        class: Busybee\TimeTableBundle\Validator\Constraints\PeriodsValidator
        arguments:
            - "@setting.manager"
        tags:
            - { name: validator.constraint_validator, alias: periods_validator }
    columns.validator:
        class: Busybee\TimeTableBundle\Validator\Constraints\ColumnsValidator
        arguments:
            - "@setting.manager"
        tags:
            - { name: validator.constraint_validator, alias: columns_validator }
    period.plan.repository:
        class: Busybee\TimeTableBundle\Repository\PeriodPlanRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeTimeTableBundle:PeriodPlan"

