parameters:
    TimeTablePagination:
        alias: t
        sortBy:
            Year:
                y.firstDay: DESC
                t.name: ASC
            Name:
                t.name: ASC
                y.firstDay: DESC
            Short Name:
                t.nameShort: ASC
                y.firstDay: DESC
        limit: '25'
        join:
            t.year:
                alias: y
                type: leftJoin
        searchList:
            - t.name
            - t.nameShort
            - y.name
        select:
            - t.name
            - t.nameShort
            - t.id
            - y.name as year
    LinePagination:
        alias: l
        sortBy:
            Name:
                l.name: ASC
                l.nameShort: ASC
            Short Name:
                l.nameShort: ASC
                l.name: ASC
            Course:
                c.name: ASC
                l.name: ASC
        limit: '25'
        join:
            l.course:
                alias: c
                type: leftJoin
            l.activities:
                alias: a
                type: leftJoin
            a.grades:
                alias: g
                type: leftJoin
        searchList:
            - l.name
            - l.nameShort
            - c.name
        select:
            - l.name
            - l.nameShort
            - c.name as course
            - l.id
    PeriodPagination:
        alias: p
        sortBy:
            Time:
                c.sequence: ASC
                p.start: ASC
            Name:
                c.sequence: ASC
                p.name: ASC
            Code:
                c.sequence: ASC
                p.nameShort: ASC
        limit: '25'
        join:
            p.column:
                alias: c
                type: leftJoin
        searchList:
            - c.name
            - p.nameShort
            - p.name
        select:
            - p.name
            - p.nameShort
            - c.name as columnName
            - p.id
            - p.start
            - p.end
services:
    timetable.repository:
        class: Busybee\TimeTableBundle\Repository\TimeTableRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeTimeTableBundle:TimeTable"
    timetable.pagination:
        class: Busybee\TimeTableBundle\Model\TimeTablePagination
        arguments:
            - '%TimeTablePagination%'
            - '@timetable.repository'
            - '@my_service_container'
    form.timetable.type:
        class: Busybee\TimeTableBundle\Form\TimeTableType
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@setting.manager'
        tags:
            - { name: form.type }
    line.repository:
        class: Busybee\TimeTableBundle\Repository\LineRepository
        factory:
            - '@doctrine'
            - 'getRepository'
        arguments:
            - "BusybeeTimeTableBundle:Line"
    line.pagination:
        class: Busybee\TimeTableBundle\Model\LinePagination
        arguments:
            - '%LinePagination%'
            - '@line.repository'
            - '@my_service_container'
            - '@current.year.currentYear'
    line.manager:
        class: Busybee\TimeTableBundle\Model\LineManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@translator'
            - '@session.flash_bag'
    form.timetable.column.type:
        class: Busybee\TimeTableBundle\Form\ColumnEntityType
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@setting.manager'
        tags:
            - { name: form.type }
    form.timetable.day.type:
        class: Busybee\TimeTableBundle\Form\DayEntityType
        arguments:
            - '@doctrine.orm.default_entity_manager'
        tags:
            - { name: form.type }
    timetable.manager:
        class: Busybee\TimeTableBundle\Model\TimeTableManager
        arguments:
            - '@current.year.currentYear'
            - '@doctrine.orm.default_entity_manager'
            - '@setting.manager'
            - '@period.manager'
            - '@session'
            - '@translator'
    timetable.display.manager:
        class: Busybee\TimeTableBundle\Model\TimeTableDisplayManager
        arguments:
            - '@current.year.currentYear'
            - '@doctrine.orm.default_entity_manager'
            - '@setting.manager'
            - '@period.manager'
            - '@session'
            - '@person.manager'
            - '@translator'
    form.timetable.hidden.day.type:
        class: Busybee\TimeTableBundle\Form\DayHiddenType
        arguments:
            - '@doctrine.orm.default_entity_manager'
        tags:
            - { name: form.type }
    form.timetable.columns.type:
        class: Busybee\TimeTableBundle\Form\ColumnType
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@setting.manager'
        tags:
            - { name: form.type }
    form.timetable.period.type:
        class: Busybee\TimeTableBundle\Form\PeriodType
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@setting.manager'
        tags:
            - { name: form.type }
    column.repository:
        class: Busybee\TimeTableBundle\Repository\ColumnRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeTimeTableBundle:Column"
    form.timetable.column.period.type:
        class: Busybee\TimeTableBundle\Form\ColumnPeriodType
        arguments:
            - '@doctrine.orm.default_entity_manager'
        tags:
            - { name: form.type }
    period.repository:
        class: Busybee\TimeTableBundle\Repository\PeriodRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeTimeTableBundle:Period"
    period.manager:
        class: Busybee\TimeTableBundle\Model\PeriodManager
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@translator'
            - '@session.flash_bag'
            - '@current.year.currentYear'
            - '@session'
    period.pagination:
        class: Busybee\TimeTableBundle\Model\PeriodPagination
        arguments:
            - '%PeriodPagination%'
            - '@period.repository'
            - '@my_service_container'
            - '@timetable.manager.getTimeTable'
    periods.validator:
        class: Busybee\TimeTableBundle\Validator\Constraints\PeriodsValidator
        arguments:
            - "@setting.manager"
        tags:
            - { name: validator.constraint_validator, alias: periods_validator }
    columns.validator:
        class: Busybee\TimeTableBundle\Validator\Constraints\ColumnsValidator
        arguments:
            - "@setting.manager"
        tags:
            - { name: validator.constraint_validator, alias: columns_validator }
    period.activity.repository:
        class: Busybee\TimeTableBundle\Repository\PeriodActivityRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeTimeTableBundle:PeriodActivity"
    form.period.activity.entity.type:
        class: Busybee\TimeTableBundle\Form\PeriodActivityEntityType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
    form.period.activity.edit.type:
        class: Busybee\TimeTableBundle\Form\EditPeriodActivityType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
    form.line.type:
        class: Busybee\TimeTableBundle\Form\LineType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
    timetable.manager.getTimeTable:
        class: Busybee\TimeTableBundle\Model\TimeTableManager
        factory:
            - '@timetable.manager'
            - 'getTimeTable'
    timetable.activity.manager:
        class: Busybee\TimeTableBundle\Model\ActivityManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@session.flash_bag'
            - '@translator'
            - '@current.year.currentYear'
