parameters:
    TimeTablePagination:
        alias: t
        sortBy:
            Name:
                t.name: ASC
                y.firstDay: ASC
            Short Name:
                t.nameShort: ASC
                y.firstDay: ASC
            Year:
                y.firstDay: ASC
                t.name: ASC
        limit: '25'
        join:
            t.year:
                alias: y
                type: leftJoin
        searchList:
            - t.name
            - t.nameShort
            - y.name
        select:
            - t.name
            - t.nameShort
            - t.id
            - y.name as year
    LearningGroupsPagination:
        alias: l
        sortBy:
            Name:
                l.name: ASC
                l.nameShort: ASC
            Short Name:
                l.nameShort: ASC
                l.name: ASC
            Course:
                c.name: ASC
                l.name: ASC
        limit: '25'
        join:
            l.course:
                alias: c
                type: leftJoin
        searchList:
            - l.name
            - l.nameShort
            - c.name
        select:
            - l.name
            - l.nameShort
            - c.name as course
            - l.id
services:
    timetable.repository:
        class: Busybee\TimeTableBundle\Repository\TimeTableRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeTimeTableBundle:TimeTable"
    timetable.pagination:
        class: Busybee\TimeTableBundle\Model\TimeTablePagination
        arguments:
            - '%TimeTablePagination%'
            - '@timetable.repository'
            - '@my_service_container'
    form.timetable.type:
        class: Busybee\TimeTableBundle\Form\TimeTableType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
    form.timetable.line.type:
        class: Busybee\TimeTableBundle\Form\LineType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
    learning.groups.repository:
        class: Busybee\TimeTableBundle\Repository\LearningGroupsRepository
        factory:
            - '@doctrine'
            - 'getRepository'
        arguments:
            - "BusybeeTimeTableBundle:LearningGroups"
    learning.groups.pagination:
        class: Busybee\TimeTableBundle\Model\LearningGroupsPagination
        arguments:
            - '%LearningGroupsPagination%'
            - '@learning.groups.repository'
            - '@my_service_container'
    learning.groups.manager:
        class: Busybee\TimeTableBundle\Model\LearningGroupsManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@translator'

