Busybee\People\FamilyBundle\Entity\CareGiver:
    type: entity
    table: caregiver
    repositoryClass: Busybee\People\FamilyBundle\Repository\CareGiverRepository
    uniqueConstraints:
        familyPerson:
            columns:
                - family_id
                - person_id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        comment:
            type: text
            nullable: true
        phoneContact:
            type: boolean
        smsContact:
            type: boolean
        emailContact:
            type: boolean
        mailContact:
            type: boolean
        lastModified:
            type: datetime
        createdOn:
            type: datetime
        contactPriority:
            type: integer
            length: 2
        relationship:
            type: string
            length: 32
        newsletter:
            type: boolean
        finance:
            type: boolean
        pickUpAllowed:
            type: boolean
        emergencyOnly:
            type: boolean
        reporting:
            type: boolean
    manyToOne:
        person:
            targetEntity: Busybee\People\PersonBundle\Entity\Person
            inversedBy: careGivers
            joinColumn:
                name: person_id
                referencedColumnName: id
                nullable: false
        family:
            targetEntity: Busybee\People\FamilyBundle\Entity\Family
            inversedBy: careGivers
            joinColumn:
                name: family_id
                referencedColumnName: id
                nullable: false
        createdBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
