# Enrolment
parameters:
    nodes: []
    items: []
#        23:
#            label: menu.Student
#            name: Manage Students
#            node: 2
#            order: 23
#            menu: 23
#        230:
#            label: menu.Enrolment
#            name: Enrolment
#            node: 23
#            order: 230
#            menu: 230


