Busybee\AttendanceBundle\Entity\AttendancePeriod:
    type: entity
    table: attendance_period
    repositoryClass: Busybee\AttendanceBundle\Repository\AttendancePeriodRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        attendanceDate:
            type: datetime
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    oneToMany:
        students:
            targetEntity: Busybee\AttendanceBundle\Entity\AttendancePeriodStudent
            mappedBy: attendancePeriod
            cascade: [ 'all' ]
    manyToOne:
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                createdBy:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modifiedBy:
                    referencedColumnName: id
