# src\General\ValidationBundle\Resources\config\doctrine\Validator.orm.yml
General\ValidationBundle\Entity\Validator:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [ConstraintName, ConstraintGroup]
            errorPath: ConstraintName
            message: validator.name.unique
    properties:
        ConstraintName:
            - NotBlank: 
                message: validator.name.blank 
        ConstraintGroup:
            - NotBlank: 
                message: validator.group.blank 
        message:
            - Collection:
                fields:
                    key: 
                        - Choice: ~
                    value: ~ 
                allowMissingFields: true
