Busybee\ActivityBundle\Entity\Activity:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name, year]
            errorPath: name
            message: activity.nameyear.unique
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [nameShort, year]
            errorPath: nameShort
            message: activity.nameshortyear.unique
        - Callback: studentNumbersValidate
    properties:
        name:
            - NotBlank: ~
        nameShort:
            - NotBlank: ~
            - Busybee\Core\FormBundle\Validator\NoWhiteSpace: ~
        year:
            - Valid: ~
            - NotBlank: ~
        teachingLoad:
            - Busybee\Core\FormBundle\Validator\Integer: ~
            - Range:
                min: 0
                max: 99