install_start:
    path:     /install/start/
    defaults: { _controller: SystemBundle:Install:index }
install_check_mailer_parameters:
    path:     /install/checkMailer/
    defaults: { _controller: SystemBundle:Install:checkMailer }
install_save_mailer:
    path:     /install/saveMailer/
    defaults: { _controller: SystemBundle:Install:saveMailer }
install_misc_check: 
    path:     /install/miscCheck/
    defaults: { _controller: SystemBundle:Install:miscCheck }
install_misc_save: 
    path:     /install/miscSave/
    defaults: { _controller: SystemBundle:Install:miscSave }
install_build_system:
    path:     /install/build/
    defaults: { _controller: SystemBundle:Install:build }
update_start:
    path:     /update/start/
    defaults: { _controller: SystemBundle:Update:index }
update_database:
    path:     /update/database/
    defaults: { _controller: SystemBundle:Update:database }
setting_manage:
    path:     /setting/manage/
    defaults: { _controller: SystemBundle:Setting:index }
setting_upload:
    path:     /setting/upload/
    defaults: { _controller: SystemBundle:Setting:upload }
setting_edit:
    path:     /setting/{id}/edit/
    defaults: { _controller: SystemBundle:Setting:edit }
setting_edit_name:
    path:     /setting/{name}/editName/
    defaults: { _controller: SystemBundle:Setting:editName }
plugin_manage:
    path:     /plugin/manage/
    defaults: { _controller: SystemBundle:Plugin:manager }
install_update:
    path:     /update/install/
    defaults: { _controller: SystemBundle:Update:install }
setting_create:
    path: /setting/create/
    defaults: { _controller: SystemBundle:Setting:create }
install_connection_fail:
    path: /install/connection/{exception}/fail/
    defaults: { _controller: SystemBundle:Install:connectionFail }