system_homepage:
    path:     /
    defaults: { _controller: SystemBundle:Default:index }
install_start:
    path:     /install/start/
    defaults: { _controller: SystemBundle:Install:index }
install_save_database_parameters:
    path:     /install/saveDatabase/
    defaults: { _controller: SystemBundle:Install:saveDatabase }
install_check_mailer_parameters:
    path:     /install/checkMailer/
    defaults: { _controller: SystemBundle:Install:checkMailer }
install_save_mailer:
    path:     /install/saveMailer/
    defaults: { _controller: SystemBundle:Install:saveMailer }
install_misc_check: 
    path:     /install/miscCheck/
    defaults: { _controller: SystemBundle:Install:miscCheck }
install_misc_save: 
    path:     /install/miscSave/
    defaults: { _controller: SystemBundle:Install:miscSave }
install_build_system:
    path:     /install/build/
    defaults: { _controller: SystemBundle:Install:build }
update_start:
    path:     /update/start/
    defaults: { _controller: SystemBundle:Update:index }
update_database:
    path:     /update/database/
    defaults: { _controller: SystemBundle:Update:database }
setting_manage:
    path:     /setting/manage
    defaults: { _controller: SystemBundle:Setting:index }
setting_edit:
    path:     /setting/edit/{id}
    defaults: { _controller: SystemBundle:Setting:edit }

