# System Bundle
parameters:
    kernel_root_dir: '%kernel.root_dir%'
    version:
        system: '0.0.03'
        database: '0.0.03'
    settingPagination:
        alias: s
        sortBy:
            Name: 
                s.displayName: ASC
                s.description: ASC
            Description: 
                s.description: ASC
                s.displayName: ASC
        limit: '10'
        searchList:
            - s.displayName
            - s.description
        select:
            - s.displayName
            - s.description
            - s.id

services:
    monolog.formatter.session_request:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] [%%extra.token%%] %%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"
    monolog.processor.session_request:
        class: Busybee\SystemBundle\Model\SessionRequestProcessor
        arguments:  ["@session"]
        tags:
            - { name: monolog.processor, method: processRecord }
    monolog.logger.busybee:
        class: Busybee\SystemBundle\Model\BusybeeLogger 
        arguments: ['@logger']
        tags:
            - { name: monolog.logger, channel: busybee }
    doctrine.tblprefix_subscriber:
        class: Busybee\SystemBundle\Subscriber\TablePrefixSubscriber
        arguments: 
            - '%database_prefix%'
        tags:
            - { name: doctrine.event_subscriber }    
    system.setting.repository:
        class: Busybee\SystemBundle\Entity\SettingRepository
        factory: 
            - "@doctrine"
            - getRepository 
        arguments: 
            - "SystemBundle:Setting"
    setting.repository:
        class: Busybee\SystemBundle\Entity\SettingRepository
        factory: 
            - "@doctrine"
            - getRepository 
        arguments: 
            - "SystemBundle:Setting"
    system.update.manager:
        class: Busybee\SystemBundle\Update\UpdateManager
        arguments: 
            - "@my_service_container"
    system.password.manager:
        class: Busybee\SystemBundle\Password\PasswordManager
    busybee.writeDoctrine.listener:
        class: Busybee\SystemBundle\EventListener\WriteDoctrineListener
        arguments: 
            - "@my_service_container"
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }
    setting.manager:
        class: Busybee\SystemBundle\Setting\SettingManager
        arguments: 
            - "@my_service_container"
    plugin.manager:
        class: Busybee\SystemBundle\Plugin\PluginManager
        arguments: 
            - "@my_service_container"
    setting.pagination:
        class: Busybee\SystemBundle\Model\SettingPagination
        arguments: 
            - '%settingPagination%'
            - '@setting.repository'
            - '@my_service_container'
    setting.extension:
        class: Busybee\SystemBundle\Model\SettingExtension
        arguments:
            - '@setting.manager'
            - '@my_service_container'
        tags:
            - { name: twig.extension }
    test.plugin.manage:
        class: Busybee\SystemBundle\Model\Test\TestPluginManage
        arguments:
            - '@my_service_container'
    my_service_container:
        class: Busybee\SystemBundle\Model\myContainer
        arguments:
            - '@service_container'
    test.plugin.installed:
        class: Busybee\SystemBundle\Model\Test\TestPluginInstalled
        arguments:
            - '@my_service_container'
    test.update.available:
        class: Busybee\SystemBundle\Model\Test\TestUpdateAvailable
        arguments:
            - '@my_service_container'
    system.SettingListType:
        class: Busybee\SystemBundle\Form\SettingListType
        arguments:
            - '@setting.manager'
        tags: 
            - { name: form.type }    
    system.SettingType:
        class: Busybee\SystemBundle\Form\SettingType
        arguments:
            - '@setting.repository'
        tags: 
            - { name: form.type }    
