services:
    monolog.formatter.session_request:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] [%%extra.token%%] %%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"
    monolog.processor.session_request:
        class: Busybee\SystemBundle\Model\SessionRequestProcessor
        arguments:  ["@session"]
        tags:
            - { name: monolog.processor, method: processRecord }
    monolog.logger.busybee:
        class: Busybee\SystemBundle\Model\BusybeeLogger 
        arguments: ['@logger']
        tags:
            - { name: monolog.logger, channel: busybee }
    doctrine.tblprefix_subscriber:
        class: Busybee\SystemBundle\Subscriber\TablePrefixSubscriber
        arguments: ['%database_prefix%']
        tags:
            - { name: doctrine.event_subscriber }    
