# System Bundle
parameters:
    version:
        system: '0.0.03'
        database: '0.0.03'
    settingPagination:
        alias: s
        sortBy:
            Name: 
                s.displayName: ASC
                s.description: ASC
            Description: 
                s.description: ASC
                s.displayName: ASC
        limit: '10'
        searchList:
            - s.displayName
            - s.description
        select:
            - s.displayName
            - s.description
            - s.id

services:
    monolog.formatter.session_request:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] [%%extra.token%%] %%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"
    monolog.processor.session_request:
        class: Busybee\SystemBundle\Model\SessionRequestProcessor
        arguments:  ["@session"]
        tags:
            - { name: monolog.processor, method: processRecord }
    monolog.logger.busybee:
        class: Busybee\SystemBundle\Model\BusybeeLogger 
        arguments: ['@logger']
        tags:
            - { name: monolog.logger, channel: busybee }
    doctrine.tblprefix_subscriber:
        class: Busybee\SystemBundle\Subscriber\TablePrefixSubscriber
        arguments: 
            - '%database_prefix%'
        tags:
            - { name: doctrine.event_subscriber }    
    system.setting.repository:
        class: Busybee\SystemBundle\Entity\SettingRepository
        factory: 
            - "@doctrine"
            - getRepository 
        arguments: 
            - "SystemBundle:Setting"
    setting.repository:
        class: Busybee\SystemBundle\Entity\SettingRepository
        factory: 
            - "@doctrine"
            - getRepository 
        arguments: 
            - "SystemBundle:Setting"
    system.update.manager:
        class: Busybee\SystemBundle\Update\UpdateManager
        arguments: 
            - "@service_container"
    system.password.manager:
        class: Busybee\SystemBundle\Password\PasswordManager
    busybee.writeDoctrine.listener:
        class: Busybee\SystemBundle\EventListener\WriteDoctrineListener
        arguments: 
            - "@service_container"
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }
    setting.manager:
        class: Busybee\SystemBundle\Setting\SettingManager
        arguments: 
            - "@service_container"
    setting.pagination:
        class: Busybee\SystemBundle\Model\SettingPagination
        arguments: 
            - '%settingPagination%'
            - '@setting.repository'
            - '@service_container'
    setting.extension:
        class: Busybee\SystemBundle\Model\SettingExtension
        arguments:
            - '@setting.manager'
            - '@service_container'
        tags:
            - { name: twig.extension }
