campus_manage:
    path:     /{id}/campus/
    defaults: { _controller: BusybeeInstituteBundle:Campus:index, id: Add }
campus_space_manage:
    path:     /campus/space/
    defaults: { _controller: BusybeeInstituteBundle:Campus:space }
campus_space_edit:
    path:     /campus/space/{id}/edit/
    defaults: { _controller: BusybeeInstituteBundle:Campus:editSpace }
department_edit:
    path:     /department/{id}/edit/
    defaults: { _controller: BusybeeInstituteBundle:Department:edit, id: 'Add' }
campus_space_duplicate:
    path:     /campus/space/duplicate/
    defaults: { _controller: BusybeeInstituteBundle:Campus:duplicateSpace }
