# InstituteBundle
parameters:
    spacePagination:
        alias: s
        sortBy:
            institute.space.sort:
                s.name: ASC
                c.name: ASC
            institute.campus.sort:
                c.name: ASC
                s.name: ASC
        searchList:
            - s.name
            - s.comment
            - c.name
        limit: '25'
        join:
            s.campus:
                type: leftJoin
                alias: c
        transDomain: BusybeeInstituteBundle
    InstituteBundle:
        version: 0.0.01
        settings:
            resources: 'BusybeeInstituteBundle/Resources/config/Settings/Settings_0_0_01.yml'
services:
    busybee_facility_institute.repository.campus_repository:
        class: Busybee\Facility\InstituteBundle\Repository\CampusRepository
        factory: 
            - "@doctrine"
            - getRepository 
        arguments: 
            - "BusybeeInstituteBundle:Campus"
    busybee_facility_institute.form.campus_type:
        class: Busybee\Facility\InstituteBundle\Form\CampusType
        arguments:
            - '@busybee_core_system.setting.setting_manager'
        tags: 
            - { name: form.type }    
    busybee_facility_institute.form.department_type:
        class: Busybee\Facility\InstituteBundle\Form\DepartmentType
        arguments:
            - '@busybee_core_system.setting.setting_manager'
            - '@doctrine.orm.default_entity_manager'
        tags:
            - { name: form.type }
    busybee_facility_institute.form.department_member_type:
        class: Busybee\Facility\InstituteBundle\Form\DepartmentMemberType
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@busybee_core_system.setting.setting_manager'
        tags:
            - { name: form.type }
    busybee_facility_institute.validator.constraints.institute_name_validator:
        class: Busybee\Facility\InstituteBundle\Validator\Constraints\InstituteNameValidator
        tags:
            - { name: validator.constraint_validator, alias: institute_name_validator }
    busybee_facility_institute.model.space_pagination:
        class: Busybee\Facility\InstituteBundle\Model\SpacePagination
        arguments:
            - '%spacePagination%'
            - '@busybee_facility_institute.repository.space_repository'
            - '@busybee_core_system.model.my_container'
    busybee_facility_institute.repository.space_repository:
        class: Busybee\Facility\InstituteBundle\Repository\SpaceRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeInstituteBundle:Space"
    busybee_facility_institute.repository.department_repository:
        class: Busybee\Facility\InstituteBundle\Repository\DepartmentRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeInstituteBundle:Department"
    busybee_facility_institute.events.department_member_subscriber:
        class: Busybee\Facility\InstituteBundle\Events\DepartmentMemberSubscriber
        tags:
            - { name: doctrine.event_subscriber }
    busybee_facility_institute.model.department_manager:
        class: Busybee\Facility\InstituteBundle\Model\DepartmentManager
        arguments:
            - '@doctrine.orm.default_entity_manager'
    busybee_facility_institute.form.space_type:
        class: Busybee\Facility\InstituteBundle\Form\SpaceType
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@busybee_core_system.setting.setting_manager'
        tags:
            - { name: form.type }
