# src\Busybee\DatabaseBundle\Resources\config\validation\Enumerator.orm.yml
Busybee\DatabaseBundle\Entity\Enumerator:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [name, value]
            errorPath: value
            message: 'The Enumerated name and value combination must be unique.'
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [name, prompt]
            errorPath: prompt
            message: 'The Enumerated name and prompt combination must be unique.'
    properties:
        name:
            - NotBlank: ~
        value:
            - NotBlank: ~
        prompt:
            - NotBlank: ~
