Busybee\People\PersonBundle\Entity\Person:
    constraints:
        - Busybee\People\PersonBundle\Validator\PersonName: ~
    properties:
        email:
            - Email:
                  checkMX: true
            - Busybee\People\PersonBundle\Validator\PersonEmail:
                errorPath: email
        email2:
            - Email:
                  checkMX: true
            - Busybee\People\PersonBundle\Validator\PersonEmail:
                errorPath: email2
        surname:
            - NotBlank: ~
        firstName:
            - NotBlank: ~
        officialName:
            - NotBlank: ~
        preferredName:
            - NotBlank: ~
        website:
            - Url: ~
        dob:
            - Date: ~
        gender:
            - \Busybee\Core\TemplateBundle\Validator\SettingChoice:
                name: 'Person.GenderList'
            - NotBlank: ~
        title:
            - \Busybee\Core\TemplateBundle\Validator\SettingChoice:
                name: 'Person.TitleList'
        photo:
            - \Busybee\People\PersonBundle\Validator\PersonImage: ~
        phone:
            - Valid: ~
        address1:
            - Valid: ~
        address2:
            - Valid: ~
        user:
            - Valid: ~
        student:
            - Valid: ~
        staff:
            - Valid: ~
        importIdentifier:
            - \Busybee\Core\TemplateBundle\Validator\UniqueOrBlank: ~