# Person
parameters:
    items:
        59:
            label: menu.timetable.title
            name: Timetable Menu
            role: ROLE_PRINCIPAL
            parameters: []
            node: 5
            order: 59
            menu: 59
        590:
            label: menu.timetable.manage
            name: Manage Timetable
            route: timetable_manage
            role: ROLE_PRINCIPAL
            parameters: []
            node: 59
            order: 590
        591:
            label: menu.timetable.activitygroups
            name: Manage Activity Groups
            route: activity_group_list
            role: ROLE_PRINCIPAL
            parameters: []
            node: 59
            order: 591
