# TimeTable
parameters:
    items:
        16:
            label: menu.timetable.title
            name: Timetable Menu
            role: ROLE_PRINCIPAL
            parameters: []
            node: 1
            order: 16
            menu: 16
        161:
            label: menu.student.activities.submenu
            name: Activity Menu
            role: ROLE_ADMIN
            node: 16
            order: 161
            menu: 161
        162:
            label: menu.timetable.title
            name: Manage Timetable
            role: ROLE_PRINCIPAL
            parameters: []
            node: 16
            order: 162
            menu: 162
        1610:
            label: menu.student.activities.manage
            name: Manage Activities
            role: ROLE_ADMIN
            node: 161
            order: 1610
            route: student_activities
        1611:
            label: menu.timetable.line
            name: Manage Activity Lines
            route: line_list
            role: ROLE_PRINCIPAL
            parameters: []
            node: 161
            order: 1611
        1620:
            label: menu.timetable.manage
            name: Manage Timetable
            route: timetable_manage
            role: ROLE_PRINCIPAL
            parameters: []
            node: 162
            order: 1620
        1621:
            label: menu.timetable.assigndays
            name: Assign TimeTable Days
            route: timetable_day_assignment
            role: ROLE_PRINCIPAL
            parameters: []
            node: 162
            order: 1621
