family_manage:
    path:     /manage/
    defaults: { _controller: BusybeeFamilyBundle:Family:index }
family_edit:
    path:     /{id}/edit/
    defaults: { _controller: BusybeeFamilyBundle:Family:edit }