# FamilyBundle
parameters:
   familyPagination:
        alias: f
        sortBy:
            Family Name:
                f.name: ASC
        limit: '10'
        searchList:
            - f.name
        select:
            - f.name
            - f.id
services:
    family.repository:
        class: Busybee\FamilyBundle\Repository\FamilyRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeFamilyBundle:Family"
    family.pagination:
        class: Busybee\FamilyBundle\Model\FamilyPagination
        arguments:
            - '%familyPagination%'
            - '@family.repository'
            - '@my_service_container'
    form.family.type:
        class: Busybee\FamilyBundle\Form\FamilyType
        arguments:
            - '@family.manager'
        tags:
            - { name: form.type }
    family.manager:
        class: Busybee\FamilyBundle\Model\FamilyManager
        arguments:
            - '@setting.manager'
            - '@doctrine.orm.entity_manager'
            - '@person.manager'
