# Institute
parameters:
    nodes: []
    items:
        140:
            label: menu.facility.manage
            name: Facility Management
            role: ROLE_REGISTRAR
            node: 14
            order: 140
            menu: 140
        1400:
            label: menu.campus.manage
            name: Campus Management
            role: ROLE_REGISTRAR
            node: 140
            order: 1400
            route: campus_manage
        1401:
            label: menu.campus.spaces
            name: Space Management
            role: ROLE_REGISTRAR
            node: 140
            order: 1401
            route: campus_space_manage
            translate: BusybeeInstituteBundle
        142:
            label: menu.department.manage
            name: Department Management
            role: ROLE_PRINCIPAL
            node: 14
            order: 142
            route: department_edit
            translate: BusybeeInstituteBundle
