# src\Busybee\Core\SecurityBundle\Resources\config\doctrine\Failure.orm.yml
Busybee\Core\SecurityBundle\Entity\Failure:
    type: entity
    table: failure
    repositoryClass: Busybee\Core\SecurityBundle\Repository\FailureRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        address:
            type: string
            length: 16
            unique: true
        failures:
            type: integer
        lastModified:
            type: datetime
            column: last_modified
        createdOn:
            type: datetime
            column: created_on
    manyToOne:
        createdBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
                    nullable: true
        modifiedBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
                    nullable: true
