campus_manage:
    path:     /campus/
    defaults: { _controller: BusybeeInstituteBundle:Campus:index }
calendar_years:
    path:     /years/
    defaults: { _controller: BusybeeInstituteBundle:Calendar:years }
year_edit:
    path:     /year/{id}/edit/
    defaults: { _controller: BusybeeInstituteBundle:Calendar:editYear }
year_delete:
    path:     /year/{id}/delete/
    defaults: { _controller: BusybeeInstituteBundle:Calendar:deleteYear }
