campus_manage:
    path:     /campus/
    defaults: { _controller: BusybeeInstituteBundle:Campus:index }
calendar_years:
    path:     /years/
    defaults: { _controller: BusybeeInstituteBundle:Calendar:years }
year_calendar:
    path:     /year/{id}/calendar/
    defaults: { _controller: BusybeeInstituteBundle:Calendar:calendar }
year_edit:
    path:     /year/{id}/edit/
    defaults: { _controller: BusybeeInstituteBundle:Calendar:editYear }
year_delete:
    path:     /year/{id}/delete/
    defaults: { _controller: BusybeeInstituteBundle:Calendar:deleteYear }
term_delete:
    path:     /term/{id}/{year}/delete/
    defaults: { _controller: BusybeeInstituteBundle:Calendar:deleteTerm }
specialday_delete:
    path:     /special_day/{id}/{year}/delete/
    defaults: { _controller: BusybeeInstituteBundle:Calendar:deleteSpecialDay }
