campus_manage:
    path:     /{id}/campus/
    defaults: { _controller: BusybeeInstituteBundle:Campus:index, id: Add }
calendar_years:
    path:     /years/
    defaults: { _controller: BusybeeInstituteBundle:Calendar:years }
year_calendar:
    path:     /year/{id}/calendar/
    defaults: { _controller: BusybeeInstituteBundle:Calendar:calendar }
year_edit:
    path:     /year/{id}/edit/
    defaults: { _controller: BusybeeInstituteBundle:Calendar:editYear }
calendar_print:
    path:     /year/{id}/print/
    defaults: { _controller: BusybeeInstituteBundle:Calendar:printCalendar }
year_delete:
    path:     /year/{id}/delete/
    defaults: { _controller: BusybeeInstituteBundle:Calendar:deleteYear }
term_delete:
    path:     /term/{id}/{year}/delete/
    defaults: { _controller: BusybeeInstituteBundle:Calendar:deleteTerm }
specialday_delete:
    path:     /special_day/{id}/{year}/delete/
    defaults: { _controller: BusybeeInstituteBundle:Calendar:deleteSpecialDay }
year_calendar_change:
    path:     /year/calendar/
    defaults: { _controller: BusybeeInstituteBundle:Calendar:calendarChange }
specialday_copy:
    path:     /special_day/{day}/{id}/copy/
    defaults: { _controller: BusybeeInstituteBundle:Calendar:copySpecialDay }
groups_years:
    path:     /groups/years/
    defaults: { _controller: BusybeeInstituteBundle:Groups:years }
student_year_edit:
    path:     /student/{id}/year/
    defaults: { _controller: BusybeeInstituteBundle:Year:edit }
campus_resource_manage:
    path:     /campus/resource/
    defaults: { _controller: BusybeeInstituteBundle:Campus:resource }
campus_resource_edit:
    path:     /campus/resource/{id}/edit/
    defaults: { _controller: BusybeeInstituteBundle:Campus:editResource }
home_room_manage:
    path:     /homeroom/manage/
    defaults: { _controller: BusybeeInstituteBundle:HomeRoom:index }
home_room_edit:
    path:     /homeroom/{id}/edit/
    defaults: { _controller: BusybeeInstituteBundle:HomeRoom:edit }
