# InstituteBundle
parameters:
    calendarStatus:
        calendar.status.past: past
        calendar.status.current: current
        calendar.status.future: future
services:
    campus.repository:
        class: Busybee\InstituteBundle\Entity\CampusRepository
        factory: 
            - "@doctrine"
            - getRepository 
        arguments: 
            - "BusybeeInstituteBundle:Campus"
    campus.form.campusType:
        class: Busybee\InstituteBundle\Form\CampusType
        arguments:
            - '@setting.manager'
        tags: 
            - { name: form.type }    
    institute.name.validator:
        class: Busybee\InstituteBundle\Validator\Constraints\InstituteNameValidator
        tags:
            - { name: validator.constraint_validator, alias: institute_name_validator }
    year.repository:
        class: Busybee\InstituteBundle\Repository\YearRepository
        factory: 
            - "@doctrine"
            - 'getRepository' 
        arguments: 
            - "BusybeeInstituteBundle:Year"
    term.repository:
        class: Busybee\InstituteBundle\Repository\TermRepository
        factory: 
            - "@doctrine"
            - 'getRepository' 
        arguments: 
            - "BusybeeInstituteBundle:Term"
    calendar.yearType:
        class: Busybee\InstituteBundle\Form\YearType
        arguments:
            - '%calendarStatus%'
        tags: 
            - { name: form.type }
    calendar.status.validator:
        class: Busybee\InstituteBundle\Validator\Constraints\CalendarStatusValidator
        arguments:
            - '@year.repository'
        tags:
            - { name: validator.constraint_validator, alias: calendar_status_validator }
    calendar.date.validator:
        class: Busybee\InstituteBundle\Validator\Constraints\CalendarDateValidator
        arguments:
            - "@year.repository"
        tags:
            - { name: validator.constraint_validator, alias: calendar_date_validator }
    term.date.validator:
        class: Busybee\InstituteBundle\Validator\Constraints\TermDateValidator
        tags:
            - { name: validator.constraint_validator, alias: term_date_validator }
    form.termType:
        class: Busybee\InstituteBundle\Form\TermType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags: 
            - { name: form.type }
    form.specialDayType:
        class: Busybee\InstituteBundle\Form\SpecialDayType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags: 
            - { name: form.type }
    specialDay.date.validator:
        class: Busybee\InstituteBundle\Validator\Constraints\SpecialDayDateValidator
        tags:
            - { name: validator.constraint_validator, alias: specialday_date_validator }
    specialDay.repository:
        class: Busybee\InstituteBundle\Repository\SpecialDayRepository
        factory: 
            - "@doctrine"
            - 'getRepository' 
        arguments: 
            - "BusybeeInstituteBundle:SpecialDay"
