# InstituteBundle
parameters:
    calendarStatus:
        calendar.status.past: past
        calendar.status.current: current
        calendar.status.future: future
    studentYearPagination:
        alias: s
        sortBy:
            Sequence:
                s.sequence: ASC
            Name:
                s.name: ASC
            Short Name:
                s.nameShort: ASC
        limit: '25'
        searchList:
            - s.name
            - s.nameShort
    campusResourcePagination:
        alias: r
        sortBy:
            Name:
                r.name: ASC
        limit: '25'
        searchList:
            - r.name
            - r.comment
    HomeRoomPagination:
        alias: h
        sortBy:
            Name:
                h.name: ASC
                y.name: ASC
            Short Name:
                h.nameShort: ASC
                y.name: ASC
            Room:
                r.name: ASC
                y.name: ASC
                h.name: ASC
            Year:
                y.name: ASC
                h.name: ASC
        join:
            h.schoolYear:
                alias: y
                type: leftJoin
            h.campusResource:
                alias: r
                type: leftJoin
        limit: '25'
        searchList:
            - h.name
            - h.nameShort
            - y.name
            - r.name
        select:
            - h.name
            - h.id
            - h.nameShort
            - y.name as year
            - r.name as room
services:
    campus.repository:
        class: Busybee\InstituteBundle\Repository\CampusRepository
        factory: 
            - "@doctrine"
            - getRepository 
        arguments: 
            - "BusybeeInstituteBundle:Campus"
    campus.form.campusType:
        class: Busybee\InstituteBundle\Form\CampusType
        arguments:
            - '@setting.manager'
        tags: 
            - { name: form.type }    
    institute.name.validator:
        class: Busybee\InstituteBundle\Validator\Constraints\InstituteNameValidator
        tags:
            - { name: validator.constraint_validator, alias: institute_name_validator }
    year.repository:
        class: Busybee\InstituteBundle\Repository\YearRepository
        factory: 
            - "@doctrine"
            - 'getRepository' 
        arguments: 
            - "BusybeeInstituteBundle:Year"
    term.repository:
        class: Busybee\InstituteBundle\Repository\TermRepository
        factory: 
            - "@doctrine"
            - 'getRepository' 
        arguments: 
            - "BusybeeInstituteBundle:Term"
    calendar.yearType:
        class: Busybee\InstituteBundle\Form\YearType
        arguments:
            - '%calendarStatus%'
        tags: 
            - { name: form.type }
    calendar.status.validator:
        class: Busybee\InstituteBundle\Validator\Constraints\CalendarStatusValidator
        arguments:
            - '@year.repository'
        tags:
            - { name: validator.constraint_validator, alias: calendar_status_validator }
    calendar.date.validator:
        class: Busybee\InstituteBundle\Validator\Constraints\CalendarDateValidator
        arguments:
            - "@year.repository"
        tags:
            - { name: validator.constraint_validator, alias: calendar_date_validator }
    term.date.validator:
        class: Busybee\InstituteBundle\Validator\Constraints\TermDateValidator
        tags:
            - { name: validator.constraint_validator, alias: term_date_validator }
    form.termType:
        class: Busybee\InstituteBundle\Form\TermType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags: 
            - { name: form.type }
    form.specialDayType:
        class: Busybee\InstituteBundle\Form\SpecialDayType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags: 
            - { name: form.type }
    specialDay.date.validator:
        class: Busybee\InstituteBundle\Validator\Constraints\SpecialDayDateValidator
        tags:
            - { name: validator.constraint_validator, alias: specialday_date_validator }
    specialDay.repository:
        class: Busybee\InstituteBundle\Repository\SpecialDayRepository
        factory: 
            - "@doctrine"
            - 'getRepository' 
        arguments: 
            - "BusybeeInstituteBundle:SpecialDay"
    calendar.widget:
        class: Busybee\InstituteBundle\Service\WidgetService
        arguments:
            - '@setting.manager'
    calendar.manager:
        class: Busybee\InstituteBundle\Model\CalendarManager
        arguments:
            - '@setting.manager'
            - '@year.repository'
            - '@doctrine.orm.entity_manager'
    calendar.extension:
        class: Busybee\InstituteBundle\Model\CalendarExtension
        arguments:
            - '@setting.manager'
            - '@calendar.manager'
            - '@my_service_container'
        tags:
            - { name: twig.extension }
    studentYear.pagination:
        class: Busybee\InstituteBundle\Model\StudentYearPagination
        arguments:
            - '%studentYearPagination%'
            - '@studentYear.repository'
            - '@my_service_container'
    studentYear.repository:
        class: Busybee\InstituteBundle\Repository\StudentYearRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeInstituteBundle:StudentYear"
    campusResource.pagination:
        class: Busybee\InstituteBundle\Model\StudentYearPagination
        arguments:
            - '%campusResourcePagination%'
            - '@campusResource.repository'
            - '@my_service_container'
    campusResource.repository:
        class: Busybee\InstituteBundle\Repository\CampusResourceRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeInstituteBundle:CampusResource"
    HomeRoom.repository:
        class: Busybee\InstituteBundle\Repository\HomeRoomRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeInstituteBundle:HomeRoom"
    form.CampusResourceType:
        class: Busybee\InstituteBundle\Form\CampusResourceType
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@setting.manager'
        tags:
            - { name: form.type }
    HomeRoom.pagination:
        class: Busybee\InstituteBundle\Model\HomeRoomPagination
        arguments:
            - '%HomeRoomPagination%'
            - '@HomeRoom.repository'
            - '@my_service_container'
    form.HomeRoomType:
        class: Busybee\InstituteBundle\Form\HomeRoomType
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@setting.manager'
        tags:
            - { name: form.type }
