Busybee\StaffBundle\Entity\Staff:
    type: entity
    table: staff
    repositoryClass: Busybee\StaffBundle\Repository\StaffRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        staffType:
            type: string
            length: '20'
            name: staff_type
        jobTitle:
            type: string
            length: '100'
        house:
            type: string
            length: 32
            nullable: true
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    oneToOne:
        person:
            targetEntity: Busybee\People\PersonBundle\Entity\Person
            inversedBy: staff
        homeroom:
            targetEntity: Busybee\InstituteBundle\Entity\Space
            mappedBy: staff
            cascade: [ all ]
    oneToMany:
        department:
            targetEntity: Busybee\InstituteBundle\Entity\DepartmentStaff
            mappedBy: staff
            cascade: [ all ]
    manyToOne:
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
