Busybee\StaffBundle\Entity\Staff:
    type: entity
    table: staff
    repositoryClass: Busybee\StaffBundle\Repository\StaffRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        staffType:
            type: string
            length: '20'
            name: staff_type
        jobTitle:
            type: string
            length: '100'
        house:
            type: string
            length: 32
            nullable: true
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    manyToMany:
        department:
            targetEntity: Busybee\InstituteBundle\Entity\Department
            inversedBy: staff
            cascade: [ all ]
            joinTable:
                name: department_staff
                joinColumns:
                    staff_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    dept_id:
                        referencedColumnName: id
    manyToOne:
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
    oneToOne:
        person:
            targetEntity: Busybee\PersonBundle\Entity\Person
            inversedBy: staff
