home_page:
    path:     /
    defaults: { _controller: BusybeeHomeBundle:Default:index }
error_page:
    path:     /error/{exception}/{logger}
    defaults: { _controller: BusybeeTemplateBundle:Error:index }
home_template:
    path:     /template
    defaults: { _controller: BusybeeHomeBundle:Template:index }
acknowledgement:
    path:     /acknowledgement
    defaults: { _controller: BusybeeHomeBundle:Default:acknowledgement }
download_file:
    path:     /download/{file}/{role}/
    defaults: { _controller: BusybeeHomeBundle:Default:downloadFile, role: 'ROLE_SYSTEM_ADMIN' }
