parameters:
    Home:
        version: 0.0.01
        settings:
            resources:
                - 'BusybeeHomeBundle/Resources/config/Settings/settings_0_0_01.yml'
services:
    menu.manager:
        class: Busybee\Core\HomeBundle\Model\MenuManager
        arguments:
            - '@my_service_container'
    math.extension:
        class: Busybee\Core\HomeBundle\Model\MathExtension
        tags:
            - { name: twig.extension }
    hide.section:
        class: Busybee\Core\HomeBundle\Model\HideSection
        arguments:
            - '@session'
            - '@request_stack'
    busybee_home.kernel.listener:
        class: Busybee\Core\HomeBundle\Listener\KernelListener
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@router'
            - '%kernel.cache_dir%'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
