parameters:
    Home:
        version: 0.0.01
        settings:
            resources:
                - 'BusybeeHomeBundle/Resources/config/Settings/settings_0_0_01.yml'
services:
    menu.manager:
        class: Busybee\Core\HomeBundle\Model\MenuManager
        arguments:
            - '@service_container'
    math.extension:
        class: Busybee\Core\HomeBundle\Model\MathExtension
        tags:
            - { name: twig.extension }
    session.extension:
        class: Busybee\Core\HomeBundle\Model\SessionExtension
        arguments:
            - '@session'
        tags:
            - { name: twig.extension }
    hide.section:
        class: Busybee\Core\HomeBundle\Model\HideSection
        arguments:
            - '@session'
            - '@request_stack'
    flash.extension:
        class: Busybee\Core\HomeBundle\Model\FlashExtension
        tags:
            - { name: twig.extension }
