parameters:
    HomeBundle:
        version: 0.0.01
        settings:
            resources:
                - 'BusybeeHomeBundle/Resources/config/Settings/settings_0_0_01.yml'
services:
    busybee_core_home.model.menu_manager:
        class: Busybee\Core\HomeBundle\Model\MenuManager
        arguments:
            - '@busybee_core_system.model.my_container'
    busybee_core_home.extension.math_extension:
        class: Busybee\Core\HomeBundle\Extension\MathExtension
        tags:
            - { name: twig.extension }
    busybee_core_home.model.hide_section:
        class: Busybee\Core\HomeBundle\Model\HideSection
        arguments:
            - '@session'
            - '@request_stack'
    busybee_core_home.listener.kernel_listener:
        class: Busybee\Core\HomeBundle\Listener\KernelListener
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@router'
            - '@busybee_core_system.model.flash_bag_manager'
            - '%kernel.cache_dir%'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
