# src\    Busybee\DatabaseBundle\Resources\config\doctrine\Form.orm.yml
Busybee\DatabaseBundle\Entity\Form:
    type: entity
    table: db_forms
    repositoryClass: Busybee\DatabaseBundle\Entity\FormRepository
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [name]
            errorPath: name
            message: 'The Form Name must be unique.'
    indexes:
        name:
            columns: [ name ] 
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 64
            unique: true
    manyToMany:
        role:
            targetEntity: Busybee\SecurityBundle\Entity\Role
            orderBy: { 'role': 'ASC' }
            joinTable: 
                name: db_form_role
                joinColumns:
                    form_id:
                        referencedColumnName: id
                        unique: true 
                inverseJoinColumns:
                    role_id:
                        referencedColumnName: id            
