Busybee\People\StaffBundle\Entity\Staff:
    type: entity
    repositoryClass: Busybee\People\StaffBundle\Repository\StaffRepository
    fields:
        staffType:
            type: string
            length: '20'
            name: staff_type
        jobTitle:
            type: string
            length: '100'
        house:
            type: string
            length: 32
            nullable: true
#    oneToOne:
#        homeroom:
#            targetEntity: Busybee\Facility\InstituteBundle\Entity\Space
#            mappedBy: staff
#            cascade: [ all ]
#    oneToMany:
#        department:
#            targetEntity: Busybee\Facility\InstituteBundle\Entity\DepartmentStaff
#            mappedBy: staff
#            cascade: [ all ]
