locality_fetch:
    path:     /fetch/
    defaults: { _controller: BusybeeLocalityBundle:Locality:fetch }
locality_manage:
    path:     /{id}/manage/
    defaults: { _controller: BusybeeLocalityBundle:Locality:index }
