services:
    busybee_people_locality.repository.locality_repository:
        class: Busybee\People\LocalityBundle\Repository\LocalityRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeLocalityBundle:Locality"
    busybee_people_locality.model.locality_manager:
        class: Busybee\People\LocalityBundle\Model\LocalityManager
        arguments:
            - '@doctrine.orm.default_entity_manager'

