parameters:
    LocalityBundle:
        version: 0.0.01
        settings:
            resources:
                - 'BusybeeLocalityBundle/Resources/config/Settings/Settings_0_0_01.yml'
services:
    busybee_people_locality.repository.locality_repository:
        class: Busybee\People\LocalityBundle\Repository\LocalityRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeLocalityBundle:Locality"
    busybee_people_locality.model.locality_manager:
        class: Busybee\People\LocalityBundle\Model\LocalityManager
        arguments:
            - '@doctrine.orm.default_entity_manager'
    busybee_people_locality.validator.constraints.locality_validator:
        class: Busybee\People\LocalityBundle\Validator\Constraints\LocalityValidator
        arguments:
            - "@busybee_core_system.setting.setting_manager"
        tags:
            - { name: validator.constraint_validator, alias: locality_validator }

