Busybee\TimeTableBundle\Entity\Column:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name, timetable]
            errorPath: name
            message: 'column.timetable.name.unique'
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [nameShort, timetable]
            errorPath: nameShort
            message: 'column.timetable.nameshort.unique'
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [sequence, timetable]
            errorPath: name
            message: 'column.timetable.sequence.unique'
    properties:
        timetable:
            - Valid: ~
            - NotBlank: ~
        name:
            - NotBlank: ~
        nameShort:
            - NotBlank: ~
            - Busybee\Core\TemplateBundle\Validator\NoWhiteSpace: ~
        periods:
            - Valid: ~
        sequence:
            - NotBlank: ~
            - Range:
                min: 1
                max: 999
