Busybee\TimeTableBundle\Entity\Line:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name, year]
            errorPath: name
            message: 'line.error.nameyear'
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name, year]
            errorPath: name
            message: 'line.error.nameshortyear'
    properties:
        name:
            - NotBlank: ~
        nameShort:
            - NotBlank: ~
        year:
            - Valid: ~
            - NotBlank: ~
        course:
            - Valid: ~
