Busybee\TimeTableBundle\Entity\Line:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name, year]
            errorPath: name
            message: 'line.nameyear.unique'
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [nameShort, year]
            errorPath: nameShort
            message: 'line.nameshortyear.unique'
    properties:
        name:
            - NotBlank: ~
        nameShort:
            - NotBlank: ~
            - Busybee\FormBundle\Validator\NoWhiteSpace: ~
        year:
            - Valid: ~
            - NotBlank: ~
        course:
            - Valid: ~
