Busybee\TimeTableBundle\Entity\Period:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name, column]
            errorPath: name
            message: 'timetable.column.name.unique'
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [nameShort, column]
            errorPath: nameShort
            message: 'timetable.column.nameShort.unique'
        - Callback: [ Busybee\TimeTableBundle\Validator\PeriodActivity, validate ]
    properties:
        column:
            - Valid: ~
            - NotBlank: ~
        name:
            - NotBlank: ~
        nameShort:
            - NotBlank: ~
            - Length:
                max: 3