Busybee\TimeTableBundle\Entity\TimeTable:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name, year]
            errorPath: name
            message: 'timetable.unique.year'
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [nameShort, year]
            errorPath: nameShort
            message: 'timetable.unique.year'
    properties:
        year:
            - Valid: ~
            - NotBlank: ~
        name:
            - NotBlank: ~
        nameShort:
            - NotBlank: ~
        columns:
            - Valid: ~
        days:
            - Valid: ~