Busybee\People\ContactBundle\Entity\Contact:
    type: entity
    repositoryClass: Busybee\People\ContactBundle\Repository\ContactRepository
    fields:
        jobTitle:
            type: string
            length: '100'
        profession:
            type: string
            length: 32
            nullable: true
        employer:
            type: string
            length: '32'
            nullable: true
