parameters:
    PhoneBundle:
        version: 0.0.01
        settings:
            resources:
                - 'BusybeePhoneBundle/Resources/config/Settings/Settings_0_0_01.yml'

services:
    busybee_people_phone.model.phone_manager:
        class: Busybee\People\PhoneBundle\Model\PhoneManager
        arguments:
            - '@translator'
            - '@busybee_core_system.setting.setting_manager'
            - '@busybee_people_phone.repository.phone_repository'
    busybee_people_phone.repository.phone_repository:
        class: Busybee\People\PhoneBundle\Repository\PhoneRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeePhoneBundle:Phone"
    busybee_people_phone.form.phone_type:
        class: Busybee\People\PhoneBundle\Form\PhoneType
        arguments:
            - '@busybee_core_system.setting.setting_manager'
            - '@busybee_people_phone.repository.phone_repository'
        tags:
            - { name: form.type }
    busybee_people_phone.validator.constraints.phone_validator:
        class: Busybee\People\PhoneBundle\Validator\Constraints\PhoneValidator
        arguments:
            - '@busybee_core_system.setting.setting_manager'
        tags:
            - { name: validator.constraint_validator, alias: phone_validator }
