parameters:
    CalendarBundle:
        version: 0.0.01
        settings:
            resources:
                - 'BusybeeCalendarBundle/Resources/config/Settings/Settings_0_0_01.yml'
    calendarStatus:
        calendar.status.past: past
        calendar.status.current: current
        calendar.status.future: future
    gradePagination:
        alias: g
        sortBy:
            grade.sequence.sort:
                g.sequence: ASC
            grade.name.sort:
                g.name: ASC
                g.grade: ASC
        limit: '25'
        searchList:
            - g.name
            - g.grade
        select:
            - g.name
            - g.grade
        join:
            g.year:
                type: leftJoin
                alias: y
        transDomain: BusybeeCalendarBundle

services:
    busybee_core_calendar.model.current_year:
        class: Busybee\Core\CalendarBundle\Model\CurrentYear
        arguments:
            - '@busybee_core_security.doctrine.user_manager'
            - '@security.token_storage'
            - '@busybee_core_calendar.repository.year_repository'
    busybee_core_calendar.model.get_current_year:
        class: Busybee\Core\CalendarBundle\Model\CurrentYear
        factory:
            - '@busybee_core_calendar.model.current_year'
            - 'getCurrentYear'
    busybee_core_calendar.model.year_manager:
        class: Busybee\Core\CalendarBundle\Model\YearManager
        arguments:
            - '@doctrine.orm.entity_manager'
    busybee_core_calendar.repository.year_repository:
        class: Busybee\Core\CalendarBundle\Repository\YearRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeCalendarBundle:Year"
    busybee_core_calendar.repository.term_repository:
        class: Busybee\Core\CalendarBundle\Repository\TermRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeCalendarBundle:Term"
    busybee_core_calendar.form.year_type:
        class: Busybee\Core\CalendarBundle\Form\YearType
        arguments:
            - '%calendarStatus%'
            - '@busybee_core_calendar.model.year_manager'
        tags:
            - { name: form.type }
    busybee_core_calendar.validator.constraints.calendar_status_validator:
        class: Busybee\Core\CalendarBundle\Validator\Constraints\CalendarStatusValidator
        arguments:
            - '@busybee_core_calendar.repository.year_repository'
        tags:
            - { name: validator.constraint_validator, alias: calendar_status_validator }
    busybee_core_calendar.validator.constraints.calendar_date_validator:
        class: Busybee\Core\CalendarBundle\Validator\Constraints\CalendarDateValidator
        arguments:
            - "@busybee_core_calendar.repository.year_repository"
        tags:
            - { name: validator.constraint_validator, alias: calendar_date_validator }
    busybee_core_calendar.validator.constraints.term_date_validator:
        class: Busybee\Core\CalendarBundle\Validator\Constraints\TermDateValidator
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: validator.constraint_validator, alias: term_date_validator }
    busybee_core_calendar.form.term_type:
        class: Busybee\Core\CalendarBundle\Form\TermType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
    busybee_core_calendar.form.special_day_type:
        class: Busybee\Core\CalendarBundle\Form\SpecialDayType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
    busybee_core_calendar.validator.constraints.special_day_date_validator:
        class: Busybee\Core\CalendarBundle\Validator\Constraints\SpecialDayDateValidator
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: validator.constraint_validator, alias: specialday_date_validator }
    busybee_core_calendar.repository.special_day_repository:
        class: Busybee\Core\CalendarBundle\Repository\SpecialDayRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeCalendarBundle:SpecialDay"
    busybee_core_calendar.service.widget_service:
        class: Busybee\Core\CalendarBundle\Service\WidgetService
        arguments:
            - '@busybee_core_system.setting.setting_manager'
    busybee_core_calendar.model.calendar_manager:
        class: Busybee\Core\CalendarBundle\Model\CalendarManager
        arguments:
            - '@busybee_core_system.setting.setting_manager'
            - '@doctrine.orm.entity_manager'
    busybee_core_calendar.extension.calendar_extension:
        class: Busybee\Core\CalendarBundle\Extension\CalendarExtension
        arguments:
            - '@busybee_core_system.setting.setting_manager'
            - '@busybee_core_calendar.model.calendar_manager'
            - '@busybee_core_system.model.my_container'
        tags:
            - { name: twig.extension }
    busybee_core_calendar.repository.grade_repository:
        class: Busybee\Core\CalendarBundle\Repository\GradeRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeCalendarBundle:Grade"
    busybee_core_calendar.form.grade_type:
        class: Busybee\Core\CalendarBundle\Form\GradeType
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@busybee_core_system.setting.setting_manager'
            - '@busybee_core_calendar.model.grade_manager'
        tags:
            - { name: form.type }
    busybee_core_calendar.validator.constraints.grade_validator:
        class: Busybee\Core\CalendarBundle\Validator\Constraints\GradeValidator
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: validator.constraint_validator, alias: calendar_grade_validator }
    busybee_core_calendar.model.grade_manager:
        class: Busybee\Core\CalendarBundle\Model\GradeManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@busybee_core_calendar.model.get_current_year'
    busybee_core_calendar.service.widget_service.calendar:
        class: Busybee\Core\CalendarBundle\Service\WidgetService\Calendar
        arguments:
            - '@busybee_core_system.setting.setting_manager'
    busybee_core_calendar.pagination.grade_pagination:
        class: Busybee\Core\CalendarBundle\Pagination\GradePagination
        arguments:
            - '%gradePagination%'
            - '@busybee_core_calendar.repository.grade_repository'
            - '@busybee_core_system.model.my_container'