Busybee\StudentBundle\Entity\Activity:
    type: entity
    table: activity
    repositoryClass: Busybee\StudentBundle\Repository\ActivityRepository
    uniqueConstraints:
        name_year:
            columns: [name, year]
        nameshort_year:
            columns: [nameShort, year]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
        nameShort:
            type: string
            length: '8'
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    oneToMany:
        periods:
            targetEntity: Busybee\TimeTableBundle\Entity\PeriodActivity
            mappedBy: activity
    manyToMany:
        grades:
            targetEntity: Busybee\InstituteBundle\Entity\Grade
            inversedBy: activities
            cascade: [ 'all' ]
            joinTable:
                name: activity_grade
                joinColumns:
                    activity_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    grade_id:
                        referencedColumnName: id
        students:
            targetEntity: Busybee\StudentBundle\Entity\Student
            inversedBy: activities
            joinTable:
                name: activity_students
                joinColumns:
                    activity_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    student_id:
                        referencedColumnName: id
    manyToOne:
        space:
            targetEntity: Busybee\InstituteBundle\Entity\Space
            joinColumns:
                space:
                    referencedColumnName: id
        year:
            targetEntity: Busybee\InstituteBundle\Entity\Year
            orderBy: {'firstDay': 'DESC'}
            joinColumns:
                year:
                    referencedColumnName: id
        tutor1:
            targetEntity: Busybee\StaffBundle\Entity\Staff
            joinColumns:
                tutor_1:
                    referencedColumnName: id
        tutor2:
            targetEntity: Busybee\StaffBundle\Entity\Staff
            joinColumns:
                tutor_2:
                    referencedColumnName: id
        tutor3:
            targetEntity: Busybee\StaffBundle\Entity\Staff
            joinColumns:
                tutor_3:
                    referencedColumnName: id
        studentReference:
            targetEntity: Busybee\StudentBundle\Entity\Activity
            joinColumns:
                student_reference_id:
                    referencedColumnName: id
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
