Busybee\StudentBundle\Entity\Enrolment:
    type: entity
    table: enrolment
    repositoryClass: Busybee\StudentBundle\Repository\EnrolmentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        status:
            type: string
            length: '32'
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    manyToOne:
        year:
            targetEntity: Busybee\InstituteBundle\Entity\Year
            joinColumns:
                year:
                    referencedColumnName: id
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
    manyToMany:
        students:
            targetEntity: Busybee\StudentBundle\Entity\Student
            mappedBy: enrolments