Busybee\StudentBundle\Entity\StudentGrade:
    type: entity
    table: student_grade
    repositoryClass: Busybee\StudentBundle\Repository\StudentGradeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        status:
            type: string
            length: '32'
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    manyToOne:
        student:
            targetEntity: Busybee\StudentBundle\Entity\Student
            inversedBy: grades
            joinColumns:
                student_id:
                    referencedColumnName: id
        grade:
            targetEntity: Busybee\Core\CalendarBundle\Entity\Grade
            inversedBy: students
            joinColumns:
                grade_id:
                    referencedColumnName: id
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
