Busybee\StudentBundle\Entity\Student:
    type: entity
    table: student
    repositoryClass: Busybee\StudentBundle\Repository\StudentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        startAtSchool:
            type: date
        startAtThisSchool:
            type: date
        lastAtThisSchool:
            type: date
            nullable: true
        locker:
            length: 16
            nullable: true
        firstLanguage:
            type: string
            length: 16
            nullable: true
        secondLanguage:
            type: string
            length: 16
            nullable: true
        thirdLanguage:
            type: string
            length: 16
            nullable: true
        countryOfBirth:
            type: string
            length: 16
            nullable: true
        birthCertificateScan:
            type: string
            length: '150'
            nullable: true
        ethnicity:
            type: string
            length: 32
            nullable: true
        citizenship1:
            type: string
            length: 16
            nullable: true
        citizenship1Passport:
            type: string
            length: 16
            nullable: true
        citizenship1PassportScan:
            type: string
            length: '150'
            nullable: true
        citizenship2:
            type: string
            length: 16
            nullable: true
        citizenship2Passport:
            type: string
            length: 16
            nullable: true
        religion:
            type: string
            length: 16
            nullable: true
        nationalIDCardNumber:
            type: string
            length: 32
            nullable: true
        nationalIDCardScan:
            type: string
            length: '150'
            nullable: true
        residencyStatus:
            type: string
            length: 32
            nullable: true
        visaExpiryDate:
            type: datetime
            nullable: true
        house:
            type: string
            length: 32
            nullable: true
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    oneToOne:
        person:
            targetEntity: Busybee\People\PersonBundle\Entity\Person
            inversedBy: student
    oneToMany:
        grades:
            targetEntity: Busybee\StudentBundle\Entity\StudentGrade
            mappedBy: student
            cascade: [ 'all' ]
    manyToOne:
        createdBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
    manyToMany:
        activities:
            targetEntity: Busybee\ActivityBundle\Entity\Activity
            mappedBy: students