person_toggle_staff:
    path:     /person/{id}/toggle/
    defaults: { _controller: BusybeeStaffBundle:Staff:toggle }
staff_manage:
    path:     /manage/
    defaults: { _controller: BusybeeStaffBundle:Staff:list }
