parameters:
    staffPagination:
        alias: s
        sortBy:
            person.surname.label:
                s.surname: ASC
                s.firstName: ASC
            person.firstname.label:
                s.firstName: ASC
                s.surname: ASC
            person.email.label:
                s.email: ASC
                s.surname: ASC
                s.firstName: ASC
        limit: '25'
        searchList:
            - s.surname
            - s.firstName
            - s.email
        join:
            s.phone:
                type: leftJoin
                alias: p
            s.user:
                type: leftJoin
                alias: u
        select:
            - s.id
            - s.surname
            - s.firstName
            - u.id as user_id
        choices:
            all:
                route: person_manage
                prompt: person.pagination.all
            student:
                route: student_manage
                prompt: person.pagination.student
            staff:
                route: staff_manage
                prompt: person.pagination.staff
            contact:
                route: contact_manage
                prompt: person.pagination.contact
            user:
                route: user_manage
                prompt: person.pagination.user
        transDomain: BusybeePersonBundle
    StaffBundle:
        version: 0.0.01
        settings:
            resources: 'BusybeeStaffBundle/Resources/config/Settings/Settings_0_0_01.yml'
services:
    busybee_people_staff.repository.staff_repository:
        class: Busybee\People\StaffBundle\Repository\StaffRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeStaffBundle:Staff"
    busybee_people_staff.form.staff_type:
        class: Busybee\People\StaffBundle\Form\StaffType
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@busybee_core_system.setting.setting_manager'
        tags:
            - { name: form.type }
    busybee_people_staff.model.staff_pagination:
        class: Busybee\People\StaffBundle\Model\StaffPagination
        arguments:
            - '%staffPagination%'
            - '@busybee_people_staff.repository.staff_repository'
            - '@busybee_core_system.model.my_container'
    busybee_people_staff.security.grade_voter:
        class: Busybee\People\StaffBundle\Security\GradeVoter
        arguments:
            - '@security.access.decision_manager'
            - '@busybee_people_person.model.person_manager'
        tags:
            - { name: security.voter, priority: 250 }
        public: false
    busybee_people_staff.security.student_voter:
        class: Busybee\People\StaffBundle\Security\StudentVoter
        arguments:
            - '@security.access.decision_manager'
            - '@busybee_people_person.model.person_manager'
        tags:
            - { name: security.voter, priority: 250 }
        public: false
    busybee_people_staff.security.staff_voter:
        class: Busybee\People\StaffBundle\Security\StaffVoter
        arguments:
            - '@security.access.decision_manager'
            - '@busybee_people_person.model.person_manager'
        tags:
            - { name: security.voter, priority: 250 }
        public: false
