parameters:
    staffPagination:
        alias: s
        sortBy:
            Family Name:
                p.surname: ASC
                p.firstName: ASC
            Given Name:
                p.firstName: ASC
                p.surname: ASC
            Email:
                p.email: ASC
                p.surname: ASC
                p.firstName: ASC
        limit: '25'
        searchList:
            - p.surname
            - p.firstName
            - p.email
        join:
            s.person:
                type: leftJoin
                alias: p
            p.user:
                type: leftJoin
                alias: u
            p.student:
                type: leftJoin
                alias: stu
        select:
            - p.id
            - p.surname
            - p.firstName
            - p.title as details
            - s.id as staff_id
            - stu.id as stu_id
            - u.id as user_id
        choices:
            all:
                route: person_manage
                prompt: pagination.person.all
            student:
                route: student_manage
                prompt: pagination.person.student
            staff:
                route: staff_manage
                prompt: pagination.person.staff
            contact:
                route: contact_manage
                prompt: pagination.person.contact
    StaffBundle:
        version: 0.0.01
        settings:
            resources: 'BusybeeStaffBundle/Resources/config/Settings/Settings_0_0_01.yml'
services:
    busybee_people_staff.repository.staff_repository:
        class: Busybee\People\StaffBundle\Repository\StaffRepository
        factory:
            - "@doctrine"
            - 'getRepository'
        arguments:
            - "BusybeeStaffBundle:Staff"
    busybee_people_staff.form.staff_type:
        class: Busybee\People\StaffBundle\Form\StaffType
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@busybee_core_system.setting.setting_manager'
        tags:
            - { name: form.type }
    busybee_people_staff.model.staff_pagination:
        class: Busybee\People\StaffBundle\Model\StaffPagination
        arguments:
            - '%staffPagination%'
            - '@busybee_people_staff.repository.staff_repository'
            - '@busybee_core_system.model.my_container'
    busybee_people_staff.security.grade_voter:
        class: Busybee\People\StaffBundle\Security\GradeVoter
        arguments:
            - '@security.access.decision_manager'
            - '@busybee_people_person.model.person_manager'
        tags:
            - { name: security.voter, priority: 250 }
        public: false
    busybee_people_staff.security.student_voter:
        class: Busybee\People\StaffBundle\Security\StudentVoter
        arguments:
            - '@security.access.decision_manager'
            - '@busybee_people_person.model.person_manager'
        tags:
            - { name: security.voter, priority: 250 }
        public: false
    busybee_people_staff.security.staff_voter:
        class: Busybee\People\StaffBundle\Security\StaffVoter
        arguments:
            - '@security.access.decision_manager'
            - '@busybee_people_person.model.person_manager'
        tags:
            - { name: security.voter, priority: 250 }
        public: false
