Busybee\Facility\InstituteBundle\Entity\Department:
    type: entity
    table: department
    repositoryClass: Busybee\Facility\InstituteBundle\Repository\DepartmentRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '30'
            unique: true
        type:
            type: string
            length: '20'
        nameShort:
            type: string
            length: '4'
            unique: true
        importIdentifier:
            type: string
            length: '12'
            nullable: true
        blurb:
            type: text
            nullable: true
        logo:
            type: string
            length: 150
            nullable: true
        lastModified:
            type: datetime
            column: last_modified
        createdOn:
            type: datetime
            column: created_on
    oneToMany:
        members:
            targetEntity: Busybee\Facility\InstituteBundle\Entity\DepartmentMember
            mappedBy: department
            cascade: [ all ]
#    manyToMany:
#        courses:
#            targetEntity: Busybee\Program\CurriculumBundle\Entity\Course
#            joinTable:
#                name: department_course
#                joinColumns:
#                    dept_id:
#                        referencedColumnName: id
#                inverseJoinColumns:
#                    course_id:
#                        referencedColumnName: id
#                        unique: true
    manyToOne:
        createdBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
