Busybee\Facility\InstituteBundle\Entity\DepartmentMember:
    type: entity
    table: department_member
    repositoryClass: Busybee\Facility\InstituteBundle\Repository\DepartmentMemberRepository
    uniqueConstraints:
        dept_staff:
            columns: [ dept_id, staff_id ]
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        staffType:
            type: string
            length: '32'
            name: staff_type
        lastModified:
            type: datetime
            column: last_modified
        createdOn:
            type: datetime
            column: created_on
    manyToOne:
        department:
            targetEntity: Busybee\Facility\InstituteBundle\Entity\Department
            inversedBy: members
            joinColumn:
                name: dept_id
                referencedColumnName: id
        staff:
            targetEntity: Busybee\People\StaffBundle\Entity\Staff
            inversedBy: members
            joinColumn:
                name: staff_id
                referencedColumnName: id
                nullable: false
        createdBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
