Busybee\InstituteBundle\Entity\CampusResource:
    type: entity
    table: campus_resource
    repositoryClass: Busybee\InstituteBundle\Repository\CampusResourceRepository
    uniqueConstraints:
        name_campus:
            columns: [ name, campus ]
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '30'
        type:
            type: string
            length: '20'
        capacity:
            type: integer
            length: '5'
            nullable: true
        computer:
            type: boolean
        studentComputers:
            type: integer
            length: '3'
            nullable: true
        projector:
            type: boolean
        tv:
            type: boolean
        dvd:
            type: boolean
        hifi:
            type: boolean
        speakers:
            type: boolean
        iwb:
            type: boolean
        phoneInt:
            type: string
            length: '5'
            nullable: true
        phoneExt:
            type: string
            length: '20'
            nullable: true
        comment:
            type: text
            nullable: true
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    manyToOne:
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                createdBy:
                    referencedColumnName: id
                    
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modifiedBy:
                    referencedColumnName: id
        campus:
            targetEntity: Busybee\InstituteBundle\Entity\Campus
            joinColumns:
                campus:
                    referencedColumnName: id
        staff1:
            targetEntity: Busybee\PersonBundle\Entity\Staff
            joinColumns:
                staff1:
                    referencedColumnName: id
        staff2:
            targetEntity: Busybee\PersonBundle\Entity\Staff
            joinColumns:
                staff2:
                    referencedColumnName: id
