Busybee\InstituteBundle\Entity\StudentYear:
    type: entity
    table: student_year
    repositoryClass: Busybee\InstituteBundle\Repository\StudentYearRepository
    uniqueConstraints:
        name:
            columns: [ year_id, name ]
        nameShort:
            columns: [ year_id, nameShort ]
        sequence:
            columns: [ year_id, sequence ]
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '15'
        nameShort:
            type: string
            length: '4'
        sequence:
            type: string
            length: '3'
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    manyToOne:
        year:
            targetEntity: Busybee\InstituteBundle\Entity\Year
            inversedBy: studentYears
            joinColumn:
                name: year_id
                referencedColumnName: id
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                createdBy:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modifiedBy:
                    referencedColumnName: id

