Busybee\InstituteBundle\Entity\Term:
    type: entity
    table: calendar_term
    repositoryClass: Busybee\InstituteBundle\Repository\YearRepository
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [name, year]
            errorPath: name
            message: 'term.unique'
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [nameShort, year]
            errorPath: nameShort
            message: 'term.unique'
    uniqueConstraints:
        name_year:
            columns: [ name, year_id ]
        nameShort_year:
            columns: [ nameShort, year_id ]
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
        nameShort:
            type: string
            length: '6'
        firstDay:
            type: date
        lastDay:
            type: date
        lastModified:
            type: datetime
            nullable: true 
        createdOn:
            type: datetime
            nullable: true 
    manyToOne:
        year:
            targetEntity: Busybee\InstituteBundle\Entity\Year
            inversedBy: terms
            joinColumn:
                name: year_id
                referencedColumnName: id
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                createdBy:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modifiedBy:
                    referencedColumnName: id
