Busybee\InstituteBundle\Entity\Term:
    type: entity
    table: calendar_term
    repositoryClass: Busybee\InstituteBundle\Repository\YearRepository
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [name, year]
            errorPath: name
            message: 'The Term Name must be unique within the year.'
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [shortName, year]
            errorPath: shortName
            message: 'The term Short Name must be unique within the year.'
    uniqueConstraints:
        name_year:
            columns: [ name, year_id ]
        shortName_year:
            columns: [ shortName, year_id ]
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
        shortName:
            type: string
            length: '6'
        firstDay:
            type: date
        lastDay:
            type: date
        lastModified:
            type: datetime
            nullable: true 
        createdOn:
            type: datetime
            nullable: true 
    manyToOne:
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                createdBy:
                    referencedColumnName: id
                    
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modifiedBy:
                    referencedColumnName: id
        year:
            targetEntity: Busybee\InstituteBundle\Entity\Year
            inversedBy: terms
            joinColumn:
                name: year_id
                referencedColumnName: id