Busybee\People\AddressBundle\Entity\Address:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - buildingType
                - buildingNumber
                - streetNumber
                - propertyName
                - streetName
                - locality
            errorPath: streetName
            message: 'address.unique'
    properties:
        buildingType:
            - \Busybee\Core\TemplateBundle\Validator\SettingChoice:
                name: 'address.buildingtype'
        locality:
            - Valid: ~
        streetName:
            - NotBlank: ~