parameters:
    version:
        system: '0.0.00'
        database: '0.0.00'
services:
    busybee_core_install.model.logger:
        class: Busybee\Core\InstallBundle\Model\Logger
        arguments: ['@logger']
        tags:
            - { name: monolog.logger, channel: busybee }
    monolog.formatter.line_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] [%%extra.token%%] %%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"
    busybee_core_security.security.user_provider:
        class: Busybee\Core\InstallBundle\Model\UserProvider
    busybee_core_security.model.login_handler:
        class: Busybee\Core\InstallBundle\Model\loginHandler
        arguments:
            - '@router'
            - '@doctrine.orm.entity_manager'
            - '@service_container'
    busybee_core_security.model.failure_handler:
        class:  Busybee\Core\InstallBundle\Model\failureHandler
        arguments:
            - "@http_kernel"
            - "@security.http_utils"
            - {}
            - '@service_container'
        tags:
            - { name: 'busybee_core_install.model.logger', channel: 'security' }
    busybee_core_install.router.advanced_loader:
        class: Busybee\Core\InstallBundle\Router\AdvancedLoader
        tags:
            - { name: routing.loader }
    busybee_core_system.setting.setting_manager:
        class: Busybee\Core\InstallBundle\Model\SettingManager
    busybee_core_install.model.menu_manager:
        class: Busybee\Core\InstallBundle\Model\MenuManager
    busybee_core_install.extension.user_manager_extension:
        class: Busybee\Core\InstallBundle\Extension\UserManagerExtension
        tags:
            - { name: twig.extension }
