parameters:
    TemplateBundle:
        version: 0.0.01
        settings:
            resources:
                - 'BusybeeTemplateBundle/Resources/config/Settings/Settings_0_0_01.yml'
    buttons:
        save:
            class: "halflings halflings-save btn btn-success"
            type: submit
            title: 'form.save'
            style: 'float: right;'
            additional: ''
            prompt: ''
        cancel:
            class: "halflings halflings-remove-circle btn btn-info"
            type: button
            title: 'form.cancel'
            style: 'float: right;'
            additional: ''
            prompt: ''
        upload:
            class: "halflings halflings-cloud-upload btn btn-success"
            type: submit
            title: 'form.upload'
            style: 'float: right;'
            additional: ''
            prompt: ''
        add:
            class: "halflings halflings-plus-sign btn btn-info"
            type: button
            title: 'form.add'
            style: 'float: right;'
            additional: ''
            prompt: ''
        edit:
            class: "halflings halflings-edit btn btn-info"
            type: button
            title: 'form.edit'
            style: 'float: right;'
            additional: ''
            prompt: ''
        proceed:
            class: "halflings halflings-hand-right btn btn-info"
            type: button
            title: 'form.proceed'
            style: 'float: right;'
            additional: ''
            prompt: ''
        return:
            class: "halflings halflings-hand-left btn btn-primary"
            type: button
            title: 'form.return'
            style: 'float: right;'
            additional: ''
            prompt: ''
        delete:
            class: "halflings halflings-erase btn btn-danger"
            type: button
            title: 'form.delete'
            style: 'float: right;'
            additional: ''
            prompt: ''
        reset:
            class: "halflings halflings-refresh btn btn-warning"
            type: reset
            title: 'form.reset'
            style: 'float: right;'
            additional: ''
            prompt: ''
        misc:
            class: ""
            type: button
            title: 'form.misc'
            style: 'float: right;'
            additional: ''
            prompt: ''
        close:
            class: "halflings halflings-remove-sign btn btn-primary"
            type: button
            title: 'form.close'
            style: 'float: right;'
            additional: 'onclick="window.close();"'
            prompt: ''
        up:
            class: "collection-up collection-action halflings halflings-arrow-up btn btn-default"
            type: button
            title: 'form.up'
            style: 'float: right;'
            additional: ''
            prompt: ''
        down:
            class: "collection-down collection-action halflings halflings-arrow-down btn btn-default"
            type: button
            title: 'form.down'
            style: 'float: right;'
            additional: ''
            prompt: ''
services:
    form.errors.parser:
        class: Busybee\Core\TemplateBundle\Model\FormErrorsParser
    form.all_form_errors_extension:
        class: Busybee\Core\TemplateBundle\Extension\FormErrorsExtension
        arguments:
            - '@form.errors.parser'
            - '@translator'
        tags:
            - { name: twig.extension }
    form.type.image:
        class: Busybee\Core\TemplateBundle\Type\ImageType
        arguments:
            - '@image.uploader'
        tags: 
            - { name: form.type }    
    image.uploader:
        class: Busybee\Core\TemplateBundle\Model\ImageUploader
        arguments:
            - "%upload_path%"
    validator.logo:
        class: Busybee\Core\TemplateBundle\Validator\Logo
    validator.logo.constraint:
        class: Busybee\Core\TemplateBundle\Validator\Constraints\LogoValidator
        tags:
            - { name: validator.constraint_validator, alias: logo_validator }
    validator.background.image:
        class: Busybee\Core\TemplateBundle\Validator\BackgroundImage
    validator.background.image.constraint:
        class: Busybee\Core\TemplateBundle\Validator\Constraints\BackgroundImageValidator
        tags:
            - { name: validator.constraint_validator, alias: background_image_validator }
    form.time.type:
        class: Busybee\Core\TemplateBundle\Type\TimeType
        arguments:
            - '%timezone%'
        tags: 
            - { name: form.type }
    validator.setting.choice.constraint:
        class: Busybee\Core\TemplateBundle\Validator\Constraints\SettingChoiceValidator
        arguments:
            - '@busybee_core_system.setting.setting_manager'
        tags:
            - { name: validator.constraint_validator, alias: setting_validator }
    validator.blank.or.valid.constraint:
        class: Busybee\Core\TemplateBundle\Validator\Constraints\BlankOrValidValidator
        tags:
            - { name: validator.constraint_validator, alias: blank_or_valid_validator }
    file.uploader:
        class: Busybee\Core\TemplateBundle\Model\FileUpLoad
        arguments:
            - "%upload_path%"
    form.type.csv:
        class: Busybee\Core\TemplateBundle\Type\CSVType
        arguments:
            - '@file.uploader'
        tags:
            - { name: form.type }
    form.type.yaml:
        class: Busybee\Core\TemplateBundle\Type\YamlType
        arguments:
            - '@file.uploader'
        tags:
            - { name: form.type }
    form.type.setting.choice:
        class: Busybee\Core\TemplateBundle\Type\SettingChoiceType
        arguments:
            - '@busybee_core_system.setting.setting_manager'
        tags:
            - { name: form.type }
    validator.unique.or.blank:
        class: Busybee\Core\TemplateBundle\Validator\Constraints\UniqueOrBlankValidator
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: validator.constraint_validator, alias: unique_or_blank_validator }
    validator.integer.constraint:
        class: Busybee\Core\TemplateBundle\Validator\Constraints\IntegerValidator
        tags:
            - { name: validator.constraint_validator, alias: integer_validator }
    validator.nowhitespace.constraint:
        class: Busybee\Core\TemplateBundle\Validator\Constraints\NoWhiteSpaceValidator
        tags:
            - { name: validator.constraint_validator, alias: nowhitespace_validator }
    validator.uppercase.constraint:
        class: Busybee\Core\TemplateBundle\Validator\Constraints\UpperCaseValidator
        tags:
            - { name: validator.constraint_validator, alias: uppercase_validator }
    version.manager:
        class: Busybee\Core\TemplateBundle\Model\VersionManager
        arguments:
            - '@doctrine.dbal.default_connection'
            - '@busybee_core_system.setting.setting_manager'
            - '%version%'
            - '@translator'
    busybee_form.button.extension:
        class: Busybee\Core\TemplateBundle\Extension\ButtonExtension
        arguments:
            - '%buttons%'
            - '@translator'
        tags:
            - { name: twig.extension }
    busybee_form.setting.extension:
        class: Busybee\Core\TemplateBundle\Extension\SettingExtension
        arguments:
            - '@busybee_core_system.setting.setting_manager'
            - '@menu.manager'
            - '@busybee.parameters'
        tags:
            - { name: twig.extension }
    busybee_form.session.extension:
        class: Busybee\Core\TemplateBundle\Extension\SessionExtension
        arguments:
            - '@session'
        tags:
            - { name: twig.extension }
    busybee_form.flash.extension:
        class: Busybee\Core\TemplateBundle\Extension\FlashExtension
        tags:
            - { name: twig.extension }
    busybee_form.password.validator:
        class: Busybee\Core\TemplateBundle\Validator\Constraints\PasswordValidator
        tags:
            - { name: validator.constraint_validator, alias: password.validator  }
        arguments:
            - '%password%'
    install.manager:
        class: Busybee\Core\TemplateBundle\Model\InstallManager
        arguments:
            - '%kernel.project_dir%'
            - '@doctrine.dbal.connection_factory'
            - '@system.password.manager'
    system.password.manager:
        class: Busybee\Core\TemplateBundle\Model\PasswordManager
