parameters:
    TemplateBundle:
        version: 0.0.01
        settings:
            resources:
                - 'BusybeeTemplateBundle/Resources/config/Settings/Settings_0_0_01.yml'
    buttons:
        save:
            class: "halflings halflings-save btn btn-success"
            type: submit
            title: 'form.save'
            style: 'float: right;'
            additional: ''
            prompt: ''
        cancel:
            class: "halflings halflings-remove-circle btn btn-info"
            type: button
            title: 'form.cancel'
            style: 'float: right;'
            additional: ''
            prompt: ''
        upload:
            class: "halflings halflings-cloud-upload btn btn-success"
            type: submit
            title: 'form.upload'
            style: 'float: right;'
            additional: ''
            prompt: ''
        add:
            class: "halflings halflings-plus-sign btn btn-info"
            type: button
            title: 'form.add'
            style: 'float: right;'
            additional: ''
            prompt: ''
        edit:
            class: "halflings halflings-edit btn btn-info"
            type: button
            title: 'form.edit'
            style: 'float: right;'
            additional: ''
            prompt: ''
        proceed:
            class: "halflings halflings-hand-right btn btn-info"
            type: button
            title: 'form.proceed'
            style: 'float: right;'
            additional: ''
            prompt: ''
        return:
            class: "halflings halflings-hand-left btn btn-primary"
            type: button
            title: 'form.return'
            style: 'float: right;'
            additional: ''
            prompt: ''
        delete:
            class: "halflings halflings-erase btn btn-danger"
            type: button
            title: 'form.delete'
            style: 'float: right;'
            additional: ''
            prompt: ''
        reset:
            class: "halflings halflings-refresh btn btn-warning"
            type: reset
            title: 'form.reset'
            style: 'float: right;'
            additional: ''
            prompt: ''
        misc:
            class: ""
            type: button
            title: 'form.misc'
            style: 'float: right;'
            additional: ''
            prompt: ''
        close:
            class: "halflings halflings-remove-sign btn btn-primary"
            type: button
            title: 'form.close'
            style: 'float: right;'
            additional: 'onclick="window.close();"'
            prompt: ''
        duplicate:
            class: "halflings halflings-duplicate btn btn-primary"
            type: button
            title: 'form.duplicate'
            style: 'float: right;'
            additional: ''
            prompt: ''
        up:
            class: "collection-up collection-action halflings halflings-arrow-up btn btn-default"
            type: button
            title: 'form.up'
            style: 'float: right;'
            additional: ''
            prompt: ''
        down:
            class: "collection-down collection-action halflings halflings-arrow-down btn btn-default"
            type: button
            title: 'form.down'
            style: 'float: right;'
            additional: ''
            prompt: ''
        on:
            class: "halflings halflings-thumbs-up btn btn-danger"
            type: button
            title: 'form.on'
            style: 'float: right;'
            additional: ''
            prompt: ''
        off:
            class: "halflings halflings-thumbs-down btn btn-success"
            type: button
            title: 'form.off'
            style: 'float: right;'
            additional: ''
            prompt: ''
services:
    busybee_core_template.model.form_errors_parser:
        class: Busybee\Core\TemplateBundle\Model\FormErrorsParser
    busybee_core_template.extension.form_errors_extension:
        class: Busybee\Core\TemplateBundle\Extension\FormErrorsExtension
        arguments:
            - '@busybee_core_template.model.form_errors_parser'
            - '@translator'
        tags:
            - { name: twig.extension }
    busybee_core_template.type.image_type:
        class: Busybee\Core\TemplateBundle\Type\ImageType
        arguments:
            - '%upload_path%'
        tags: 
            - { name: form.type }    
    busybee_core_template.validator.logo:
        class: Busybee\Core\TemplateBundle\Validator\Logo
    busybee_core_template.validator.constraints.logo_validator:
        class: Busybee\Core\TemplateBundle\Validator\Constraints\LogoValidator
        tags:
            - { name: validator.constraint_validator, alias: logo_validator }
    busybee_core_template.validator.background_image:
        class: Busybee\Core\TemplateBundle\Validator\BackgroundImage
    busybee_core_template.validator.constraints.background_image_validator:
        class: Busybee\Core\TemplateBundle\Validator\Constraints\BackgroundImageValidator
        tags:
            - { name: validator.constraint_validator, alias: background_image_validator }
    busybee_core_template.type.time_type:
        class: Busybee\Core\TemplateBundle\Type\TimeType
        arguments:
            - '%timezone%'
        tags: 
            - { name: form.type }
    busybee_core_template.validator.constraints.setting_choice_validator:
        class: Busybee\Core\TemplateBundle\Validator\Constraints\SettingChoiceValidator
        arguments:
            - '@busybee_core_system.setting.setting_manager'
        tags:
            - { name: validator.constraint_validator, alias: setting_validator }
    busybee_core_template.validator.constraints.blank_or_valid_validator:
        class: Busybee\Core\TemplateBundle\Validator\Constraints\BlankOrValidValidator
        tags:
            - { name: validator.constraint_validator, alias: blank_or_valid_validator }
    busybee_core_template.model.file_upload:
        class: Busybee\Core\TemplateBundle\Model\FileUpLoad
        arguments:
            - "%upload_path%"
    busybee_core_template.type.csv_type:
        class: Busybee\Core\TemplateBundle\Type\CSVType
        arguments:
            - '@busybee_core_template.model.file_upload'
        tags:
            - { name: form.type }
    busybee_core_template.type.yaml_type:
        class: Busybee\Core\TemplateBundle\Type\YamlType
        arguments:
            - '@busybee_core_template.model.file_upload'
        tags:
            - { name: form.type }
    busybee_core_template.type.setting_choice_type:
        class: Busybee\Core\TemplateBundle\Type\SettingChoiceType
        arguments:
            - '@busybee_core_system.setting.setting_manager'
            - '@translator'
        tags:
            - { name: form.type }
    busybee_core_template.validator.constraints.unique_or_blank_validator:
        class: Busybee\Core\TemplateBundle\Validator\Constraints\UniqueOrBlankValidator
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: validator.constraint_validator, alias: unique_or_blank_validator }
    busybee_core_template.validator.constraints.integer_validator:
        class: Busybee\Core\TemplateBundle\Validator\Constraints\IntegerValidator
        tags:
            - { name: validator.constraint_validator, alias: integer_validator }
    busybee_core_template.validator.constraints.no_white_space_validator:
        class: Busybee\Core\TemplateBundle\Validator\Constraints\NoWhiteSpaceValidator
        tags:
            - { name: validator.constraint_validator, alias: nowhitespace_validator }
    busybee_core_template.model.version_manager:
        class: Busybee\Core\TemplateBundle\Model\VersionManager
        arguments:
            - '@doctrine.dbal.default_connection'
            - '@busybee_core_system.setting.setting_manager'
            - '%version%'
            - '@translator'
    busybee_core_template.extension.button_extension:
        class: Busybee\Core\TemplateBundle\Extension\ButtonExtension
        arguments:
            - '%buttons%'
            - '@translator'
        tags:
            - { name: twig.extension }
    busybee_core_template.extension.setting_extension:
        class: Busybee\Core\TemplateBundle\Extension\SettingExtension
        arguments:
            - '@busybee_core_system.setting.setting_manager'
            - '@busybee_core_home.model.menu_manager'
            - '@busybee.parameters'
        tags:
            - { name: twig.extension }
    busybee_core_template.extension.session_extension:
        class: Busybee\Core\TemplateBundle\Extension\SessionExtension
        arguments:
            - '@session'
        tags:
            - { name: twig.extension }
    busybee_core_template.extension.flash_extension:
        class: Busybee\Core\TemplateBundle\Extension\FlashExtension
        tags:
            - { name: twig.extension }
    busybee_core_template.validator.constraints.password_validator:
        class: Busybee\Core\TemplateBundle\Validator\Constraints\PasswordValidator
        tags:
            - { name: validator.constraint_validator, alias: password.validator  }
        arguments:
            - '%password%'
    busybee_core_template.model.install_manager:
        class: Busybee\Core\TemplateBundle\Model\InstallManager
        arguments:
            - '%kernel.project_dir%'
            - '@doctrine.dbal.connection_factory'
            - '@busybee_core_system.password.password_manager'
    busybee_core_system.password.password_manager:
        class: Busybee\Core\TemplateBundle\Model\PasswordManager
    busybee_core_template.extension.router_extension:
        class: Busybee\Core\TemplateBundle\Extension\RouterExtension
        arguments:
            - '@router'
        tags:
            - { name: twig.extension }
    busybee_core_template.model.logger:
        class: Busybee\Core\TemplateBundle\Model\Logger
        arguments: ['@logger']
        tags:
            - { name: monolog.logger, channel: busybee }
    busybee.parameters:
        public: false
        class: stdClass
        factory:
            - '@busybee_core_system.model.my_container'
            - 'getParameterBag'
    busybee_core_template.model.tab_manager:
        class: Busybee\Core\TemplateBundle\Model\TabManager
        arguments:
            - '@busybee.parameters'
    busybee_core_template.model.photo_uploader:
        class: Busybee\Core\TemplateBundle\Model\PhotoUploader
        arguments:
            - "%upload_path%"
    busybee_core_template.extension.image_extension:
        class: Busybee\Core\TemplateBundle\Extension\ImageExtension
        tags:
            - { name: twig.extension }
    busybee_core_template.type.entity_type:
        class: Busybee\Core\TemplateBundle\Type\EntityType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
    busybee_core_template.type.hidden_entity_type:
        class: Busybee\Core\TemplateBundle\Type\HiddenEntityType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
