Busybee\Management\GradeBundle\Entity\StudentGrade:
    type: entity
    table: grade_by_student
    repositoryClass: Busybee\Management\GradeBundle\Repository\StudentGradeRepository
    uniqueConstraints:
         student_grade:
             columns:
                 - student_id
                 - grade_id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        status:
            type: string
            length: '32'
        lastModified:
            type: datetime
            column: last_modified
        createdOn:
            type: datetime
            column: created_on
    manyToOne:
        grade:
            targetEntity: Busybee\Core\CalendarBundle\Entity\Grade
            inversedBy: students
            joinColumns:
                grade_id:
                    referencedColumnName: id
        student:
            targetEntity: Busybee\People\StudentBundle\Entity\Student
            inversedBy: grades
            joinColumns:
                student_id:
                    referencedColumnName: id
        createdBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\Core\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
