# src\Busybee\SecurityBundle\Resources\config\doctrine\Group.orm.yml
Busybee\SecurityBundle\Entity\Group:
    type: entity
    table: secure_groups
    repositoryClass: Busybee\SecurityBundle\Entity\GroupRepository
    indexes:
        groupname:
            columns: [ groupname ] 
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        groupname:
            type: string
            length: 64
            unique: true
        lastModified:
            type: datetime
            nullable: true
        createdOn:
            type: datetime
            nullable: true
    manyToOne:
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
                    nullable: true
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
                    nullable: true
    manyToMany:
        roles:
            targetEntity: Busybee\SecurityBundle\Entity\Role
            nullable: true 
            joinTable:
                name: secure_groups_to_roles
                joinColumns: 
                    group_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    role_id:
                        referencedColumnName: id
