# src\Busybee\SecurityBundle\Resources\config\doctrine\User.orm.yml
Busybee\SecurityBundle\Entity\Role:
    type: entity
    table: secure_roles
    repositoryClass: Busybee\SecurityBundle\Entity\RoleRepository
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [role]
            errorPath: role
            message: 'The Role Name must be unique.'
    indexes:
        rolename:
            columns: [ role ] 
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        role:
            type: string
            length: 64
            unique: true
    manyToMany:
        childrenRoles:
            targetEntity: Busybee\SecurityBundle\Entity\Role
            nullable: true 
            joinTable:
                name: secure_role_children
                joinColumns: 
                    role_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    child_role_id:
                        referencedColumnName: id
