# Family
parameters:
    family:
        details:
            label: family.tab.details
            include: 'BusybeeFamilyBundle:Family:details.html.twig'
            message: personMessage
        contacts:
            label: family.tab.contacts
            include: 'BusybeeFamilyBundle:Family:contacts.html.twig'
        students:
            label: family.tab.students
            include: 'BusybeeFamilyBundle:Family:studentPanel.html.twig'
        careGivers:
            label: family.tab.careGivers
            include: 'BusybeeFamilyBundle:Family:careGiverPanel.html.twig'