# System
parameters:
    nodes:
        1:
            name: System
            label: menu.system
            role: ROLE_USER
            order: 1
            menu: 1
    items:
        10:
            name: User Manage
            label: menu.site.security.user
            role: ROLE_USER
            node: 1
            order: 10
            menu: 10
        11:
            name: Update
            label: menu.site.update
            role: ROLE_ADMIN
            node: 1
            route: update_start
            order: 11
        12:
            name: Manage Setting
            label: menu.site.setting.manage
            role: ROLE_REGISTRAR
            node: 1
            route: setting_manage
            order: 12
        13:
            name: Plugin Manager
            label: menu.site.plugin.manage
            role: ROLE_ADMIN
            node: 1
            order: 13
            menu: 13
            test:
                value1: test.plugin.manage
                value2: true
                comparitor: !=
        100:
            label: menu.site.security.edit
            role: ROLE_USER
            node: 10
            route: busybee_security_user_edit
            parameters:
                'id': '0'
            order: 100
        101:
            name: Register User:
            label: menu.site.security.register
            grant: ROLE_REGISTRAR
            route: busybee_security_user_register
            node: 10
            order: 101
        102:
            name: Current User:
            label: menu.site.security.user
            grant: ROLE_REGISTRAR
            route: busybee_security_user_list
            node: 10
            order: 102
        
    