# System
parameters:
    nodes:
        1:
            name: System
            label: menu.system
            role: ROLE_USER
            order: 1
            menu: 1
    items:
        19:
            name: User Manage
            label: menu.site.security.user
            role: ROLE_USER
            node: 1
            order: 19
            menu: 19
        12:
            name: Manage System Settings
            label: menu.site.setting.manage
            role: ROLE_REGISTRAR
            node: 1
            route: setting_manage
            order: 12
            menu: 12
        190:
            label: menu.site.security.edit
            role: ROLE_USER
            node: 19
            route: security_user_edit
            parameters:
                'id': 'self'
            order: 100
        191:
            name: Register User
            label: menu.site.security.register
            role: ROLE_REGISTRAR
            route: security_user_register
            node: 19
            order: 101
        192:
            name: Current User
            label: menu.site.security.user
            role: ROLE_REGISTRAR
            route: security_user_list
            node: 19
            order: 102
        120:
            name: Manage Individual Setting
            label: menu.site.setting.individual
            role: ROLE_REGISTRAR
            node: 12
            route: setting_manage
            order: 120
        121:
            name: Upload Default Settings
            label: menu.site.setting.upload
            role: ROLE_REGISTRAR
            node: 12
            route: setting_upload
            order: 120
        122:
            name: Update
            label: menu.site.update
            role: ROLE_ADMIN
            node: 12
            route: update_start
            order: 122
            test:
                value1: test.update.available
                value2: true
                comparitor: ==
                default1: false
