Busybee\FamilyBundle\Entity\Family:
    type: entity
    table: family
    repositoryClass: Busybee\FamilyBundle\Repository\FamilyRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
        firstLanguage:
            type: string
            length: 16
            nullable: true
        secondLanguage:
            type: string
            length: 16
            nullable: true
        house:
             type: string
             length: 32
             nullable: true
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    oneToMany:
        careGiver:
            targetEntity: Busybee\FamilyBundle\Entity\CareGiver
            orderBy: { 'contactPriority': 'ASC' }
            mappedBy: family
            cascade: [ 'all' ]
            joinColumn:
                name: caregiver
                referencedColumnName: id
    manyToMany:
        phone:
            targetEntity: Busybee\People\PersonBundle\Entity\Phone
            cascade: [ 'persist' ]
            joinTable:
                name: family_phone
                joinColumns:
                    family_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    phone_id:
                        referencedColumnName: id
        students:
            targetEntity: Busybee\StudentBundle\Entity\Student
            orderBy: { 'startAtSchool': 'ASC' }
            cascade: [ 'persist' ]
            joinTable:
                name: family_student
                joinColumns:
                    family_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    student_id:
                        referencedColumnName: id
    manyToOne:
        address1:
            targetEntity: Busybee\People\PersonBundle\Entity\Address
            nullable: true
            joinColumns:
                address1:
                    referencedColumnName: id
        address2:
            targetEntity: Busybee\People\PersonBundle\Entity\Address
            nullable: true
            joinColumns:
                address2:
                    referencedColumnName: id
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id