Busybee\FamilyBundle\Entity\Family:
    type: entity
    table: family
    repositoryClass: Busybee\FamilyBundle\Repository\FamilyRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    manyToMany:
        phone:
            targetEntity: Busybee\PersonBundle\Entity\Phone
            cascade: [ 'persist' ]
            joinTable:
                name: family_phone
                joinColumns:
                    family_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    phone_id:
                        referencedColumnName: id
        emergencyContact:
            targetEntity: Busybee\PersonBundle\Entity\CareGiver
            cascade: [ 'persist' ]
            joinTable:
                name: family_emergency_contact
                joinColumns:
                    family_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    emergency_contact_id:
                        referencedColumnName: id
    manyToOne:
        careGiver1:
            targetEntity: Busybee\PersonBundle\Entity\CareGiver
            joinColumns:
                careGiver1:
                    referencedColumnName: id
        careGiver2:
            targetEntity: Busybee\PersonBundle\Entity\CareGiver
            nullable: true
            joinColumns:
                careGiver2:
                    referencedColumnName: id
        address1:
            targetEntity: Busybee\PersonBundle\Entity\Address
            nullable: true
            joinColumns:
                address1:
                    referencedColumnName: id
        address2:
            targetEntity: Busybee\PersonBundle\Entity\Address
            nullable: true
            joinColumns:
                address2:
                    referencedColumnName: id
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
