Busybee\FamilyBundle\Entity\FamilyCareGiver:
    type: entity
    table: family_caregiver
    repositoryClass: Busybee\FamilyBundle\Repository\FamilyCareGiverRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        contactOrder:
            type: integer
            length: '3'
            name: contact_order
        lastModified:
            type: datetime
        createdOn:
            type: datetime
    manyToOne:
        createdBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
        modifiedBy:
            targetEntity: Busybee\SecurityBundle\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
        family:
            targetEntity: Busybee\FamilyBundle\Entity\Family
            joinColumn:
                name: family_id
                referencedColumnName: id
        careGiver:
            targetEntity: Busybee\PersonBundle\Entity\CareGiver
            joinColumn:
                name: caregiver_id
                referencedColumnName: id
